// Code generated by ent, DO NOT EDIT.

package providerhallconfig

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
)

const (
	// Label holds the string label denoting the providerhallconfig type in the database.
	Label = "provider_hall_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCollectionEnabled holds the string denoting the collection_enabled field in the database.
	FieldCollectionEnabled = "collection_enabled"
	// FieldDisplayEnabled holds the string denoting the display_enabled field in the database.
	FieldDisplayEnabled = "display_enabled"
	// FieldTasksEnabled holds the string denoting the tasks_enabled field in the database.
	FieldTasksEnabled = "tasks_enabled"
	// FieldAutoScheduleEnabled holds the string denoting the auto_schedule_enabled field in the database.
	FieldAutoScheduleEnabled = "auto_schedule_enabled"
	// FieldDefaultModel holds the string denoting the default_model field in the database.
	FieldDefaultModel = "default_model"
	// FieldDefaultProtocol holds the string denoting the default_protocol field in the database.
	FieldDefaultProtocol = "default_protocol"
	// FieldDefaultRange holds the string denoting the default_range field in the database.
	FieldDefaultRange = "default_range"
	// FieldGatewayOrigin holds the string denoting the gateway_origin field in the database.
	FieldGatewayOrigin = "gateway_origin"
	// FieldOperatorUserID holds the string denoting the operator_user_id field in the database.
	FieldOperatorUserID = "operator_user_id"
	// FieldDailyBudget holds the string denoting the daily_budget field in the database.
	FieldDailyBudget = "daily_budget"
	// FieldExpectedNodes holds the string denoting the expected_nodes field in the database.
	FieldExpectedNodes = "expected_nodes"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the providerhallconfig in the database.
	Table = "provider_hall_config"
)

// Columns holds all SQL columns for providerhallconfig fields.
var Columns = []string{
	FieldID,
	FieldCollectionEnabled,
	FieldDisplayEnabled,
	FieldTasksEnabled,
	FieldAutoScheduleEnabled,
	FieldDefaultModel,
	FieldDefaultProtocol,
	FieldDefaultRange,
	FieldGatewayOrigin,
	FieldOperatorUserID,
	FieldDailyBudget,
	FieldExpectedNodes,
	FieldVersion,
	FieldUpdatedBy,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCollectionEnabled holds the default value on creation for the "collection_enabled" field.
	DefaultCollectionEnabled bool
	// DefaultDisplayEnabled holds the default value on creation for the "display_enabled" field.
	DefaultDisplayEnabled bool
	// DefaultTasksEnabled holds the default value on creation for the "tasks_enabled" field.
	DefaultTasksEnabled bool
	// DefaultAutoScheduleEnabled holds the default value on creation for the "auto_schedule_enabled" field.
	DefaultAutoScheduleEnabled bool
	// DefaultDefaultModel holds the default value on creation for the "default_model" field.
	DefaultDefaultModel string
	// DefaultModelValidator is a validator for the "default_model" field. It is called by the builders before save.
	DefaultModelValidator func(string) error
	// DefaultGatewayOrigin holds the default value on creation for the "gateway_origin" field.
	DefaultGatewayOrigin string
	// GatewayOriginValidator is a validator for the "gateway_origin" field. It is called by the builders before save.
	GatewayOriginValidator func(string) error
	// OperatorUserIDValidator is a validator for the "operator_user_id" field. It is called by the builders before save.
	OperatorUserIDValidator func(int64) error
	// DefaultDailyBudget holds the default value on creation for the "daily_budget" field.
	DefaultDailyBudget func() decimal.Decimal
	// DefaultExpectedNodes holds the default value on creation for the "expected_nodes" field.
	DefaultExpectedNodes []string
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int64) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID int64
)

// DefaultProtocol defines the type for the "default_protocol" enum field.
type DefaultProtocol string

// DefaultProtocolResponses is the default value of the DefaultProtocol enum.
const DefaultDefaultProtocol = DefaultProtocolResponses

// DefaultProtocol values.
const (
	DefaultProtocolResponses       DefaultProtocol = "responses"
	DefaultProtocolChatCompletions DefaultProtocol = "chat_completions"
	DefaultProtocolMessages        DefaultProtocol = "messages"
)

func (dp DefaultProtocol) String() string {
	return string(dp)
}

// DefaultProtocolValidator is a validator for the "default_protocol" field enum values. It is called by the builders before save.
func DefaultProtocolValidator(dp DefaultProtocol) error {
	switch dp {
	case DefaultProtocolResponses, DefaultProtocolChatCompletions, DefaultProtocolMessages:
		return nil
	default:
		return fmt.Errorf("providerhallconfig: invalid enum value for default_protocol field: %q", dp)
	}
}

// DefaultRange defines the type for the "default_range" enum field.
type DefaultRange string

// DefaultRange6h is the default value of the DefaultRange enum.
const DefaultDefaultRange = DefaultRange6h

// DefaultRange values.
const (
	DefaultRange6h  DefaultRange = "6h"
	DefaultRange24h DefaultRange = "24h"
	DefaultRange7d  DefaultRange = "7d"
	DefaultRange30d DefaultRange = "30d"
)

func (dr DefaultRange) String() string {
	return string(dr)
}

// DefaultRangeValidator is a validator for the "default_range" field enum values. It is called by the builders before save.
func DefaultRangeValidator(dr DefaultRange) error {
	switch dr {
	case DefaultRange6h, DefaultRange24h, DefaultRange7d, DefaultRange30d:
		return nil
	default:
		return fmt.Errorf("providerhallconfig: invalid enum value for default_range field: %q", dr)
	}
}

// OrderOption defines the ordering options for the ProviderHallConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCollectionEnabled orders the results by the collection_enabled field.
func ByCollectionEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectionEnabled, opts...).ToFunc()
}

// ByDisplayEnabled orders the results by the display_enabled field.
func ByDisplayEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayEnabled, opts...).ToFunc()
}

// ByTasksEnabled orders the results by the tasks_enabled field.
func ByTasksEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTasksEnabled, opts...).ToFunc()
}

// ByAutoScheduleEnabled orders the results by the auto_schedule_enabled field.
func ByAutoScheduleEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoScheduleEnabled, opts...).ToFunc()
}

// ByDefaultModel orders the results by the default_model field.
func ByDefaultModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultModel, opts...).ToFunc()
}

// ByDefaultProtocol orders the results by the default_protocol field.
func ByDefaultProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultProtocol, opts...).ToFunc()
}

// ByDefaultRange orders the results by the default_range field.
func ByDefaultRange(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultRange, opts...).ToFunc()
}

// ByGatewayOrigin orders the results by the gateway_origin field.
func ByGatewayOrigin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayOrigin, opts...).ToFunc()
}

// ByOperatorUserID orders the results by the operator_user_id field.
func ByOperatorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorUserID, opts...).ToFunc()
}

// ByDailyBudget orders the results by the daily_budget field.
func ByDailyBudget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyBudget, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
