// Code generated by ent, DO NOT EDIT.

package providerhallconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLTE(FieldID, id))
}

// CollectionEnabled applies equality check predicate on the "collection_enabled" field. It's identical to CollectionEnabledEQ.
func CollectionEnabled(v bool) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldCollectionEnabled, v))
}

// DisplayEnabled applies equality check predicate on the "display_enabled" field. It's identical to DisplayEnabledEQ.
func DisplayEnabled(v bool) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldDisplayEnabled, v))
}

// TasksEnabled applies equality check predicate on the "tasks_enabled" field. It's identical to TasksEnabledEQ.
func TasksEnabled(v bool) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldTasksEnabled, v))
}

// AutoScheduleEnabled applies equality check predicate on the "auto_schedule_enabled" field. It's identical to AutoScheduleEnabledEQ.
func AutoScheduleEnabled(v bool) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldAutoScheduleEnabled, v))
}

// DefaultModel applies equality check predicate on the "default_model" field. It's identical to DefaultModelEQ.
func DefaultModel(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldDefaultModel, v))
}

// GatewayOrigin applies equality check predicate on the "gateway_origin" field. It's identical to GatewayOriginEQ.
func GatewayOrigin(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldGatewayOrigin, v))
}

// OperatorUserID applies equality check predicate on the "operator_user_id" field. It's identical to OperatorUserIDEQ.
func OperatorUserID(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldOperatorUserID, v))
}

// DailyBudget applies equality check predicate on the "daily_budget" field. It's identical to DailyBudgetEQ.
func DailyBudget(v decimal.Decimal) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldDailyBudget, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldVersion, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// CollectionEnabledEQ applies the EQ predicate on the "collection_enabled" field.
func CollectionEnabledEQ(v bool) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldCollectionEnabled, v))
}

// CollectionEnabledNEQ applies the NEQ predicate on the "collection_enabled" field.
func CollectionEnabledNEQ(v bool) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldCollectionEnabled, v))
}

// DisplayEnabledEQ applies the EQ predicate on the "display_enabled" field.
func DisplayEnabledEQ(v bool) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldDisplayEnabled, v))
}

// DisplayEnabledNEQ applies the NEQ predicate on the "display_enabled" field.
func DisplayEnabledNEQ(v bool) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldDisplayEnabled, v))
}

// TasksEnabledEQ applies the EQ predicate on the "tasks_enabled" field.
func TasksEnabledEQ(v bool) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldTasksEnabled, v))
}

// TasksEnabledNEQ applies the NEQ predicate on the "tasks_enabled" field.
func TasksEnabledNEQ(v bool) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldTasksEnabled, v))
}

// AutoScheduleEnabledEQ applies the EQ predicate on the "auto_schedule_enabled" field.
func AutoScheduleEnabledEQ(v bool) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldAutoScheduleEnabled, v))
}

// AutoScheduleEnabledNEQ applies the NEQ predicate on the "auto_schedule_enabled" field.
func AutoScheduleEnabledNEQ(v bool) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldAutoScheduleEnabled, v))
}

// DefaultModelEQ applies the EQ predicate on the "default_model" field.
func DefaultModelEQ(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldDefaultModel, v))
}

// DefaultModelNEQ applies the NEQ predicate on the "default_model" field.
func DefaultModelNEQ(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldDefaultModel, v))
}

// DefaultModelIn applies the In predicate on the "default_model" field.
func DefaultModelIn(vs ...string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldIn(FieldDefaultModel, vs...))
}

// DefaultModelNotIn applies the NotIn predicate on the "default_model" field.
func DefaultModelNotIn(vs ...string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNotIn(FieldDefaultModel, vs...))
}

// DefaultModelGT applies the GT predicate on the "default_model" field.
func DefaultModelGT(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGT(FieldDefaultModel, v))
}

// DefaultModelGTE applies the GTE predicate on the "default_model" field.
func DefaultModelGTE(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGTE(FieldDefaultModel, v))
}

// DefaultModelLT applies the LT predicate on the "default_model" field.
func DefaultModelLT(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLT(FieldDefaultModel, v))
}

// DefaultModelLTE applies the LTE predicate on the "default_model" field.
func DefaultModelLTE(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLTE(FieldDefaultModel, v))
}

// DefaultModelContains applies the Contains predicate on the "default_model" field.
func DefaultModelContains(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldContains(FieldDefaultModel, v))
}

// DefaultModelHasPrefix applies the HasPrefix predicate on the "default_model" field.
func DefaultModelHasPrefix(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldHasPrefix(FieldDefaultModel, v))
}

// DefaultModelHasSuffix applies the HasSuffix predicate on the "default_model" field.
func DefaultModelHasSuffix(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldHasSuffix(FieldDefaultModel, v))
}

// DefaultModelEqualFold applies the EqualFold predicate on the "default_model" field.
func DefaultModelEqualFold(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEqualFold(FieldDefaultModel, v))
}

// DefaultModelContainsFold applies the ContainsFold predicate on the "default_model" field.
func DefaultModelContainsFold(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldContainsFold(FieldDefaultModel, v))
}

// DefaultProtocolEQ applies the EQ predicate on the "default_protocol" field.
func DefaultProtocolEQ(v DefaultProtocol) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldDefaultProtocol, v))
}

// DefaultProtocolNEQ applies the NEQ predicate on the "default_protocol" field.
func DefaultProtocolNEQ(v DefaultProtocol) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldDefaultProtocol, v))
}

// DefaultProtocolIn applies the In predicate on the "default_protocol" field.
func DefaultProtocolIn(vs ...DefaultProtocol) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldIn(FieldDefaultProtocol, vs...))
}

// DefaultProtocolNotIn applies the NotIn predicate on the "default_protocol" field.
func DefaultProtocolNotIn(vs ...DefaultProtocol) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNotIn(FieldDefaultProtocol, vs...))
}

// DefaultRangeEQ applies the EQ predicate on the "default_range" field.
func DefaultRangeEQ(v DefaultRange) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldDefaultRange, v))
}

// DefaultRangeNEQ applies the NEQ predicate on the "default_range" field.
func DefaultRangeNEQ(v DefaultRange) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldDefaultRange, v))
}

// DefaultRangeIn applies the In predicate on the "default_range" field.
func DefaultRangeIn(vs ...DefaultRange) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldIn(FieldDefaultRange, vs...))
}

// DefaultRangeNotIn applies the NotIn predicate on the "default_range" field.
func DefaultRangeNotIn(vs ...DefaultRange) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNotIn(FieldDefaultRange, vs...))
}

// GatewayOriginEQ applies the EQ predicate on the "gateway_origin" field.
func GatewayOriginEQ(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldGatewayOrigin, v))
}

// GatewayOriginNEQ applies the NEQ predicate on the "gateway_origin" field.
func GatewayOriginNEQ(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldGatewayOrigin, v))
}

// GatewayOriginIn applies the In predicate on the "gateway_origin" field.
func GatewayOriginIn(vs ...string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldIn(FieldGatewayOrigin, vs...))
}

// GatewayOriginNotIn applies the NotIn predicate on the "gateway_origin" field.
func GatewayOriginNotIn(vs ...string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNotIn(FieldGatewayOrigin, vs...))
}

// GatewayOriginGT applies the GT predicate on the "gateway_origin" field.
func GatewayOriginGT(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGT(FieldGatewayOrigin, v))
}

// GatewayOriginGTE applies the GTE predicate on the "gateway_origin" field.
func GatewayOriginGTE(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGTE(FieldGatewayOrigin, v))
}

// GatewayOriginLT applies the LT predicate on the "gateway_origin" field.
func GatewayOriginLT(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLT(FieldGatewayOrigin, v))
}

// GatewayOriginLTE applies the LTE predicate on the "gateway_origin" field.
func GatewayOriginLTE(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLTE(FieldGatewayOrigin, v))
}

// GatewayOriginContains applies the Contains predicate on the "gateway_origin" field.
func GatewayOriginContains(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldContains(FieldGatewayOrigin, v))
}

// GatewayOriginHasPrefix applies the HasPrefix predicate on the "gateway_origin" field.
func GatewayOriginHasPrefix(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldHasPrefix(FieldGatewayOrigin, v))
}

// GatewayOriginHasSuffix applies the HasSuffix predicate on the "gateway_origin" field.
func GatewayOriginHasSuffix(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldHasSuffix(FieldGatewayOrigin, v))
}

// GatewayOriginEqualFold applies the EqualFold predicate on the "gateway_origin" field.
func GatewayOriginEqualFold(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEqualFold(FieldGatewayOrigin, v))
}

// GatewayOriginContainsFold applies the ContainsFold predicate on the "gateway_origin" field.
func GatewayOriginContainsFold(v string) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldContainsFold(FieldGatewayOrigin, v))
}

// OperatorUserIDEQ applies the EQ predicate on the "operator_user_id" field.
func OperatorUserIDEQ(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldOperatorUserID, v))
}

// OperatorUserIDNEQ applies the NEQ predicate on the "operator_user_id" field.
func OperatorUserIDNEQ(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldOperatorUserID, v))
}

// OperatorUserIDIn applies the In predicate on the "operator_user_id" field.
func OperatorUserIDIn(vs ...int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDNotIn applies the NotIn predicate on the "operator_user_id" field.
func OperatorUserIDNotIn(vs ...int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNotIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDGT applies the GT predicate on the "operator_user_id" field.
func OperatorUserIDGT(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGT(FieldOperatorUserID, v))
}

// OperatorUserIDGTE applies the GTE predicate on the "operator_user_id" field.
func OperatorUserIDGTE(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGTE(FieldOperatorUserID, v))
}

// OperatorUserIDLT applies the LT predicate on the "operator_user_id" field.
func OperatorUserIDLT(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLT(FieldOperatorUserID, v))
}

// OperatorUserIDLTE applies the LTE predicate on the "operator_user_id" field.
func OperatorUserIDLTE(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLTE(FieldOperatorUserID, v))
}

// OperatorUserIDIsNil applies the IsNil predicate on the "operator_user_id" field.
func OperatorUserIDIsNil() predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldIsNull(FieldOperatorUserID))
}

// OperatorUserIDNotNil applies the NotNil predicate on the "operator_user_id" field.
func OperatorUserIDNotNil() predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNotNull(FieldOperatorUserID))
}

// DailyBudgetEQ applies the EQ predicate on the "daily_budget" field.
func DailyBudgetEQ(v decimal.Decimal) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldDailyBudget, v))
}

// DailyBudgetNEQ applies the NEQ predicate on the "daily_budget" field.
func DailyBudgetNEQ(v decimal.Decimal) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldDailyBudget, v))
}

// DailyBudgetIn applies the In predicate on the "daily_budget" field.
func DailyBudgetIn(vs ...decimal.Decimal) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldIn(FieldDailyBudget, vs...))
}

// DailyBudgetNotIn applies the NotIn predicate on the "daily_budget" field.
func DailyBudgetNotIn(vs ...decimal.Decimal) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNotIn(FieldDailyBudget, vs...))
}

// DailyBudgetGT applies the GT predicate on the "daily_budget" field.
func DailyBudgetGT(v decimal.Decimal) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGT(FieldDailyBudget, v))
}

// DailyBudgetGTE applies the GTE predicate on the "daily_budget" field.
func DailyBudgetGTE(v decimal.Decimal) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGTE(FieldDailyBudget, v))
}

// DailyBudgetLT applies the LT predicate on the "daily_budget" field.
func DailyBudgetLT(v decimal.Decimal) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLT(FieldDailyBudget, v))
}

// DailyBudgetLTE applies the LTE predicate on the "daily_budget" field.
func DailyBudgetLTE(v decimal.Decimal) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLTE(FieldDailyBudget, v))
}

// DailyBudgetContains applies the Contains predicate on the "daily_budget" field.
func DailyBudgetContains(v decimal.Decimal) predicate.ProviderHallConfig {
	vc := v.String()
	return predicate.ProviderHallConfig(sql.FieldContains(FieldDailyBudget, vc))
}

// DailyBudgetHasPrefix applies the HasPrefix predicate on the "daily_budget" field.
func DailyBudgetHasPrefix(v decimal.Decimal) predicate.ProviderHallConfig {
	vc := v.String()
	return predicate.ProviderHallConfig(sql.FieldHasPrefix(FieldDailyBudget, vc))
}

// DailyBudgetHasSuffix applies the HasSuffix predicate on the "daily_budget" field.
func DailyBudgetHasSuffix(v decimal.Decimal) predicate.ProviderHallConfig {
	vc := v.String()
	return predicate.ProviderHallConfig(sql.FieldHasSuffix(FieldDailyBudget, vc))
}

// DailyBudgetEqualFold applies the EqualFold predicate on the "daily_budget" field.
func DailyBudgetEqualFold(v decimal.Decimal) predicate.ProviderHallConfig {
	vc := v.String()
	return predicate.ProviderHallConfig(sql.FieldEqualFold(FieldDailyBudget, vc))
}

// DailyBudgetContainsFold applies the ContainsFold predicate on the "daily_budget" field.
func DailyBudgetContainsFold(v decimal.Decimal) predicate.ProviderHallConfig {
	vc := v.String()
	return predicate.ProviderHallConfig(sql.FieldContainsFold(FieldDailyBudget, vc))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLTE(FieldVersion, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderHallConfig) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderHallConfig) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderHallConfig) predicate.ProviderHallConfig {
	return predicate.ProviderHallConfig(sql.NotPredicates(p))
}
