// Code generated by ent, DO NOT EDIT.

package providerhallprobekey

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the providerhallprobekey type in the database.
	Label = "provider_hall_probe_key"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "api_key_id"
	// FieldOperatorUserID holds the string denoting the operator_user_id field in the database.
	FieldOperatorUserID = "operator_user_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldRegisteredBy holds the string denoting the registered_by field in the database.
	FieldRegisteredBy = "registered_by"
	// FieldRegisteredAt holds the string denoting the registered_at field in the database.
	FieldRegisteredAt = "registered_at"
	// Table holds the table name of the providerhallprobekey in the database.
	Table = "provider_hall_probe_keys"
)

// Columns holds all SQL columns for providerhallprobekey fields.
var Columns = []string{
	FieldID,
	FieldOperatorUserID,
	FieldGroupID,
	FieldRegisteredBy,
	FieldRegisteredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OperatorUserIDValidator is a validator for the "operator_user_id" field. It is called by the builders before save.
	OperatorUserIDValidator func(int64) error
	// GroupIDValidator is a validator for the "group_id" field. It is called by the builders before save.
	GroupIDValidator func(int64) error
	// RegisteredByValidator is a validator for the "registered_by" field. It is called by the builders before save.
	RegisteredByValidator func(int64) error
	// DefaultRegisteredAt holds the default value on creation for the "registered_at" field.
	DefaultRegisteredAt func() time.Time
)

// OrderOption defines the ordering options for the ProviderHallProbeKey queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOperatorUserID orders the results by the operator_user_id field.
func ByOperatorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorUserID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByRegisteredBy orders the results by the registered_by field.
func ByRegisteredBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegisteredBy, opts...).ToFunc()
}

// ByRegisteredAt orders the results by the registered_at field.
func ByRegisteredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegisteredAt, opts...).ToFunc()
}
