// Code generated by ent, DO NOT EDIT.

package providerhallprobekey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldLTE(FieldID, id))
}

// OperatorUserID applies equality check predicate on the "operator_user_id" field. It's identical to OperatorUserIDEQ.
func OperatorUserID(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldEQ(FieldOperatorUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldEQ(FieldGroupID, v))
}

// RegisteredBy applies equality check predicate on the "registered_by" field. It's identical to RegisteredByEQ.
func RegisteredBy(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldEQ(FieldRegisteredBy, v))
}

// RegisteredAt applies equality check predicate on the "registered_at" field. It's identical to RegisteredAtEQ.
func RegisteredAt(v time.Time) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldEQ(FieldRegisteredAt, v))
}

// OperatorUserIDEQ applies the EQ predicate on the "operator_user_id" field.
func OperatorUserIDEQ(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldEQ(FieldOperatorUserID, v))
}

// OperatorUserIDNEQ applies the NEQ predicate on the "operator_user_id" field.
func OperatorUserIDNEQ(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldNEQ(FieldOperatorUserID, v))
}

// OperatorUserIDIn applies the In predicate on the "operator_user_id" field.
func OperatorUserIDIn(vs ...int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDNotIn applies the NotIn predicate on the "operator_user_id" field.
func OperatorUserIDNotIn(vs ...int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldNotIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDGT applies the GT predicate on the "operator_user_id" field.
func OperatorUserIDGT(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldGT(FieldOperatorUserID, v))
}

// OperatorUserIDGTE applies the GTE predicate on the "operator_user_id" field.
func OperatorUserIDGTE(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldGTE(FieldOperatorUserID, v))
}

// OperatorUserIDLT applies the LT predicate on the "operator_user_id" field.
func OperatorUserIDLT(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldLT(FieldOperatorUserID, v))
}

// OperatorUserIDLTE applies the LTE predicate on the "operator_user_id" field.
func OperatorUserIDLTE(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldLTE(FieldOperatorUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldLTE(FieldGroupID, v))
}

// RegisteredByEQ applies the EQ predicate on the "registered_by" field.
func RegisteredByEQ(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldEQ(FieldRegisteredBy, v))
}

// RegisteredByNEQ applies the NEQ predicate on the "registered_by" field.
func RegisteredByNEQ(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldNEQ(FieldRegisteredBy, v))
}

// RegisteredByIn applies the In predicate on the "registered_by" field.
func RegisteredByIn(vs ...int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldIn(FieldRegisteredBy, vs...))
}

// RegisteredByNotIn applies the NotIn predicate on the "registered_by" field.
func RegisteredByNotIn(vs ...int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldNotIn(FieldRegisteredBy, vs...))
}

// RegisteredByGT applies the GT predicate on the "registered_by" field.
func RegisteredByGT(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldGT(FieldRegisteredBy, v))
}

// RegisteredByGTE applies the GTE predicate on the "registered_by" field.
func RegisteredByGTE(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldGTE(FieldRegisteredBy, v))
}

// RegisteredByLT applies the LT predicate on the "registered_by" field.
func RegisteredByLT(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldLT(FieldRegisteredBy, v))
}

// RegisteredByLTE applies the LTE predicate on the "registered_by" field.
func RegisteredByLTE(v int64) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldLTE(FieldRegisteredBy, v))
}

// RegisteredAtEQ applies the EQ predicate on the "registered_at" field.
func RegisteredAtEQ(v time.Time) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldEQ(FieldRegisteredAt, v))
}

// RegisteredAtNEQ applies the NEQ predicate on the "registered_at" field.
func RegisteredAtNEQ(v time.Time) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldNEQ(FieldRegisteredAt, v))
}

// RegisteredAtIn applies the In predicate on the "registered_at" field.
func RegisteredAtIn(vs ...time.Time) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldIn(FieldRegisteredAt, vs...))
}

// RegisteredAtNotIn applies the NotIn predicate on the "registered_at" field.
func RegisteredAtNotIn(vs ...time.Time) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldNotIn(FieldRegisteredAt, vs...))
}

// RegisteredAtGT applies the GT predicate on the "registered_at" field.
func RegisteredAtGT(v time.Time) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldGT(FieldRegisteredAt, v))
}

// RegisteredAtGTE applies the GTE predicate on the "registered_at" field.
func RegisteredAtGTE(v time.Time) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldGTE(FieldRegisteredAt, v))
}

// RegisteredAtLT applies the LT predicate on the "registered_at" field.
func RegisteredAtLT(v time.Time) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldLT(FieldRegisteredAt, v))
}

// RegisteredAtLTE applies the LTE predicate on the "registered_at" field.
func RegisteredAtLTE(v time.Time) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.FieldLTE(FieldRegisteredAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderHallProbeKey) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderHallProbeKey) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderHallProbeKey) predicate.ProviderHallProbeKey {
	return predicate.ProviderHallProbeKey(sql.NotPredicates(p))
}
