// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/providerhallprofile"
	"github.com/shopspring/decimal"
)

// ProviderHallProfileCreate is the builder for creating a ProviderHallProfile entity.
type ProviderHallProfileCreate struct {
	config
	mutation *ProviderHallProfileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetModel sets the "model" field.
func (_c *ProviderHallProfileCreate) SetModel(v string) *ProviderHallProfileCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetProtocol sets the "protocol" field.
func (_c *ProviderHallProfileCreate) SetProtocol(v providerhallprofile.Protocol) *ProviderHallProfileCreate {
	_c.mutation.SetProtocol(v)
	return _c
}

// SetSupportsTools sets the "supports_tools" field.
func (_c *ProviderHallProfileCreate) SetSupportsTools(v bool) *ProviderHallProfileCreate {
	_c.mutation.SetSupportsTools(v)
	return _c
}

// SetNillableSupportsTools sets the "supports_tools" field if the given value is not nil.
func (_c *ProviderHallProfileCreate) SetNillableSupportsTools(v *bool) *ProviderHallProfileCreate {
	if v != nil {
		_c.SetSupportsTools(*v)
	}
	return _c
}

// SetOutputLimit sets the "output_limit" field.
func (_c *ProviderHallProfileCreate) SetOutputLimit(v int) *ProviderHallProfileCreate {
	_c.mutation.SetOutputLimit(v)
	return _c
}

// SetNillableOutputLimit sets the "output_limit" field if the given value is not nil.
func (_c *ProviderHallProfileCreate) SetNillableOutputLimit(v *int) *ProviderHallProfileCreate {
	if v != nil {
		_c.SetOutputLimit(*v)
	}
	return _c
}

// SetModelAliases sets the "model_aliases" field.
func (_c *ProviderHallProfileCreate) SetModelAliases(v []string) *ProviderHallProfileCreate {
	_c.mutation.SetModelAliases(v)
	return _c
}

// SetReferenceInputPrice sets the "reference_input_price" field.
func (_c *ProviderHallProfileCreate) SetReferenceInputPrice(v decimal.Decimal) *ProviderHallProfileCreate {
	_c.mutation.SetReferenceInputPrice(v)
	return _c
}

// SetNillableReferenceInputPrice sets the "reference_input_price" field if the given value is not nil.
func (_c *ProviderHallProfileCreate) SetNillableReferenceInputPrice(v *decimal.Decimal) *ProviderHallProfileCreate {
	if v != nil {
		_c.SetReferenceInputPrice(*v)
	}
	return _c
}

// SetReferenceCachePrice sets the "reference_cache_price" field.
func (_c *ProviderHallProfileCreate) SetReferenceCachePrice(v decimal.Decimal) *ProviderHallProfileCreate {
	_c.mutation.SetReferenceCachePrice(v)
	return _c
}

// SetNillableReferenceCachePrice sets the "reference_cache_price" field if the given value is not nil.
func (_c *ProviderHallProfileCreate) SetNillableReferenceCachePrice(v *decimal.Decimal) *ProviderHallProfileCreate {
	if v != nil {
		_c.SetReferenceCachePrice(*v)
	}
	return _c
}

// SetReferenceCacheRate sets the "reference_cache_rate" field.
func (_c *ProviderHallProfileCreate) SetReferenceCacheRate(v decimal.Decimal) *ProviderHallProfileCreate {
	_c.mutation.SetReferenceCacheRate(v)
	return _c
}

// SetNillableReferenceCacheRate sets the "reference_cache_rate" field if the given value is not nil.
func (_c *ProviderHallProfileCreate) SetNillableReferenceCacheRate(v *decimal.Decimal) *ProviderHallProfileCreate {
	if v != nil {
		_c.SetReferenceCacheRate(*v)
	}
	return _c
}

// SetReferenceConfirmedAt sets the "reference_confirmed_at" field.
func (_c *ProviderHallProfileCreate) SetReferenceConfirmedAt(v time.Time) *ProviderHallProfileCreate {
	_c.mutation.SetReferenceConfirmedAt(v)
	return _c
}

// SetNillableReferenceConfirmedAt sets the "reference_confirmed_at" field if the given value is not nil.
func (_c *ProviderHallProfileCreate) SetNillableReferenceConfirmedAt(v *time.Time) *ProviderHallProfileCreate {
	if v != nil {
		_c.SetReferenceConfirmedAt(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ProviderHallProfileCreate) SetVersion(v int64) *ProviderHallProfileCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ProviderHallProfileCreate) SetNillableVersion(v *int64) *ProviderHallProfileCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ProviderHallProfileCreate) SetUpdatedBy(v int64) *ProviderHallProfileCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ProviderHallProfileCreate) SetNillableUpdatedBy(v *int64) *ProviderHallProfileCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProviderHallProfileCreate) SetUpdatedAt(v time.Time) *ProviderHallProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProviderHallProfileCreate) SetNillableUpdatedAt(v *time.Time) *ProviderHallProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ProviderHallProfileMutation object of the builder.
func (_c *ProviderHallProfileCreate) Mutation() *ProviderHallProfileMutation {
	return _c.mutation
}

// Save creates the ProviderHallProfile in the database.
func (_c *ProviderHallProfileCreate) Save(ctx context.Context) (*ProviderHallProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderHallProfileCreate) SaveX(ctx context.Context) *ProviderHallProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderHallProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderHallProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProviderHallProfileCreate) defaults() {
	if _, ok := _c.mutation.SupportsTools(); !ok {
		v := providerhallprofile.DefaultSupportsTools
		_c.mutation.SetSupportsTools(v)
	}
	if _, ok := _c.mutation.OutputLimit(); !ok {
		v := providerhallprofile.DefaultOutputLimit
		_c.mutation.SetOutputLimit(v)
	}
	if _, ok := _c.mutation.ModelAliases(); !ok {
		v := providerhallprofile.DefaultModelAliases
		_c.mutation.SetModelAliases(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := providerhallprofile.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := providerhallprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderHallProfileCreate) check() error {
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "ProviderHallProfile.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := providerhallprofile.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProfile.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		return &ValidationError{Name: "protocol", err: errors.New(`ent: missing required field "ProviderHallProfile.protocol"`)}
	}
	if v, ok := _c.mutation.Protocol(); ok {
		if err := providerhallprofile.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProfile.protocol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SupportsTools(); !ok {
		return &ValidationError{Name: "supports_tools", err: errors.New(`ent: missing required field "ProviderHallProfile.supports_tools"`)}
	}
	if _, ok := _c.mutation.OutputLimit(); !ok {
		return &ValidationError{Name: "output_limit", err: errors.New(`ent: missing required field "ProviderHallProfile.output_limit"`)}
	}
	if v, ok := _c.mutation.OutputLimit(); ok {
		if err := providerhallprofile.OutputLimitValidator(v); err != nil {
			return &ValidationError{Name: "output_limit", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProfile.output_limit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelAliases(); !ok {
		return &ValidationError{Name: "model_aliases", err: errors.New(`ent: missing required field "ProviderHallProfile.model_aliases"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ProviderHallProfile.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := providerhallprofile.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProfile.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProviderHallProfile.updated_at"`)}
	}
	return nil
}

func (_c *ProviderHallProfileCreate) sqlSave(ctx context.Context) (*ProviderHallProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProviderHallProfileCreate) createSpec() (*ProviderHallProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderHallProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(providerhallprofile.Table, sqlgraph.NewFieldSpec(providerhallprofile.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(providerhallprofile.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Protocol(); ok {
		_spec.SetField(providerhallprofile.FieldProtocol, field.TypeEnum, value)
		_node.Protocol = value
	}
	if value, ok := _c.mutation.SupportsTools(); ok {
		_spec.SetField(providerhallprofile.FieldSupportsTools, field.TypeBool, value)
		_node.SupportsTools = value
	}
	if value, ok := _c.mutation.OutputLimit(); ok {
		_spec.SetField(providerhallprofile.FieldOutputLimit, field.TypeInt, value)
		_node.OutputLimit = value
	}
	if value, ok := _c.mutation.ModelAliases(); ok {
		_spec.SetField(providerhallprofile.FieldModelAliases, field.TypeJSON, value)
		_node.ModelAliases = value
	}
	if value, ok := _c.mutation.ReferenceInputPrice(); ok {
		_spec.SetField(providerhallprofile.FieldReferenceInputPrice, field.TypeString, value)
		_node.ReferenceInputPrice = &value
	}
	if value, ok := _c.mutation.ReferenceCachePrice(); ok {
		_spec.SetField(providerhallprofile.FieldReferenceCachePrice, field.TypeString, value)
		_node.ReferenceCachePrice = &value
	}
	if value, ok := _c.mutation.ReferenceCacheRate(); ok {
		_spec.SetField(providerhallprofile.FieldReferenceCacheRate, field.TypeString, value)
		_node.ReferenceCacheRate = &value
	}
	if value, ok := _c.mutation.ReferenceConfirmedAt(); ok {
		_spec.SetField(providerhallprofile.FieldReferenceConfirmedAt, field.TypeTime, value)
		_node.ReferenceConfirmedAt = &value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(providerhallprofile.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(providerhallprofile.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(providerhallprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderHallProfile.Create().
//		SetModel(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderHallProfileUpsert) {
//			SetModel(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderHallProfileCreate) OnConflict(opts ...sql.ConflictOption) *ProviderHallProfileUpsertOne {
	_c.conflict = opts
	return &ProviderHallProfileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderHallProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderHallProfileCreate) OnConflictColumns(columns ...string) *ProviderHallProfileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderHallProfileUpsertOne{
		create: _c,
	}
}

type (
	// ProviderHallProfileUpsertOne is the builder for "upsert"-ing
	//  one ProviderHallProfile node.
	ProviderHallProfileUpsertOne struct {
		create *ProviderHallProfileCreate
	}

	// ProviderHallProfileUpsert is the "OnConflict" setter.
	ProviderHallProfileUpsert struct {
		*sql.UpdateSet
	}
)

// SetModel sets the "model" field.
func (u *ProviderHallProfileUpsert) SetModel(v string) *ProviderHallProfileUpsert {
	u.Set(providerhallprofile.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ProviderHallProfileUpsert) UpdateModel() *ProviderHallProfileUpsert {
	u.SetExcluded(providerhallprofile.FieldModel)
	return u
}

// SetProtocol sets the "protocol" field.
func (u *ProviderHallProfileUpsert) SetProtocol(v providerhallprofile.Protocol) *ProviderHallProfileUpsert {
	u.Set(providerhallprofile.FieldProtocol, v)
	return u
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ProviderHallProfileUpsert) UpdateProtocol() *ProviderHallProfileUpsert {
	u.SetExcluded(providerhallprofile.FieldProtocol)
	return u
}

// SetSupportsTools sets the "supports_tools" field.
func (u *ProviderHallProfileUpsert) SetSupportsTools(v bool) *ProviderHallProfileUpsert {
	u.Set(providerhallprofile.FieldSupportsTools, v)
	return u
}

// UpdateSupportsTools sets the "supports_tools" field to the value that was provided on create.
func (u *ProviderHallProfileUpsert) UpdateSupportsTools() *ProviderHallProfileUpsert {
	u.SetExcluded(providerhallprofile.FieldSupportsTools)
	return u
}

// SetOutputLimit sets the "output_limit" field.
func (u *ProviderHallProfileUpsert) SetOutputLimit(v int) *ProviderHallProfileUpsert {
	u.Set(providerhallprofile.FieldOutputLimit, v)
	return u
}

// UpdateOutputLimit sets the "output_limit" field to the value that was provided on create.
func (u *ProviderHallProfileUpsert) UpdateOutputLimit() *ProviderHallProfileUpsert {
	u.SetExcluded(providerhallprofile.FieldOutputLimit)
	return u
}

// AddOutputLimit adds v to the "output_limit" field.
func (u *ProviderHallProfileUpsert) AddOutputLimit(v int) *ProviderHallProfileUpsert {
	u.Add(providerhallprofile.FieldOutputLimit, v)
	return u
}

// SetModelAliases sets the "model_aliases" field.
func (u *ProviderHallProfileUpsert) SetModelAliases(v []string) *ProviderHallProfileUpsert {
	u.Set(providerhallprofile.FieldModelAliases, v)
	return u
}

// UpdateModelAliases sets the "model_aliases" field to the value that was provided on create.
func (u *ProviderHallProfileUpsert) UpdateModelAliases() *ProviderHallProfileUpsert {
	u.SetExcluded(providerhallprofile.FieldModelAliases)
	return u
}

// SetReferenceInputPrice sets the "reference_input_price" field.
func (u *ProviderHallProfileUpsert) SetReferenceInputPrice(v decimal.Decimal) *ProviderHallProfileUpsert {
	u.Set(providerhallprofile.FieldReferenceInputPrice, v)
	return u
}

// UpdateReferenceInputPrice sets the "reference_input_price" field to the value that was provided on create.
func (u *ProviderHallProfileUpsert) UpdateReferenceInputPrice() *ProviderHallProfileUpsert {
	u.SetExcluded(providerhallprofile.FieldReferenceInputPrice)
	return u
}

// ClearReferenceInputPrice clears the value of the "reference_input_price" field.
func (u *ProviderHallProfileUpsert) ClearReferenceInputPrice() *ProviderHallProfileUpsert {
	u.SetNull(providerhallprofile.FieldReferenceInputPrice)
	return u
}

// SetReferenceCachePrice sets the "reference_cache_price" field.
func (u *ProviderHallProfileUpsert) SetReferenceCachePrice(v decimal.Decimal) *ProviderHallProfileUpsert {
	u.Set(providerhallprofile.FieldReferenceCachePrice, v)
	return u
}

// UpdateReferenceCachePrice sets the "reference_cache_price" field to the value that was provided on create.
func (u *ProviderHallProfileUpsert) UpdateReferenceCachePrice() *ProviderHallProfileUpsert {
	u.SetExcluded(providerhallprofile.FieldReferenceCachePrice)
	return u
}

// ClearReferenceCachePrice clears the value of the "reference_cache_price" field.
func (u *ProviderHallProfileUpsert) ClearReferenceCachePrice() *ProviderHallProfileUpsert {
	u.SetNull(providerhallprofile.FieldReferenceCachePrice)
	return u
}

// SetReferenceCacheRate sets the "reference_cache_rate" field.
func (u *ProviderHallProfileUpsert) SetReferenceCacheRate(v decimal.Decimal) *ProviderHallProfileUpsert {
	u.Set(providerhallprofile.FieldReferenceCacheRate, v)
	return u
}

// UpdateReferenceCacheRate sets the "reference_cache_rate" field to the value that was provided on create.
func (u *ProviderHallProfileUpsert) UpdateReferenceCacheRate() *ProviderHallProfileUpsert {
	u.SetExcluded(providerhallprofile.FieldReferenceCacheRate)
	return u
}

// ClearReferenceCacheRate clears the value of the "reference_cache_rate" field.
func (u *ProviderHallProfileUpsert) ClearReferenceCacheRate() *ProviderHallProfileUpsert {
	u.SetNull(providerhallprofile.FieldReferenceCacheRate)
	return u
}

// SetReferenceConfirmedAt sets the "reference_confirmed_at" field.
func (u *ProviderHallProfileUpsert) SetReferenceConfirmedAt(v time.Time) *ProviderHallProfileUpsert {
	u.Set(providerhallprofile.FieldReferenceConfirmedAt, v)
	return u
}

// UpdateReferenceConfirmedAt sets the "reference_confirmed_at" field to the value that was provided on create.
func (u *ProviderHallProfileUpsert) UpdateReferenceConfirmedAt() *ProviderHallProfileUpsert {
	u.SetExcluded(providerhallprofile.FieldReferenceConfirmedAt)
	return u
}

// ClearReferenceConfirmedAt clears the value of the "reference_confirmed_at" field.
func (u *ProviderHallProfileUpsert) ClearReferenceConfirmedAt() *ProviderHallProfileUpsert {
	u.SetNull(providerhallprofile.FieldReferenceConfirmedAt)
	return u
}

// SetVersion sets the "version" field.
func (u *ProviderHallProfileUpsert) SetVersion(v int64) *ProviderHallProfileUpsert {
	u.Set(providerhallprofile.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderHallProfileUpsert) UpdateVersion() *ProviderHallProfileUpsert {
	u.SetExcluded(providerhallprofile.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *ProviderHallProfileUpsert) AddVersion(v int64) *ProviderHallProfileUpsert {
	u.Add(providerhallprofile.FieldVersion, v)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProviderHallProfileUpsert) SetUpdatedBy(v int64) *ProviderHallProfileUpsert {
	u.Set(providerhallprofile.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProviderHallProfileUpsert) UpdateUpdatedBy() *ProviderHallProfileUpsert {
	u.SetExcluded(providerhallprofile.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ProviderHallProfileUpsert) AddUpdatedBy(v int64) *ProviderHallProfileUpsert {
	u.Add(providerhallprofile.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProviderHallProfileUpsert) ClearUpdatedBy() *ProviderHallProfileUpsert {
	u.SetNull(providerhallprofile.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderHallProfileUpsert) SetUpdatedAt(v time.Time) *ProviderHallProfileUpsert {
	u.Set(providerhallprofile.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderHallProfileUpsert) UpdateUpdatedAt() *ProviderHallProfileUpsert {
	u.SetExcluded(providerhallprofile.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProviderHallProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderHallProfileUpsertOne) UpdateNewValues() *ProviderHallProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderHallProfile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProviderHallProfileUpsertOne) Ignore() *ProviderHallProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderHallProfileUpsertOne) DoNothing() *ProviderHallProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderHallProfileCreate.OnConflict
// documentation for more info.
func (u *ProviderHallProfileUpsertOne) Update(set func(*ProviderHallProfileUpsert)) *ProviderHallProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderHallProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetModel sets the "model" field.
func (u *ProviderHallProfileUpsertOne) SetModel(v string) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertOne) UpdateModel() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateModel()
	})
}

// SetProtocol sets the "protocol" field.
func (u *ProviderHallProfileUpsertOne) SetProtocol(v providerhallprofile.Protocol) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertOne) UpdateProtocol() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateProtocol()
	})
}

// SetSupportsTools sets the "supports_tools" field.
func (u *ProviderHallProfileUpsertOne) SetSupportsTools(v bool) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetSupportsTools(v)
	})
}

// UpdateSupportsTools sets the "supports_tools" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertOne) UpdateSupportsTools() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateSupportsTools()
	})
}

// SetOutputLimit sets the "output_limit" field.
func (u *ProviderHallProfileUpsertOne) SetOutputLimit(v int) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetOutputLimit(v)
	})
}

// AddOutputLimit adds v to the "output_limit" field.
func (u *ProviderHallProfileUpsertOne) AddOutputLimit(v int) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.AddOutputLimit(v)
	})
}

// UpdateOutputLimit sets the "output_limit" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertOne) UpdateOutputLimit() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateOutputLimit()
	})
}

// SetModelAliases sets the "model_aliases" field.
func (u *ProviderHallProfileUpsertOne) SetModelAliases(v []string) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetModelAliases(v)
	})
}

// UpdateModelAliases sets the "model_aliases" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertOne) UpdateModelAliases() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateModelAliases()
	})
}

// SetReferenceInputPrice sets the "reference_input_price" field.
func (u *ProviderHallProfileUpsertOne) SetReferenceInputPrice(v decimal.Decimal) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetReferenceInputPrice(v)
	})
}

// UpdateReferenceInputPrice sets the "reference_input_price" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertOne) UpdateReferenceInputPrice() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateReferenceInputPrice()
	})
}

// ClearReferenceInputPrice clears the value of the "reference_input_price" field.
func (u *ProviderHallProfileUpsertOne) ClearReferenceInputPrice() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.ClearReferenceInputPrice()
	})
}

// SetReferenceCachePrice sets the "reference_cache_price" field.
func (u *ProviderHallProfileUpsertOne) SetReferenceCachePrice(v decimal.Decimal) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetReferenceCachePrice(v)
	})
}

// UpdateReferenceCachePrice sets the "reference_cache_price" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertOne) UpdateReferenceCachePrice() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateReferenceCachePrice()
	})
}

// ClearReferenceCachePrice clears the value of the "reference_cache_price" field.
func (u *ProviderHallProfileUpsertOne) ClearReferenceCachePrice() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.ClearReferenceCachePrice()
	})
}

// SetReferenceCacheRate sets the "reference_cache_rate" field.
func (u *ProviderHallProfileUpsertOne) SetReferenceCacheRate(v decimal.Decimal) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetReferenceCacheRate(v)
	})
}

// UpdateReferenceCacheRate sets the "reference_cache_rate" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertOne) UpdateReferenceCacheRate() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateReferenceCacheRate()
	})
}

// ClearReferenceCacheRate clears the value of the "reference_cache_rate" field.
func (u *ProviderHallProfileUpsertOne) ClearReferenceCacheRate() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.ClearReferenceCacheRate()
	})
}

// SetReferenceConfirmedAt sets the "reference_confirmed_at" field.
func (u *ProviderHallProfileUpsertOne) SetReferenceConfirmedAt(v time.Time) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetReferenceConfirmedAt(v)
	})
}

// UpdateReferenceConfirmedAt sets the "reference_confirmed_at" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertOne) UpdateReferenceConfirmedAt() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateReferenceConfirmedAt()
	})
}

// ClearReferenceConfirmedAt clears the value of the "reference_confirmed_at" field.
func (u *ProviderHallProfileUpsertOne) ClearReferenceConfirmedAt() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.ClearReferenceConfirmedAt()
	})
}

// SetVersion sets the "version" field.
func (u *ProviderHallProfileUpsertOne) SetVersion(v int64) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ProviderHallProfileUpsertOne) AddVersion(v int64) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertOne) UpdateVersion() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProviderHallProfileUpsertOne) SetUpdatedBy(v int64) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ProviderHallProfileUpsertOne) AddUpdatedBy(v int64) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertOne) UpdateUpdatedBy() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProviderHallProfileUpsertOne) ClearUpdatedBy() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderHallProfileUpsertOne) SetUpdatedAt(v time.Time) *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertOne) UpdateUpdatedAt() *ProviderHallProfileUpsertOne {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProviderHallProfileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderHallProfileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderHallProfileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProviderHallProfileUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProviderHallProfileUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProviderHallProfileCreateBulk is the builder for creating many ProviderHallProfile entities in bulk.
type ProviderHallProfileCreateBulk struct {
	config
	err      error
	builders []*ProviderHallProfileCreate
	conflict []sql.ConflictOption
}

// Save creates the ProviderHallProfile entities in the database.
func (_c *ProviderHallProfileCreateBulk) Save(ctx context.Context) ([]*ProviderHallProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProviderHallProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderHallProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderHallProfileCreateBulk) SaveX(ctx context.Context) []*ProviderHallProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderHallProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderHallProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderHallProfile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderHallProfileUpsert) {
//			SetModel(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderHallProfileCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProviderHallProfileUpsertBulk {
	_c.conflict = opts
	return &ProviderHallProfileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderHallProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderHallProfileCreateBulk) OnConflictColumns(columns ...string) *ProviderHallProfileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderHallProfileUpsertBulk{
		create: _c,
	}
}

// ProviderHallProfileUpsertBulk is the builder for "upsert"-ing
// a bulk of ProviderHallProfile nodes.
type ProviderHallProfileUpsertBulk struct {
	create *ProviderHallProfileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProviderHallProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderHallProfileUpsertBulk) UpdateNewValues() *ProviderHallProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderHallProfile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProviderHallProfileUpsertBulk) Ignore() *ProviderHallProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderHallProfileUpsertBulk) DoNothing() *ProviderHallProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderHallProfileCreateBulk.OnConflict
// documentation for more info.
func (u *ProviderHallProfileUpsertBulk) Update(set func(*ProviderHallProfileUpsert)) *ProviderHallProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderHallProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetModel sets the "model" field.
func (u *ProviderHallProfileUpsertBulk) SetModel(v string) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertBulk) UpdateModel() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateModel()
	})
}

// SetProtocol sets the "protocol" field.
func (u *ProviderHallProfileUpsertBulk) SetProtocol(v providerhallprofile.Protocol) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertBulk) UpdateProtocol() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateProtocol()
	})
}

// SetSupportsTools sets the "supports_tools" field.
func (u *ProviderHallProfileUpsertBulk) SetSupportsTools(v bool) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetSupportsTools(v)
	})
}

// UpdateSupportsTools sets the "supports_tools" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertBulk) UpdateSupportsTools() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateSupportsTools()
	})
}

// SetOutputLimit sets the "output_limit" field.
func (u *ProviderHallProfileUpsertBulk) SetOutputLimit(v int) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetOutputLimit(v)
	})
}

// AddOutputLimit adds v to the "output_limit" field.
func (u *ProviderHallProfileUpsertBulk) AddOutputLimit(v int) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.AddOutputLimit(v)
	})
}

// UpdateOutputLimit sets the "output_limit" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertBulk) UpdateOutputLimit() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateOutputLimit()
	})
}

// SetModelAliases sets the "model_aliases" field.
func (u *ProviderHallProfileUpsertBulk) SetModelAliases(v []string) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetModelAliases(v)
	})
}

// UpdateModelAliases sets the "model_aliases" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertBulk) UpdateModelAliases() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateModelAliases()
	})
}

// SetReferenceInputPrice sets the "reference_input_price" field.
func (u *ProviderHallProfileUpsertBulk) SetReferenceInputPrice(v decimal.Decimal) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetReferenceInputPrice(v)
	})
}

// UpdateReferenceInputPrice sets the "reference_input_price" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertBulk) UpdateReferenceInputPrice() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateReferenceInputPrice()
	})
}

// ClearReferenceInputPrice clears the value of the "reference_input_price" field.
func (u *ProviderHallProfileUpsertBulk) ClearReferenceInputPrice() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.ClearReferenceInputPrice()
	})
}

// SetReferenceCachePrice sets the "reference_cache_price" field.
func (u *ProviderHallProfileUpsertBulk) SetReferenceCachePrice(v decimal.Decimal) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetReferenceCachePrice(v)
	})
}

// UpdateReferenceCachePrice sets the "reference_cache_price" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertBulk) UpdateReferenceCachePrice() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateReferenceCachePrice()
	})
}

// ClearReferenceCachePrice clears the value of the "reference_cache_price" field.
func (u *ProviderHallProfileUpsertBulk) ClearReferenceCachePrice() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.ClearReferenceCachePrice()
	})
}

// SetReferenceCacheRate sets the "reference_cache_rate" field.
func (u *ProviderHallProfileUpsertBulk) SetReferenceCacheRate(v decimal.Decimal) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetReferenceCacheRate(v)
	})
}

// UpdateReferenceCacheRate sets the "reference_cache_rate" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertBulk) UpdateReferenceCacheRate() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateReferenceCacheRate()
	})
}

// ClearReferenceCacheRate clears the value of the "reference_cache_rate" field.
func (u *ProviderHallProfileUpsertBulk) ClearReferenceCacheRate() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.ClearReferenceCacheRate()
	})
}

// SetReferenceConfirmedAt sets the "reference_confirmed_at" field.
func (u *ProviderHallProfileUpsertBulk) SetReferenceConfirmedAt(v time.Time) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetReferenceConfirmedAt(v)
	})
}

// UpdateReferenceConfirmedAt sets the "reference_confirmed_at" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertBulk) UpdateReferenceConfirmedAt() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateReferenceConfirmedAt()
	})
}

// ClearReferenceConfirmedAt clears the value of the "reference_confirmed_at" field.
func (u *ProviderHallProfileUpsertBulk) ClearReferenceConfirmedAt() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.ClearReferenceConfirmedAt()
	})
}

// SetVersion sets the "version" field.
func (u *ProviderHallProfileUpsertBulk) SetVersion(v int64) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ProviderHallProfileUpsertBulk) AddVersion(v int64) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertBulk) UpdateVersion() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProviderHallProfileUpsertBulk) SetUpdatedBy(v int64) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ProviderHallProfileUpsertBulk) AddUpdatedBy(v int64) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertBulk) UpdateUpdatedBy() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProviderHallProfileUpsertBulk) ClearUpdatedBy() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderHallProfileUpsertBulk) SetUpdatedAt(v time.Time) *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderHallProfileUpsertBulk) UpdateUpdatedAt() *ProviderHallProfileUpsertBulk {
	return u.Update(func(s *ProviderHallProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProviderHallProfileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProviderHallProfileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderHallProfileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderHallProfileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
