// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/providerhallprobekey"
)

// ProviderHallProbeKeyCreate is the builder for creating a ProviderHallProbeKey entity.
type ProviderHallProbeKeyCreate struct {
	config
	mutation *ProviderHallProbeKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_c *ProviderHallProbeKeyCreate) SetOperatorUserID(v int64) *ProviderHallProbeKeyCreate {
	_c.mutation.SetOperatorUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ProviderHallProbeKeyCreate) SetGroupID(v int64) *ProviderHallProbeKeyCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetRegisteredBy sets the "registered_by" field.
func (_c *ProviderHallProbeKeyCreate) SetRegisteredBy(v int64) *ProviderHallProbeKeyCreate {
	_c.mutation.SetRegisteredBy(v)
	return _c
}

// SetRegisteredAt sets the "registered_at" field.
func (_c *ProviderHallProbeKeyCreate) SetRegisteredAt(v time.Time) *ProviderHallProbeKeyCreate {
	_c.mutation.SetRegisteredAt(v)
	return _c
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (_c *ProviderHallProbeKeyCreate) SetNillableRegisteredAt(v *time.Time) *ProviderHallProbeKeyCreate {
	if v != nil {
		_c.SetRegisteredAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProviderHallProbeKeyCreate) SetID(v int64) *ProviderHallProbeKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProviderHallProbeKeyMutation object of the builder.
func (_c *ProviderHallProbeKeyCreate) Mutation() *ProviderHallProbeKeyMutation {
	return _c.mutation
}

// Save creates the ProviderHallProbeKey in the database.
func (_c *ProviderHallProbeKeyCreate) Save(ctx context.Context) (*ProviderHallProbeKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderHallProbeKeyCreate) SaveX(ctx context.Context) *ProviderHallProbeKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderHallProbeKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderHallProbeKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProviderHallProbeKeyCreate) defaults() {
	if _, ok := _c.mutation.RegisteredAt(); !ok {
		v := providerhallprobekey.DefaultRegisteredAt()
		_c.mutation.SetRegisteredAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderHallProbeKeyCreate) check() error {
	if _, ok := _c.mutation.OperatorUserID(); !ok {
		return &ValidationError{Name: "operator_user_id", err: errors.New(`ent: missing required field "ProviderHallProbeKey.operator_user_id"`)}
	}
	if v, ok := _c.mutation.OperatorUserID(); ok {
		if err := providerhallprobekey.OperatorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "operator_user_id", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProbeKey.operator_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "ProviderHallProbeKey.group_id"`)}
	}
	if v, ok := _c.mutation.GroupID(); ok {
		if err := providerhallprobekey.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProbeKey.group_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RegisteredBy(); !ok {
		return &ValidationError{Name: "registered_by", err: errors.New(`ent: missing required field "ProviderHallProbeKey.registered_by"`)}
	}
	if v, ok := _c.mutation.RegisteredBy(); ok {
		if err := providerhallprobekey.RegisteredByValidator(v); err != nil {
			return &ValidationError{Name: "registered_by", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProbeKey.registered_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RegisteredAt(); !ok {
		return &ValidationError{Name: "registered_at", err: errors.New(`ent: missing required field "ProviderHallProbeKey.registered_at"`)}
	}
	return nil
}

func (_c *ProviderHallProbeKeyCreate) sqlSave(ctx context.Context) (*ProviderHallProbeKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProviderHallProbeKeyCreate) createSpec() (*ProviderHallProbeKey, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderHallProbeKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(providerhallprobekey.Table, sqlgraph.NewFieldSpec(providerhallprobekey.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OperatorUserID(); ok {
		_spec.SetField(providerhallprobekey.FieldOperatorUserID, field.TypeInt64, value)
		_node.OperatorUserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(providerhallprobekey.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.RegisteredBy(); ok {
		_spec.SetField(providerhallprobekey.FieldRegisteredBy, field.TypeInt64, value)
		_node.RegisteredBy = value
	}
	if value, ok := _c.mutation.RegisteredAt(); ok {
		_spec.SetField(providerhallprobekey.FieldRegisteredAt, field.TypeTime, value)
		_node.RegisteredAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderHallProbeKey.Create().
//		SetOperatorUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderHallProbeKeyUpsert) {
//			SetOperatorUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderHallProbeKeyCreate) OnConflict(opts ...sql.ConflictOption) *ProviderHallProbeKeyUpsertOne {
	_c.conflict = opts
	return &ProviderHallProbeKeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderHallProbeKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderHallProbeKeyCreate) OnConflictColumns(columns ...string) *ProviderHallProbeKeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderHallProbeKeyUpsertOne{
		create: _c,
	}
}

type (
	// ProviderHallProbeKeyUpsertOne is the builder for "upsert"-ing
	//  one ProviderHallProbeKey node.
	ProviderHallProbeKeyUpsertOne struct {
		create *ProviderHallProbeKeyCreate
	}

	// ProviderHallProbeKeyUpsert is the "OnConflict" setter.
	ProviderHallProbeKeyUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ProviderHallProbeKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(providerhallprobekey.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProviderHallProbeKeyUpsertOne) UpdateNewValues() *ProviderHallProbeKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(providerhallprobekey.FieldID)
		}
		if _, exists := u.create.mutation.OperatorUserID(); exists {
			s.SetIgnore(providerhallprobekey.FieldOperatorUserID)
		}
		if _, exists := u.create.mutation.GroupID(); exists {
			s.SetIgnore(providerhallprobekey.FieldGroupID)
		}
		if _, exists := u.create.mutation.RegisteredBy(); exists {
			s.SetIgnore(providerhallprobekey.FieldRegisteredBy)
		}
		if _, exists := u.create.mutation.RegisteredAt(); exists {
			s.SetIgnore(providerhallprobekey.FieldRegisteredAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderHallProbeKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProviderHallProbeKeyUpsertOne) Ignore() *ProviderHallProbeKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderHallProbeKeyUpsertOne) DoNothing() *ProviderHallProbeKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderHallProbeKeyCreate.OnConflict
// documentation for more info.
func (u *ProviderHallProbeKeyUpsertOne) Update(set func(*ProviderHallProbeKeyUpsert)) *ProviderHallProbeKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderHallProbeKeyUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ProviderHallProbeKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderHallProbeKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderHallProbeKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProviderHallProbeKeyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProviderHallProbeKeyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProviderHallProbeKeyCreateBulk is the builder for creating many ProviderHallProbeKey entities in bulk.
type ProviderHallProbeKeyCreateBulk struct {
	config
	err      error
	builders []*ProviderHallProbeKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the ProviderHallProbeKey entities in the database.
func (_c *ProviderHallProbeKeyCreateBulk) Save(ctx context.Context) ([]*ProviderHallProbeKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProviderHallProbeKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderHallProbeKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderHallProbeKeyCreateBulk) SaveX(ctx context.Context) []*ProviderHallProbeKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderHallProbeKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderHallProbeKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderHallProbeKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderHallProbeKeyUpsert) {
//			SetOperatorUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderHallProbeKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProviderHallProbeKeyUpsertBulk {
	_c.conflict = opts
	return &ProviderHallProbeKeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderHallProbeKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderHallProbeKeyCreateBulk) OnConflictColumns(columns ...string) *ProviderHallProbeKeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderHallProbeKeyUpsertBulk{
		create: _c,
	}
}

// ProviderHallProbeKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of ProviderHallProbeKey nodes.
type ProviderHallProbeKeyUpsertBulk struct {
	create *ProviderHallProbeKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProviderHallProbeKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(providerhallprobekey.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProviderHallProbeKeyUpsertBulk) UpdateNewValues() *ProviderHallProbeKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(providerhallprobekey.FieldID)
			}
			if _, exists := b.mutation.OperatorUserID(); exists {
				s.SetIgnore(providerhallprobekey.FieldOperatorUserID)
			}
			if _, exists := b.mutation.GroupID(); exists {
				s.SetIgnore(providerhallprobekey.FieldGroupID)
			}
			if _, exists := b.mutation.RegisteredBy(); exists {
				s.SetIgnore(providerhallprobekey.FieldRegisteredBy)
			}
			if _, exists := b.mutation.RegisteredAt(); exists {
				s.SetIgnore(providerhallprobekey.FieldRegisteredAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderHallProbeKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProviderHallProbeKeyUpsertBulk) Ignore() *ProviderHallProbeKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderHallProbeKeyUpsertBulk) DoNothing() *ProviderHallProbeKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderHallProbeKeyCreateBulk.OnConflict
// documentation for more info.
func (u *ProviderHallProbeKeyUpsertBulk) Update(set func(*ProviderHallProbeKeyUpsert)) *ProviderHallProbeKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderHallProbeKeyUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ProviderHallProbeKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProviderHallProbeKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderHallProbeKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderHallProbeKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
