// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/providerhallgroup"
)

// ProviderHallGroupCreate is the builder for creating a ProviderHallGroup entity.
type ProviderHallGroupCreate struct {
	config
	mutation *ProviderHallGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetListed sets the "listed" field.
func (_c *ProviderHallGroupCreate) SetListed(v bool) *ProviderHallGroupCreate {
	_c.mutation.SetListed(v)
	return _c
}

// SetNillableListed sets the "listed" field if the given value is not nil.
func (_c *ProviderHallGroupCreate) SetNillableListed(v *bool) *ProviderHallGroupCreate {
	if v != nil {
		_c.SetListed(*v)
	}
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *ProviderHallGroupCreate) SetDisplayName(v string) *ProviderHallGroupCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *ProviderHallGroupCreate) SetNillableDisplayName(v *string) *ProviderHallGroupCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ProviderHallGroupCreate) SetDescription(v string) *ProviderHallGroupCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ProviderHallGroupCreate) SetNillableDescription(v *string) *ProviderHallGroupCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetDisplayOrder sets the "display_order" field.
func (_c *ProviderHallGroupCreate) SetDisplayOrder(v int) *ProviderHallGroupCreate {
	_c.mutation.SetDisplayOrder(v)
	return _c
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_c *ProviderHallGroupCreate) SetNillableDisplayOrder(v *int) *ProviderHallGroupCreate {
	if v != nil {
		_c.SetDisplayOrder(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ProviderHallGroupCreate) SetVersion(v int64) *ProviderHallGroupCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ProviderHallGroupCreate) SetNillableVersion(v *int64) *ProviderHallGroupCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ProviderHallGroupCreate) SetUpdatedBy(v int64) *ProviderHallGroupCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ProviderHallGroupCreate) SetNillableUpdatedBy(v *int64) *ProviderHallGroupCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProviderHallGroupCreate) SetUpdatedAt(v time.Time) *ProviderHallGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProviderHallGroupCreate) SetNillableUpdatedAt(v *time.Time) *ProviderHallGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProviderHallGroupCreate) SetID(v int64) *ProviderHallGroupCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProviderHallGroupMutation object of the builder.
func (_c *ProviderHallGroupCreate) Mutation() *ProviderHallGroupMutation {
	return _c.mutation
}

// Save creates the ProviderHallGroup in the database.
func (_c *ProviderHallGroupCreate) Save(ctx context.Context) (*ProviderHallGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderHallGroupCreate) SaveX(ctx context.Context) *ProviderHallGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderHallGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderHallGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProviderHallGroupCreate) defaults() {
	if _, ok := _c.mutation.Listed(); !ok {
		v := providerhallgroup.DefaultListed
		_c.mutation.SetListed(v)
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := providerhallgroup.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := providerhallgroup.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		v := providerhallgroup.DefaultDisplayOrder
		_c.mutation.SetDisplayOrder(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := providerhallgroup.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := providerhallgroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderHallGroupCreate) check() error {
	if _, ok := _c.mutation.Listed(); !ok {
		return &ValidationError{Name: "listed", err: errors.New(`ent: missing required field "ProviderHallGroup.listed"`)}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "ProviderHallGroup.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := providerhallgroup.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ProviderHallGroup.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ProviderHallGroup.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := providerhallgroup.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ProviderHallGroup.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`ent: missing required field "ProviderHallGroup.display_order"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ProviderHallGroup.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := providerhallgroup.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderHallGroup.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProviderHallGroup.updated_at"`)}
	}
	return nil
}

func (_c *ProviderHallGroupCreate) sqlSave(ctx context.Context) (*ProviderHallGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProviderHallGroupCreate) createSpec() (*ProviderHallGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderHallGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(providerhallgroup.Table, sqlgraph.NewFieldSpec(providerhallgroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Listed(); ok {
		_spec.SetField(providerhallgroup.FieldListed, field.TypeBool, value)
		_node.Listed = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(providerhallgroup.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(providerhallgroup.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.DisplayOrder(); ok {
		_spec.SetField(providerhallgroup.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(providerhallgroup.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(providerhallgroup.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(providerhallgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderHallGroup.Create().
//		SetListed(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderHallGroupUpsert) {
//			SetListed(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderHallGroupCreate) OnConflict(opts ...sql.ConflictOption) *ProviderHallGroupUpsertOne {
	_c.conflict = opts
	return &ProviderHallGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderHallGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderHallGroupCreate) OnConflictColumns(columns ...string) *ProviderHallGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderHallGroupUpsertOne{
		create: _c,
	}
}

type (
	// ProviderHallGroupUpsertOne is the builder for "upsert"-ing
	//  one ProviderHallGroup node.
	ProviderHallGroupUpsertOne struct {
		create *ProviderHallGroupCreate
	}

	// ProviderHallGroupUpsert is the "OnConflict" setter.
	ProviderHallGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetListed sets the "listed" field.
func (u *ProviderHallGroupUpsert) SetListed(v bool) *ProviderHallGroupUpsert {
	u.Set(providerhallgroup.FieldListed, v)
	return u
}

// UpdateListed sets the "listed" field to the value that was provided on create.
func (u *ProviderHallGroupUpsert) UpdateListed() *ProviderHallGroupUpsert {
	u.SetExcluded(providerhallgroup.FieldListed)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *ProviderHallGroupUpsert) SetDisplayName(v string) *ProviderHallGroupUpsert {
	u.Set(providerhallgroup.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ProviderHallGroupUpsert) UpdateDisplayName() *ProviderHallGroupUpsert {
	u.SetExcluded(providerhallgroup.FieldDisplayName)
	return u
}

// SetDescription sets the "description" field.
func (u *ProviderHallGroupUpsert) SetDescription(v string) *ProviderHallGroupUpsert {
	u.Set(providerhallgroup.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ProviderHallGroupUpsert) UpdateDescription() *ProviderHallGroupUpsert {
	u.SetExcluded(providerhallgroup.FieldDescription)
	return u
}

// SetDisplayOrder sets the "display_order" field.
func (u *ProviderHallGroupUpsert) SetDisplayOrder(v int) *ProviderHallGroupUpsert {
	u.Set(providerhallgroup.FieldDisplayOrder, v)
	return u
}

// UpdateDisplayOrder sets the "display_order" field to the value that was provided on create.
func (u *ProviderHallGroupUpsert) UpdateDisplayOrder() *ProviderHallGroupUpsert {
	u.SetExcluded(providerhallgroup.FieldDisplayOrder)
	return u
}

// AddDisplayOrder adds v to the "display_order" field.
func (u *ProviderHallGroupUpsert) AddDisplayOrder(v int) *ProviderHallGroupUpsert {
	u.Add(providerhallgroup.FieldDisplayOrder, v)
	return u
}

// SetVersion sets the "version" field.
func (u *ProviderHallGroupUpsert) SetVersion(v int64) *ProviderHallGroupUpsert {
	u.Set(providerhallgroup.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderHallGroupUpsert) UpdateVersion() *ProviderHallGroupUpsert {
	u.SetExcluded(providerhallgroup.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *ProviderHallGroupUpsert) AddVersion(v int64) *ProviderHallGroupUpsert {
	u.Add(providerhallgroup.FieldVersion, v)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProviderHallGroupUpsert) SetUpdatedBy(v int64) *ProviderHallGroupUpsert {
	u.Set(providerhallgroup.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProviderHallGroupUpsert) UpdateUpdatedBy() *ProviderHallGroupUpsert {
	u.SetExcluded(providerhallgroup.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ProviderHallGroupUpsert) AddUpdatedBy(v int64) *ProviderHallGroupUpsert {
	u.Add(providerhallgroup.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProviderHallGroupUpsert) ClearUpdatedBy() *ProviderHallGroupUpsert {
	u.SetNull(providerhallgroup.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderHallGroupUpsert) SetUpdatedAt(v time.Time) *ProviderHallGroupUpsert {
	u.Set(providerhallgroup.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderHallGroupUpsert) UpdateUpdatedAt() *ProviderHallGroupUpsert {
	u.SetExcluded(providerhallgroup.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ProviderHallGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(providerhallgroup.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProviderHallGroupUpsertOne) UpdateNewValues() *ProviderHallGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(providerhallgroup.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderHallGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProviderHallGroupUpsertOne) Ignore() *ProviderHallGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderHallGroupUpsertOne) DoNothing() *ProviderHallGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderHallGroupCreate.OnConflict
// documentation for more info.
func (u *ProviderHallGroupUpsertOne) Update(set func(*ProviderHallGroupUpsert)) *ProviderHallGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderHallGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetListed sets the "listed" field.
func (u *ProviderHallGroupUpsertOne) SetListed(v bool) *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetListed(v)
	})
}

// UpdateListed sets the "listed" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertOne) UpdateListed() *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateListed()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *ProviderHallGroupUpsertOne) SetDisplayName(v string) *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertOne) UpdateDisplayName() *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateDisplayName()
	})
}

// SetDescription sets the "description" field.
func (u *ProviderHallGroupUpsertOne) SetDescription(v string) *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertOne) UpdateDescription() *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateDescription()
	})
}

// SetDisplayOrder sets the "display_order" field.
func (u *ProviderHallGroupUpsertOne) SetDisplayOrder(v int) *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetDisplayOrder(v)
	})
}

// AddDisplayOrder adds v to the "display_order" field.
func (u *ProviderHallGroupUpsertOne) AddDisplayOrder(v int) *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.AddDisplayOrder(v)
	})
}

// UpdateDisplayOrder sets the "display_order" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertOne) UpdateDisplayOrder() *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateDisplayOrder()
	})
}

// SetVersion sets the "version" field.
func (u *ProviderHallGroupUpsertOne) SetVersion(v int64) *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ProviderHallGroupUpsertOne) AddVersion(v int64) *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertOne) UpdateVersion() *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProviderHallGroupUpsertOne) SetUpdatedBy(v int64) *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ProviderHallGroupUpsertOne) AddUpdatedBy(v int64) *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertOne) UpdateUpdatedBy() *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProviderHallGroupUpsertOne) ClearUpdatedBy() *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderHallGroupUpsertOne) SetUpdatedAt(v time.Time) *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertOne) UpdateUpdatedAt() *ProviderHallGroupUpsertOne {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProviderHallGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderHallGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderHallGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProviderHallGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProviderHallGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProviderHallGroupCreateBulk is the builder for creating many ProviderHallGroup entities in bulk.
type ProviderHallGroupCreateBulk struct {
	config
	err      error
	builders []*ProviderHallGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the ProviderHallGroup entities in the database.
func (_c *ProviderHallGroupCreateBulk) Save(ctx context.Context) ([]*ProviderHallGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProviderHallGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderHallGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderHallGroupCreateBulk) SaveX(ctx context.Context) []*ProviderHallGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderHallGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderHallGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderHallGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderHallGroupUpsert) {
//			SetListed(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderHallGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProviderHallGroupUpsertBulk {
	_c.conflict = opts
	return &ProviderHallGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderHallGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderHallGroupCreateBulk) OnConflictColumns(columns ...string) *ProviderHallGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderHallGroupUpsertBulk{
		create: _c,
	}
}

// ProviderHallGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of ProviderHallGroup nodes.
type ProviderHallGroupUpsertBulk struct {
	create *ProviderHallGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProviderHallGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(providerhallgroup.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProviderHallGroupUpsertBulk) UpdateNewValues() *ProviderHallGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(providerhallgroup.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderHallGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProviderHallGroupUpsertBulk) Ignore() *ProviderHallGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderHallGroupUpsertBulk) DoNothing() *ProviderHallGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderHallGroupCreateBulk.OnConflict
// documentation for more info.
func (u *ProviderHallGroupUpsertBulk) Update(set func(*ProviderHallGroupUpsert)) *ProviderHallGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderHallGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetListed sets the "listed" field.
func (u *ProviderHallGroupUpsertBulk) SetListed(v bool) *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetListed(v)
	})
}

// UpdateListed sets the "listed" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertBulk) UpdateListed() *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateListed()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *ProviderHallGroupUpsertBulk) SetDisplayName(v string) *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertBulk) UpdateDisplayName() *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateDisplayName()
	})
}

// SetDescription sets the "description" field.
func (u *ProviderHallGroupUpsertBulk) SetDescription(v string) *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertBulk) UpdateDescription() *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateDescription()
	})
}

// SetDisplayOrder sets the "display_order" field.
func (u *ProviderHallGroupUpsertBulk) SetDisplayOrder(v int) *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetDisplayOrder(v)
	})
}

// AddDisplayOrder adds v to the "display_order" field.
func (u *ProviderHallGroupUpsertBulk) AddDisplayOrder(v int) *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.AddDisplayOrder(v)
	})
}

// UpdateDisplayOrder sets the "display_order" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertBulk) UpdateDisplayOrder() *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateDisplayOrder()
	})
}

// SetVersion sets the "version" field.
func (u *ProviderHallGroupUpsertBulk) SetVersion(v int64) *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ProviderHallGroupUpsertBulk) AddVersion(v int64) *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertBulk) UpdateVersion() *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProviderHallGroupUpsertBulk) SetUpdatedBy(v int64) *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ProviderHallGroupUpsertBulk) AddUpdatedBy(v int64) *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertBulk) UpdateUpdatedBy() *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProviderHallGroupUpsertBulk) ClearUpdatedBy() *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderHallGroupUpsertBulk) SetUpdatedAt(v time.Time) *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderHallGroupUpsertBulk) UpdateUpdatedAt() *ProviderHallGroupUpsertBulk {
	return u.Update(func(s *ProviderHallGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProviderHallGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProviderHallGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderHallGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderHallGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
