// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/providerhallprofile"
	"github.com/shopspring/decimal"
)

// ProviderHallProfile is the model entity for the ProviderHallProfile schema.
type ProviderHallProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol providerhallprofile.Protocol `json:"protocol,omitempty"`
	// SupportsTools holds the value of the "supports_tools" field.
	SupportsTools bool `json:"supports_tools,omitempty"`
	// OutputLimit holds the value of the "output_limit" field.
	OutputLimit int `json:"output_limit,omitempty"`
	// ModelAliases holds the value of the "model_aliases" field.
	ModelAliases []string `json:"model_aliases,omitempty"`
	// ReferenceInputPrice holds the value of the "reference_input_price" field.
	ReferenceInputPrice *decimal.Decimal `json:"reference_input_price,omitempty"`
	// ReferenceCachePrice holds the value of the "reference_cache_price" field.
	ReferenceCachePrice *decimal.Decimal `json:"reference_cache_price,omitempty"`
	// ReferenceCacheRate holds the value of the "reference_cache_rate" field.
	ReferenceCacheRate *decimal.Decimal `json:"reference_cache_rate,omitempty"`
	// ReferenceConfirmedAt holds the value of the "reference_confirmed_at" field.
	ReferenceConfirmedAt *time.Time `json:"reference_confirmed_at,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy *int64 `json:"updated_by,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderHallProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providerhallprofile.FieldReferenceInputPrice, providerhallprofile.FieldReferenceCachePrice, providerhallprofile.FieldReferenceCacheRate:
			values[i] = &sql.NullScanner{S: new(decimal.Decimal)}
		case providerhallprofile.FieldModelAliases:
			values[i] = new([]byte)
		case providerhallprofile.FieldSupportsTools:
			values[i] = new(sql.NullBool)
		case providerhallprofile.FieldID, providerhallprofile.FieldOutputLimit, providerhallprofile.FieldVersion, providerhallprofile.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case providerhallprofile.FieldModel, providerhallprofile.FieldProtocol:
			values[i] = new(sql.NullString)
		case providerhallprofile.FieldReferenceConfirmedAt, providerhallprofile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderHallProfile fields.
func (_m *ProviderHallProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providerhallprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case providerhallprofile.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case providerhallprofile.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = providerhallprofile.Protocol(value.String)
			}
		case providerhallprofile.FieldSupportsTools:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field supports_tools", values[i])
			} else if value.Valid {
				_m.SupportsTools = value.Bool
			}
		case providerhallprofile.FieldOutputLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_limit", values[i])
			} else if value.Valid {
				_m.OutputLimit = int(value.Int64)
			}
		case providerhallprofile.FieldModelAliases:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field model_aliases", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ModelAliases); err != nil {
					return fmt.Errorf("unmarshal field model_aliases: %w", err)
				}
			}
		case providerhallprofile.FieldReferenceInputPrice:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field reference_input_price", values[i])
			} else if value.Valid {
				_m.ReferenceInputPrice = new(decimal.Decimal)
				*_m.ReferenceInputPrice = *value.S.(*decimal.Decimal)
			}
		case providerhallprofile.FieldReferenceCachePrice:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field reference_cache_price", values[i])
			} else if value.Valid {
				_m.ReferenceCachePrice = new(decimal.Decimal)
				*_m.ReferenceCachePrice = *value.S.(*decimal.Decimal)
			}
		case providerhallprofile.FieldReferenceCacheRate:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field reference_cache_rate", values[i])
			} else if value.Valid {
				_m.ReferenceCacheRate = new(decimal.Decimal)
				*_m.ReferenceCacheRate = *value.S.(*decimal.Decimal)
			}
		case providerhallprofile.FieldReferenceConfirmedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reference_confirmed_at", values[i])
			} else if value.Valid {
				_m.ReferenceConfirmedAt = new(time.Time)
				*_m.ReferenceConfirmedAt = value.Time
			}
		case providerhallprofile.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case providerhallprofile.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(int64)
				*_m.UpdatedBy = value.Int64
			}
		case providerhallprofile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderHallProfile.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderHallProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProviderHallProfile.
// Note that you need to call ProviderHallProfile.Unwrap() before calling this method if this ProviderHallProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderHallProfile) Update() *ProviderHallProfileUpdateOne {
	return NewProviderHallProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderHallProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderHallProfile) Unwrap() *ProviderHallProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderHallProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderHallProfile) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderHallProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(fmt.Sprintf("%v", _m.Protocol))
	builder.WriteString(", ")
	builder.WriteString("supports_tools=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupportsTools))
	builder.WriteString(", ")
	builder.WriteString("output_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputLimit))
	builder.WriteString(", ")
	builder.WriteString("model_aliases=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelAliases))
	builder.WriteString(", ")
	if v := _m.ReferenceInputPrice; v != nil {
		builder.WriteString("reference_input_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReferenceCachePrice; v != nil {
		builder.WriteString("reference_cache_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReferenceCacheRate; v != nil {
		builder.WriteString("reference_cache_rate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReferenceConfirmedAt; v != nil {
		builder.WriteString("reference_confirmed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderHallProfiles is a parsable slice of ProviderHallProfile.
type ProviderHallProfiles []*ProviderHallProfile
