// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/providerhallgroup"
)

// ProviderHallGroupUpdate is the builder for updating ProviderHallGroup entities.
type ProviderHallGroupUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderHallGroupMutation
}

// Where appends a list predicates to the ProviderHallGroupUpdate builder.
func (_u *ProviderHallGroupUpdate) Where(ps ...predicate.ProviderHallGroup) *ProviderHallGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetListed sets the "listed" field.
func (_u *ProviderHallGroupUpdate) SetListed(v bool) *ProviderHallGroupUpdate {
	_u.mutation.SetListed(v)
	return _u
}

// SetNillableListed sets the "listed" field if the given value is not nil.
func (_u *ProviderHallGroupUpdate) SetNillableListed(v *bool) *ProviderHallGroupUpdate {
	if v != nil {
		_u.SetListed(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ProviderHallGroupUpdate) SetDisplayName(v string) *ProviderHallGroupUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ProviderHallGroupUpdate) SetNillableDisplayName(v *string) *ProviderHallGroupUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProviderHallGroupUpdate) SetDescription(v string) *ProviderHallGroupUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProviderHallGroupUpdate) SetNillableDescription(v *string) *ProviderHallGroupUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *ProviderHallGroupUpdate) SetDisplayOrder(v int) *ProviderHallGroupUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *ProviderHallGroupUpdate) SetNillableDisplayOrder(v *int) *ProviderHallGroupUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *ProviderHallGroupUpdate) AddDisplayOrder(v int) *ProviderHallGroupUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProviderHallGroupUpdate) SetVersion(v int64) *ProviderHallGroupUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProviderHallGroupUpdate) SetNillableVersion(v *int64) *ProviderHallGroupUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ProviderHallGroupUpdate) AddVersion(v int64) *ProviderHallGroupUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProviderHallGroupUpdate) SetUpdatedBy(v int64) *ProviderHallGroupUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProviderHallGroupUpdate) SetNillableUpdatedBy(v *int64) *ProviderHallGroupUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ProviderHallGroupUpdate) AddUpdatedBy(v int64) *ProviderHallGroupUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProviderHallGroupUpdate) ClearUpdatedBy() *ProviderHallGroupUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderHallGroupUpdate) SetUpdatedAt(v time.Time) *ProviderHallGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProviderHallGroupMutation object of the builder.
func (_u *ProviderHallGroupUpdate) Mutation() *ProviderHallGroupMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderHallGroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderHallGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderHallGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderHallGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderHallGroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providerhallgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderHallGroupUpdate) check() error {
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := providerhallgroup.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ProviderHallGroup.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := providerhallgroup.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ProviderHallGroup.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := providerhallgroup.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderHallGroup.version": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderHallGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerhallgroup.Table, providerhallgroup.Columns, sqlgraph.NewFieldSpec(providerhallgroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Listed(); ok {
		_spec.SetField(providerhallgroup.FieldListed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(providerhallgroup.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(providerhallgroup.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(providerhallgroup.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(providerhallgroup.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(providerhallgroup.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(providerhallgroup.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(providerhallgroup.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(providerhallgroup.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(providerhallgroup.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerhallgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerhallgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderHallGroupUpdateOne is the builder for updating a single ProviderHallGroup entity.
type ProviderHallGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderHallGroupMutation
}

// SetListed sets the "listed" field.
func (_u *ProviderHallGroupUpdateOne) SetListed(v bool) *ProviderHallGroupUpdateOne {
	_u.mutation.SetListed(v)
	return _u
}

// SetNillableListed sets the "listed" field if the given value is not nil.
func (_u *ProviderHallGroupUpdateOne) SetNillableListed(v *bool) *ProviderHallGroupUpdateOne {
	if v != nil {
		_u.SetListed(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ProviderHallGroupUpdateOne) SetDisplayName(v string) *ProviderHallGroupUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ProviderHallGroupUpdateOne) SetNillableDisplayName(v *string) *ProviderHallGroupUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProviderHallGroupUpdateOne) SetDescription(v string) *ProviderHallGroupUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProviderHallGroupUpdateOne) SetNillableDescription(v *string) *ProviderHallGroupUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *ProviderHallGroupUpdateOne) SetDisplayOrder(v int) *ProviderHallGroupUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *ProviderHallGroupUpdateOne) SetNillableDisplayOrder(v *int) *ProviderHallGroupUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *ProviderHallGroupUpdateOne) AddDisplayOrder(v int) *ProviderHallGroupUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProviderHallGroupUpdateOne) SetVersion(v int64) *ProviderHallGroupUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProviderHallGroupUpdateOne) SetNillableVersion(v *int64) *ProviderHallGroupUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ProviderHallGroupUpdateOne) AddVersion(v int64) *ProviderHallGroupUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProviderHallGroupUpdateOne) SetUpdatedBy(v int64) *ProviderHallGroupUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProviderHallGroupUpdateOne) SetNillableUpdatedBy(v *int64) *ProviderHallGroupUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ProviderHallGroupUpdateOne) AddUpdatedBy(v int64) *ProviderHallGroupUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProviderHallGroupUpdateOne) ClearUpdatedBy() *ProviderHallGroupUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderHallGroupUpdateOne) SetUpdatedAt(v time.Time) *ProviderHallGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProviderHallGroupMutation object of the builder.
func (_u *ProviderHallGroupUpdateOne) Mutation() *ProviderHallGroupMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProviderHallGroupUpdate builder.
func (_u *ProviderHallGroupUpdateOne) Where(ps ...predicate.ProviderHallGroup) *ProviderHallGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderHallGroupUpdateOne) Select(field string, fields ...string) *ProviderHallGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderHallGroup entity.
func (_u *ProviderHallGroupUpdateOne) Save(ctx context.Context) (*ProviderHallGroup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderHallGroupUpdateOne) SaveX(ctx context.Context) *ProviderHallGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderHallGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderHallGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderHallGroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providerhallgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderHallGroupUpdateOne) check() error {
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := providerhallgroup.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ProviderHallGroup.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := providerhallgroup.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ProviderHallGroup.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := providerhallgroup.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderHallGroup.version": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderHallGroupUpdateOne) sqlSave(ctx context.Context) (_node *ProviderHallGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerhallgroup.Table, providerhallgroup.Columns, sqlgraph.NewFieldSpec(providerhallgroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderHallGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providerhallgroup.FieldID)
		for _, f := range fields {
			if !providerhallgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providerhallgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Listed(); ok {
		_spec.SetField(providerhallgroup.FieldListed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(providerhallgroup.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(providerhallgroup.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(providerhallgroup.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(providerhallgroup.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(providerhallgroup.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(providerhallgroup.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(providerhallgroup.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(providerhallgroup.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(providerhallgroup.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerhallgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ProviderHallGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerhallgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
