// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/providerhalltarget"
)

// ProviderHallTargetCreate is the builder for creating a ProviderHallTarget entity.
type ProviderHallTargetCreate struct {
	config
	mutation *ProviderHallTargetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGroupID sets the "group_id" field.
func (_c *ProviderHallTargetCreate) SetGroupID(v int64) *ProviderHallTargetCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetProfileID sets the "profile_id" field.
func (_c *ProviderHallTargetCreate) SetProfileID(v int64) *ProviderHallTargetCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetProbeKeyID sets the "probe_key_id" field.
func (_c *ProviderHallTargetCreate) SetProbeKeyID(v int64) *ProviderHallTargetCreate {
	_c.mutation.SetProbeKeyID(v)
	return _c
}

// SetNillableProbeKeyID sets the "probe_key_id" field if the given value is not nil.
func (_c *ProviderHallTargetCreate) SetNillableProbeKeyID(v *int64) *ProviderHallTargetCreate {
	if v != nil {
		_c.SetProbeKeyID(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ProviderHallTargetCreate) SetEnabled(v bool) *ProviderHallTargetCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ProviderHallTargetCreate) SetNillableEnabled(v *bool) *ProviderHallTargetCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetAutoScheduleEnabled sets the "auto_schedule_enabled" field.
func (_c *ProviderHallTargetCreate) SetAutoScheduleEnabled(v bool) *ProviderHallTargetCreate {
	_c.mutation.SetAutoScheduleEnabled(v)
	return _c
}

// SetNillableAutoScheduleEnabled sets the "auto_schedule_enabled" field if the given value is not nil.
func (_c *ProviderHallTargetCreate) SetNillableAutoScheduleEnabled(v *bool) *ProviderHallTargetCreate {
	if v != nil {
		_c.SetAutoScheduleEnabled(*v)
	}
	return _c
}

// SetProbeIntervalSeconds sets the "probe_interval_seconds" field.
func (_c *ProviderHallTargetCreate) SetProbeIntervalSeconds(v int) *ProviderHallTargetCreate {
	_c.mutation.SetProbeIntervalSeconds(v)
	return _c
}

// SetNillableProbeIntervalSeconds sets the "probe_interval_seconds" field if the given value is not nil.
func (_c *ProviderHallTargetCreate) SetNillableProbeIntervalSeconds(v *int) *ProviderHallTargetCreate {
	if v != nil {
		_c.SetProbeIntervalSeconds(*v)
	}
	return _c
}

// SetVerificationIntervalSeconds sets the "verification_interval_seconds" field.
func (_c *ProviderHallTargetCreate) SetVerificationIntervalSeconds(v int) *ProviderHallTargetCreate {
	_c.mutation.SetVerificationIntervalSeconds(v)
	return _c
}

// SetNillableVerificationIntervalSeconds sets the "verification_interval_seconds" field if the given value is not nil.
func (_c *ProviderHallTargetCreate) SetNillableVerificationIntervalSeconds(v *int) *ProviderHallTargetCreate {
	if v != nil {
		_c.SetVerificationIntervalSeconds(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ProviderHallTargetCreate) SetVersion(v int64) *ProviderHallTargetCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ProviderHallTargetCreate) SetNillableVersion(v *int64) *ProviderHallTargetCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ProviderHallTargetCreate) SetUpdatedBy(v int64) *ProviderHallTargetCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ProviderHallTargetCreate) SetNillableUpdatedBy(v *int64) *ProviderHallTargetCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProviderHallTargetCreate) SetUpdatedAt(v time.Time) *ProviderHallTargetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProviderHallTargetCreate) SetNillableUpdatedAt(v *time.Time) *ProviderHallTargetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ProviderHallTargetMutation object of the builder.
func (_c *ProviderHallTargetCreate) Mutation() *ProviderHallTargetMutation {
	return _c.mutation
}

// Save creates the ProviderHallTarget in the database.
func (_c *ProviderHallTargetCreate) Save(ctx context.Context) (*ProviderHallTarget, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderHallTargetCreate) SaveX(ctx context.Context) *ProviderHallTarget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderHallTargetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderHallTargetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProviderHallTargetCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := providerhalltarget.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.AutoScheduleEnabled(); !ok {
		v := providerhalltarget.DefaultAutoScheduleEnabled
		_c.mutation.SetAutoScheduleEnabled(v)
	}
	if _, ok := _c.mutation.ProbeIntervalSeconds(); !ok {
		v := providerhalltarget.DefaultProbeIntervalSeconds
		_c.mutation.SetProbeIntervalSeconds(v)
	}
	if _, ok := _c.mutation.VerificationIntervalSeconds(); !ok {
		v := providerhalltarget.DefaultVerificationIntervalSeconds
		_c.mutation.SetVerificationIntervalSeconds(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := providerhalltarget.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := providerhalltarget.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderHallTargetCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "ProviderHallTarget.group_id"`)}
	}
	if v, ok := _c.mutation.GroupID(); ok {
		if err := providerhalltarget.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "ProviderHallTarget.group_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProfileID(); !ok {
		return &ValidationError{Name: "profile_id", err: errors.New(`ent: missing required field "ProviderHallTarget.profile_id"`)}
	}
	if v, ok := _c.mutation.ProfileID(); ok {
		if err := providerhalltarget.ProfileIDValidator(v); err != nil {
			return &ValidationError{Name: "profile_id", err: fmt.Errorf(`ent: validator failed for field "ProviderHallTarget.profile_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProbeKeyID(); ok {
		if err := providerhalltarget.ProbeKeyIDValidator(v); err != nil {
			return &ValidationError{Name: "probe_key_id", err: fmt.Errorf(`ent: validator failed for field "ProviderHallTarget.probe_key_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ProviderHallTarget.enabled"`)}
	}
	if _, ok := _c.mutation.AutoScheduleEnabled(); !ok {
		return &ValidationError{Name: "auto_schedule_enabled", err: errors.New(`ent: missing required field "ProviderHallTarget.auto_schedule_enabled"`)}
	}
	if _, ok := _c.mutation.ProbeIntervalSeconds(); !ok {
		return &ValidationError{Name: "probe_interval_seconds", err: errors.New(`ent: missing required field "ProviderHallTarget.probe_interval_seconds"`)}
	}
	if v, ok := _c.mutation.ProbeIntervalSeconds(); ok {
		if err := providerhalltarget.ProbeIntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "probe_interval_seconds", err: fmt.Errorf(`ent: validator failed for field "ProviderHallTarget.probe_interval_seconds": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerificationIntervalSeconds(); !ok {
		return &ValidationError{Name: "verification_interval_seconds", err: errors.New(`ent: missing required field "ProviderHallTarget.verification_interval_seconds"`)}
	}
	if v, ok := _c.mutation.VerificationIntervalSeconds(); ok {
		if err := providerhalltarget.VerificationIntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "verification_interval_seconds", err: fmt.Errorf(`ent: validator failed for field "ProviderHallTarget.verification_interval_seconds": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ProviderHallTarget.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := providerhalltarget.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderHallTarget.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProviderHallTarget.updated_at"`)}
	}
	return nil
}

func (_c *ProviderHallTargetCreate) sqlSave(ctx context.Context) (*ProviderHallTarget, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProviderHallTargetCreate) createSpec() (*ProviderHallTarget, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderHallTarget{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(providerhalltarget.Table, sqlgraph.NewFieldSpec(providerhalltarget.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(providerhalltarget.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.ProfileID(); ok {
		_spec.SetField(providerhalltarget.FieldProfileID, field.TypeInt64, value)
		_node.ProfileID = value
	}
	if value, ok := _c.mutation.ProbeKeyID(); ok {
		_spec.SetField(providerhalltarget.FieldProbeKeyID, field.TypeInt64, value)
		_node.ProbeKeyID = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(providerhalltarget.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.AutoScheduleEnabled(); ok {
		_spec.SetField(providerhalltarget.FieldAutoScheduleEnabled, field.TypeBool, value)
		_node.AutoScheduleEnabled = value
	}
	if value, ok := _c.mutation.ProbeIntervalSeconds(); ok {
		_spec.SetField(providerhalltarget.FieldProbeIntervalSeconds, field.TypeInt, value)
		_node.ProbeIntervalSeconds = value
	}
	if value, ok := _c.mutation.VerificationIntervalSeconds(); ok {
		_spec.SetField(providerhalltarget.FieldVerificationIntervalSeconds, field.TypeInt, value)
		_node.VerificationIntervalSeconds = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(providerhalltarget.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(providerhalltarget.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(providerhalltarget.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderHallTarget.Create().
//		SetGroupID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderHallTargetUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderHallTargetCreate) OnConflict(opts ...sql.ConflictOption) *ProviderHallTargetUpsertOne {
	_c.conflict = opts
	return &ProviderHallTargetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderHallTarget.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderHallTargetCreate) OnConflictColumns(columns ...string) *ProviderHallTargetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderHallTargetUpsertOne{
		create: _c,
	}
}

type (
	// ProviderHallTargetUpsertOne is the builder for "upsert"-ing
	//  one ProviderHallTarget node.
	ProviderHallTargetUpsertOne struct {
		create *ProviderHallTargetCreate
	}

	// ProviderHallTargetUpsert is the "OnConflict" setter.
	ProviderHallTargetUpsert struct {
		*sql.UpdateSet
	}
)

// SetProbeKeyID sets the "probe_key_id" field.
func (u *ProviderHallTargetUpsert) SetProbeKeyID(v int64) *ProviderHallTargetUpsert {
	u.Set(providerhalltarget.FieldProbeKeyID, v)
	return u
}

// UpdateProbeKeyID sets the "probe_key_id" field to the value that was provided on create.
func (u *ProviderHallTargetUpsert) UpdateProbeKeyID() *ProviderHallTargetUpsert {
	u.SetExcluded(providerhalltarget.FieldProbeKeyID)
	return u
}

// AddProbeKeyID adds v to the "probe_key_id" field.
func (u *ProviderHallTargetUpsert) AddProbeKeyID(v int64) *ProviderHallTargetUpsert {
	u.Add(providerhalltarget.FieldProbeKeyID, v)
	return u
}

// ClearProbeKeyID clears the value of the "probe_key_id" field.
func (u *ProviderHallTargetUpsert) ClearProbeKeyID() *ProviderHallTargetUpsert {
	u.SetNull(providerhalltarget.FieldProbeKeyID)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ProviderHallTargetUpsert) SetEnabled(v bool) *ProviderHallTargetUpsert {
	u.Set(providerhalltarget.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ProviderHallTargetUpsert) UpdateEnabled() *ProviderHallTargetUpsert {
	u.SetExcluded(providerhalltarget.FieldEnabled)
	return u
}

// SetAutoScheduleEnabled sets the "auto_schedule_enabled" field.
func (u *ProviderHallTargetUpsert) SetAutoScheduleEnabled(v bool) *ProviderHallTargetUpsert {
	u.Set(providerhalltarget.FieldAutoScheduleEnabled, v)
	return u
}

// UpdateAutoScheduleEnabled sets the "auto_schedule_enabled" field to the value that was provided on create.
func (u *ProviderHallTargetUpsert) UpdateAutoScheduleEnabled() *ProviderHallTargetUpsert {
	u.SetExcluded(providerhalltarget.FieldAutoScheduleEnabled)
	return u
}

// SetProbeIntervalSeconds sets the "probe_interval_seconds" field.
func (u *ProviderHallTargetUpsert) SetProbeIntervalSeconds(v int) *ProviderHallTargetUpsert {
	u.Set(providerhalltarget.FieldProbeIntervalSeconds, v)
	return u
}

// UpdateProbeIntervalSeconds sets the "probe_interval_seconds" field to the value that was provided on create.
func (u *ProviderHallTargetUpsert) UpdateProbeIntervalSeconds() *ProviderHallTargetUpsert {
	u.SetExcluded(providerhalltarget.FieldProbeIntervalSeconds)
	return u
}

// AddProbeIntervalSeconds adds v to the "probe_interval_seconds" field.
func (u *ProviderHallTargetUpsert) AddProbeIntervalSeconds(v int) *ProviderHallTargetUpsert {
	u.Add(providerhalltarget.FieldProbeIntervalSeconds, v)
	return u
}

// SetVerificationIntervalSeconds sets the "verification_interval_seconds" field.
func (u *ProviderHallTargetUpsert) SetVerificationIntervalSeconds(v int) *ProviderHallTargetUpsert {
	u.Set(providerhalltarget.FieldVerificationIntervalSeconds, v)
	return u
}

// UpdateVerificationIntervalSeconds sets the "verification_interval_seconds" field to the value that was provided on create.
func (u *ProviderHallTargetUpsert) UpdateVerificationIntervalSeconds() *ProviderHallTargetUpsert {
	u.SetExcluded(providerhalltarget.FieldVerificationIntervalSeconds)
	return u
}

// AddVerificationIntervalSeconds adds v to the "verification_interval_seconds" field.
func (u *ProviderHallTargetUpsert) AddVerificationIntervalSeconds(v int) *ProviderHallTargetUpsert {
	u.Add(providerhalltarget.FieldVerificationIntervalSeconds, v)
	return u
}

// SetVersion sets the "version" field.
func (u *ProviderHallTargetUpsert) SetVersion(v int64) *ProviderHallTargetUpsert {
	u.Set(providerhalltarget.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderHallTargetUpsert) UpdateVersion() *ProviderHallTargetUpsert {
	u.SetExcluded(providerhalltarget.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *ProviderHallTargetUpsert) AddVersion(v int64) *ProviderHallTargetUpsert {
	u.Add(providerhalltarget.FieldVersion, v)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProviderHallTargetUpsert) SetUpdatedBy(v int64) *ProviderHallTargetUpsert {
	u.Set(providerhalltarget.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProviderHallTargetUpsert) UpdateUpdatedBy() *ProviderHallTargetUpsert {
	u.SetExcluded(providerhalltarget.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ProviderHallTargetUpsert) AddUpdatedBy(v int64) *ProviderHallTargetUpsert {
	u.Add(providerhalltarget.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProviderHallTargetUpsert) ClearUpdatedBy() *ProviderHallTargetUpsert {
	u.SetNull(providerhalltarget.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderHallTargetUpsert) SetUpdatedAt(v time.Time) *ProviderHallTargetUpsert {
	u.Set(providerhalltarget.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderHallTargetUpsert) UpdateUpdatedAt() *ProviderHallTargetUpsert {
	u.SetExcluded(providerhalltarget.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProviderHallTarget.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderHallTargetUpsertOne) UpdateNewValues() *ProviderHallTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.GroupID(); exists {
			s.SetIgnore(providerhalltarget.FieldGroupID)
		}
		if _, exists := u.create.mutation.ProfileID(); exists {
			s.SetIgnore(providerhalltarget.FieldProfileID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderHallTarget.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProviderHallTargetUpsertOne) Ignore() *ProviderHallTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderHallTargetUpsertOne) DoNothing() *ProviderHallTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderHallTargetCreate.OnConflict
// documentation for more info.
func (u *ProviderHallTargetUpsertOne) Update(set func(*ProviderHallTargetUpsert)) *ProviderHallTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderHallTargetUpsert{UpdateSet: update})
	}))
	return u
}

// SetProbeKeyID sets the "probe_key_id" field.
func (u *ProviderHallTargetUpsertOne) SetProbeKeyID(v int64) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetProbeKeyID(v)
	})
}

// AddProbeKeyID adds v to the "probe_key_id" field.
func (u *ProviderHallTargetUpsertOne) AddProbeKeyID(v int64) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.AddProbeKeyID(v)
	})
}

// UpdateProbeKeyID sets the "probe_key_id" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertOne) UpdateProbeKeyID() *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateProbeKeyID()
	})
}

// ClearProbeKeyID clears the value of the "probe_key_id" field.
func (u *ProviderHallTargetUpsertOne) ClearProbeKeyID() *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.ClearProbeKeyID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ProviderHallTargetUpsertOne) SetEnabled(v bool) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertOne) UpdateEnabled() *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateEnabled()
	})
}

// SetAutoScheduleEnabled sets the "auto_schedule_enabled" field.
func (u *ProviderHallTargetUpsertOne) SetAutoScheduleEnabled(v bool) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetAutoScheduleEnabled(v)
	})
}

// UpdateAutoScheduleEnabled sets the "auto_schedule_enabled" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertOne) UpdateAutoScheduleEnabled() *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateAutoScheduleEnabled()
	})
}

// SetProbeIntervalSeconds sets the "probe_interval_seconds" field.
func (u *ProviderHallTargetUpsertOne) SetProbeIntervalSeconds(v int) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetProbeIntervalSeconds(v)
	})
}

// AddProbeIntervalSeconds adds v to the "probe_interval_seconds" field.
func (u *ProviderHallTargetUpsertOne) AddProbeIntervalSeconds(v int) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.AddProbeIntervalSeconds(v)
	})
}

// UpdateProbeIntervalSeconds sets the "probe_interval_seconds" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertOne) UpdateProbeIntervalSeconds() *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateProbeIntervalSeconds()
	})
}

// SetVerificationIntervalSeconds sets the "verification_interval_seconds" field.
func (u *ProviderHallTargetUpsertOne) SetVerificationIntervalSeconds(v int) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetVerificationIntervalSeconds(v)
	})
}

// AddVerificationIntervalSeconds adds v to the "verification_interval_seconds" field.
func (u *ProviderHallTargetUpsertOne) AddVerificationIntervalSeconds(v int) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.AddVerificationIntervalSeconds(v)
	})
}

// UpdateVerificationIntervalSeconds sets the "verification_interval_seconds" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertOne) UpdateVerificationIntervalSeconds() *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateVerificationIntervalSeconds()
	})
}

// SetVersion sets the "version" field.
func (u *ProviderHallTargetUpsertOne) SetVersion(v int64) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ProviderHallTargetUpsertOne) AddVersion(v int64) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertOne) UpdateVersion() *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProviderHallTargetUpsertOne) SetUpdatedBy(v int64) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ProviderHallTargetUpsertOne) AddUpdatedBy(v int64) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertOne) UpdateUpdatedBy() *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProviderHallTargetUpsertOne) ClearUpdatedBy() *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderHallTargetUpsertOne) SetUpdatedAt(v time.Time) *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertOne) UpdateUpdatedAt() *ProviderHallTargetUpsertOne {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProviderHallTargetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderHallTargetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderHallTargetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProviderHallTargetUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProviderHallTargetUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProviderHallTargetCreateBulk is the builder for creating many ProviderHallTarget entities in bulk.
type ProviderHallTargetCreateBulk struct {
	config
	err      error
	builders []*ProviderHallTargetCreate
	conflict []sql.ConflictOption
}

// Save creates the ProviderHallTarget entities in the database.
func (_c *ProviderHallTargetCreateBulk) Save(ctx context.Context) ([]*ProviderHallTarget, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProviderHallTarget, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderHallTargetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderHallTargetCreateBulk) SaveX(ctx context.Context) []*ProviderHallTarget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderHallTargetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderHallTargetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderHallTarget.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderHallTargetUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderHallTargetCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProviderHallTargetUpsertBulk {
	_c.conflict = opts
	return &ProviderHallTargetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderHallTarget.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderHallTargetCreateBulk) OnConflictColumns(columns ...string) *ProviderHallTargetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderHallTargetUpsertBulk{
		create: _c,
	}
}

// ProviderHallTargetUpsertBulk is the builder for "upsert"-ing
// a bulk of ProviderHallTarget nodes.
type ProviderHallTargetUpsertBulk struct {
	create *ProviderHallTargetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProviderHallTarget.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderHallTargetUpsertBulk) UpdateNewValues() *ProviderHallTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.GroupID(); exists {
				s.SetIgnore(providerhalltarget.FieldGroupID)
			}
			if _, exists := b.mutation.ProfileID(); exists {
				s.SetIgnore(providerhalltarget.FieldProfileID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderHallTarget.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProviderHallTargetUpsertBulk) Ignore() *ProviderHallTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderHallTargetUpsertBulk) DoNothing() *ProviderHallTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderHallTargetCreateBulk.OnConflict
// documentation for more info.
func (u *ProviderHallTargetUpsertBulk) Update(set func(*ProviderHallTargetUpsert)) *ProviderHallTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderHallTargetUpsert{UpdateSet: update})
	}))
	return u
}

// SetProbeKeyID sets the "probe_key_id" field.
func (u *ProviderHallTargetUpsertBulk) SetProbeKeyID(v int64) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetProbeKeyID(v)
	})
}

// AddProbeKeyID adds v to the "probe_key_id" field.
func (u *ProviderHallTargetUpsertBulk) AddProbeKeyID(v int64) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.AddProbeKeyID(v)
	})
}

// UpdateProbeKeyID sets the "probe_key_id" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertBulk) UpdateProbeKeyID() *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateProbeKeyID()
	})
}

// ClearProbeKeyID clears the value of the "probe_key_id" field.
func (u *ProviderHallTargetUpsertBulk) ClearProbeKeyID() *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.ClearProbeKeyID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ProviderHallTargetUpsertBulk) SetEnabled(v bool) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertBulk) UpdateEnabled() *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateEnabled()
	})
}

// SetAutoScheduleEnabled sets the "auto_schedule_enabled" field.
func (u *ProviderHallTargetUpsertBulk) SetAutoScheduleEnabled(v bool) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetAutoScheduleEnabled(v)
	})
}

// UpdateAutoScheduleEnabled sets the "auto_schedule_enabled" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertBulk) UpdateAutoScheduleEnabled() *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateAutoScheduleEnabled()
	})
}

// SetProbeIntervalSeconds sets the "probe_interval_seconds" field.
func (u *ProviderHallTargetUpsertBulk) SetProbeIntervalSeconds(v int) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetProbeIntervalSeconds(v)
	})
}

// AddProbeIntervalSeconds adds v to the "probe_interval_seconds" field.
func (u *ProviderHallTargetUpsertBulk) AddProbeIntervalSeconds(v int) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.AddProbeIntervalSeconds(v)
	})
}

// UpdateProbeIntervalSeconds sets the "probe_interval_seconds" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertBulk) UpdateProbeIntervalSeconds() *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateProbeIntervalSeconds()
	})
}

// SetVerificationIntervalSeconds sets the "verification_interval_seconds" field.
func (u *ProviderHallTargetUpsertBulk) SetVerificationIntervalSeconds(v int) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetVerificationIntervalSeconds(v)
	})
}

// AddVerificationIntervalSeconds adds v to the "verification_interval_seconds" field.
func (u *ProviderHallTargetUpsertBulk) AddVerificationIntervalSeconds(v int) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.AddVerificationIntervalSeconds(v)
	})
}

// UpdateVerificationIntervalSeconds sets the "verification_interval_seconds" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertBulk) UpdateVerificationIntervalSeconds() *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateVerificationIntervalSeconds()
	})
}

// SetVersion sets the "version" field.
func (u *ProviderHallTargetUpsertBulk) SetVersion(v int64) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ProviderHallTargetUpsertBulk) AddVersion(v int64) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertBulk) UpdateVersion() *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProviderHallTargetUpsertBulk) SetUpdatedBy(v int64) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ProviderHallTargetUpsertBulk) AddUpdatedBy(v int64) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertBulk) UpdateUpdatedBy() *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProviderHallTargetUpsertBulk) ClearUpdatedBy() *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderHallTargetUpsertBulk) SetUpdatedAt(v time.Time) *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderHallTargetUpsertBulk) UpdateUpdatedAt() *ProviderHallTargetUpsertBulk {
	return u.Update(func(s *ProviderHallTargetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProviderHallTargetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProviderHallTargetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderHallTargetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderHallTargetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
