// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/providerhallconfig"
	"github.com/shopspring/decimal"
)

// ProviderHallConfig is the model entity for the ProviderHallConfig schema.
type ProviderHallConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CollectionEnabled holds the value of the "collection_enabled" field.
	CollectionEnabled bool `json:"collection_enabled,omitempty"`
	// DisplayEnabled holds the value of the "display_enabled" field.
	DisplayEnabled bool `json:"display_enabled,omitempty"`
	// TasksEnabled holds the value of the "tasks_enabled" field.
	TasksEnabled bool `json:"tasks_enabled,omitempty"`
	// DefaultModel holds the value of the "default_model" field.
	DefaultModel string `json:"default_model,omitempty"`
	// DefaultProtocol holds the value of the "default_protocol" field.
	DefaultProtocol providerhallconfig.DefaultProtocol `json:"default_protocol,omitempty"`
	// DefaultRange holds the value of the "default_range" field.
	DefaultRange providerhallconfig.DefaultRange `json:"default_range,omitempty"`
	// GatewayOrigin holds the value of the "gateway_origin" field.
	GatewayOrigin string `json:"gateway_origin,omitempty"`
	// OperatorUserID holds the value of the "operator_user_id" field.
	OperatorUserID *int64 `json:"operator_user_id,omitempty"`
	// DailyBudget holds the value of the "daily_budget" field.
	DailyBudget decimal.Decimal `json:"daily_budget,omitempty"`
	// ExpectedNodes holds the value of the "expected_nodes" field.
	ExpectedNodes []string `json:"expected_nodes,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy *int64 `json:"updated_by,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderHallConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providerhallconfig.FieldExpectedNodes:
			values[i] = new([]byte)
		case providerhallconfig.FieldDailyBudget:
			values[i] = new(decimal.Decimal)
		case providerhallconfig.FieldCollectionEnabled, providerhallconfig.FieldDisplayEnabled, providerhallconfig.FieldTasksEnabled:
			values[i] = new(sql.NullBool)
		case providerhallconfig.FieldID, providerhallconfig.FieldOperatorUserID, providerhallconfig.FieldVersion, providerhallconfig.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case providerhallconfig.FieldDefaultModel, providerhallconfig.FieldDefaultProtocol, providerhallconfig.FieldDefaultRange, providerhallconfig.FieldGatewayOrigin:
			values[i] = new(sql.NullString)
		case providerhallconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderHallConfig fields.
func (_m *ProviderHallConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providerhallconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case providerhallconfig.FieldCollectionEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field collection_enabled", values[i])
			} else if value.Valid {
				_m.CollectionEnabled = value.Bool
			}
		case providerhallconfig.FieldDisplayEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field display_enabled", values[i])
			} else if value.Valid {
				_m.DisplayEnabled = value.Bool
			}
		case providerhallconfig.FieldTasksEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field tasks_enabled", values[i])
			} else if value.Valid {
				_m.TasksEnabled = value.Bool
			}
		case providerhallconfig.FieldDefaultModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_model", values[i])
			} else if value.Valid {
				_m.DefaultModel = value.String
			}
		case providerhallconfig.FieldDefaultProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_protocol", values[i])
			} else if value.Valid {
				_m.DefaultProtocol = providerhallconfig.DefaultProtocol(value.String)
			}
		case providerhallconfig.FieldDefaultRange:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_range", values[i])
			} else if value.Valid {
				_m.DefaultRange = providerhallconfig.DefaultRange(value.String)
			}
		case providerhallconfig.FieldGatewayOrigin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_origin", values[i])
			} else if value.Valid {
				_m.GatewayOrigin = value.String
			}
		case providerhallconfig.FieldOperatorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_user_id", values[i])
			} else if value.Valid {
				_m.OperatorUserID = new(int64)
				*_m.OperatorUserID = value.Int64
			}
		case providerhallconfig.FieldDailyBudget:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field daily_budget", values[i])
			} else if value != nil {
				_m.DailyBudget = *value
			}
		case providerhallconfig.FieldExpectedNodes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field expected_nodes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExpectedNodes); err != nil {
					return fmt.Errorf("unmarshal field expected_nodes: %w", err)
				}
			}
		case providerhallconfig.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case providerhallconfig.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(int64)
				*_m.UpdatedBy = value.Int64
			}
		case providerhallconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderHallConfig.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderHallConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProviderHallConfig.
// Note that you need to call ProviderHallConfig.Unwrap() before calling this method if this ProviderHallConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderHallConfig) Update() *ProviderHallConfigUpdateOne {
	return NewProviderHallConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderHallConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderHallConfig) Unwrap() *ProviderHallConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderHallConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderHallConfig) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderHallConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("collection_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.CollectionEnabled))
	builder.WriteString(", ")
	builder.WriteString("display_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisplayEnabled))
	builder.WriteString(", ")
	builder.WriteString("tasks_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.TasksEnabled))
	builder.WriteString(", ")
	builder.WriteString("default_model=")
	builder.WriteString(_m.DefaultModel)
	builder.WriteString(", ")
	builder.WriteString("default_protocol=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultProtocol))
	builder.WriteString(", ")
	builder.WriteString("default_range=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultRange))
	builder.WriteString(", ")
	builder.WriteString("gateway_origin=")
	builder.WriteString(_m.GatewayOrigin)
	builder.WriteString(", ")
	if v := _m.OperatorUserID; v != nil {
		builder.WriteString("operator_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("daily_budget=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyBudget))
	builder.WriteString(", ")
	builder.WriteString("expected_nodes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpectedNodes))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderHallConfigs is a parsable slice of ProviderHallConfig.
type ProviderHallConfigs []*ProviderHallConfig
