// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/providerhalltarget"
)

// ProviderHallTarget is the model entity for the ProviderHallTarget schema.
type ProviderHallTarget struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// ProfileID holds the value of the "profile_id" field.
	ProfileID int64 `json:"profile_id,omitempty"`
	// ProbeKeyID holds the value of the "probe_key_id" field.
	ProbeKeyID *int64 `json:"probe_key_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// ProbeIntervalSeconds holds the value of the "probe_interval_seconds" field.
	ProbeIntervalSeconds int `json:"probe_interval_seconds,omitempty"`
	// VerificationIntervalSeconds holds the value of the "verification_interval_seconds" field.
	VerificationIntervalSeconds int `json:"verification_interval_seconds,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy *int64 `json:"updated_by,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderHallTarget) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providerhalltarget.FieldEnabled:
			values[i] = new(sql.NullBool)
		case providerhalltarget.FieldID, providerhalltarget.FieldGroupID, providerhalltarget.FieldProfileID, providerhalltarget.FieldProbeKeyID, providerhalltarget.FieldProbeIntervalSeconds, providerhalltarget.FieldVerificationIntervalSeconds, providerhalltarget.FieldVersion, providerhalltarget.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case providerhalltarget.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderHallTarget fields.
func (_m *ProviderHallTarget) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providerhalltarget.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case providerhalltarget.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case providerhalltarget.FieldProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field profile_id", values[i])
			} else if value.Valid {
				_m.ProfileID = value.Int64
			}
		case providerhalltarget.FieldProbeKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field probe_key_id", values[i])
			} else if value.Valid {
				_m.ProbeKeyID = new(int64)
				*_m.ProbeKeyID = value.Int64
			}
		case providerhalltarget.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case providerhalltarget.FieldProbeIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field probe_interval_seconds", values[i])
			} else if value.Valid {
				_m.ProbeIntervalSeconds = int(value.Int64)
			}
		case providerhalltarget.FieldVerificationIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field verification_interval_seconds", values[i])
			} else if value.Valid {
				_m.VerificationIntervalSeconds = int(value.Int64)
			}
		case providerhalltarget.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case providerhalltarget.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(int64)
				*_m.UpdatedBy = value.Int64
			}
		case providerhalltarget.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderHallTarget.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderHallTarget) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProviderHallTarget.
// Note that you need to call ProviderHallTarget.Unwrap() before calling this method if this ProviderHallTarget
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderHallTarget) Update() *ProviderHallTargetUpdateOne {
	return NewProviderHallTargetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderHallTarget entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderHallTarget) Unwrap() *ProviderHallTarget {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderHallTarget is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderHallTarget) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderHallTarget(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("profile_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProfileID))
	builder.WriteString(", ")
	if v := _m.ProbeKeyID; v != nil {
		builder.WriteString("probe_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("probe_interval_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProbeIntervalSeconds))
	builder.WriteString(", ")
	builder.WriteString("verification_interval_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.VerificationIntervalSeconds))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderHallTargets is a parsable slice of ProviderHallTarget.
type ProviderHallTargets []*ProviderHallTarget
