// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/providerhallconfig"
	"github.com/shopspring/decimal"
)

// ProviderHallConfigCreate is the builder for creating a ProviderHallConfig entity.
type ProviderHallConfigCreate struct {
	config
	mutation *ProviderHallConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCollectionEnabled sets the "collection_enabled" field.
func (_c *ProviderHallConfigCreate) SetCollectionEnabled(v bool) *ProviderHallConfigCreate {
	_c.mutation.SetCollectionEnabled(v)
	return _c
}

// SetNillableCollectionEnabled sets the "collection_enabled" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableCollectionEnabled(v *bool) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetCollectionEnabled(*v)
	}
	return _c
}

// SetDisplayEnabled sets the "display_enabled" field.
func (_c *ProviderHallConfigCreate) SetDisplayEnabled(v bool) *ProviderHallConfigCreate {
	_c.mutation.SetDisplayEnabled(v)
	return _c
}

// SetNillableDisplayEnabled sets the "display_enabled" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableDisplayEnabled(v *bool) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetDisplayEnabled(*v)
	}
	return _c
}

// SetTasksEnabled sets the "tasks_enabled" field.
func (_c *ProviderHallConfigCreate) SetTasksEnabled(v bool) *ProviderHallConfigCreate {
	_c.mutation.SetTasksEnabled(v)
	return _c
}

// SetNillableTasksEnabled sets the "tasks_enabled" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableTasksEnabled(v *bool) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetTasksEnabled(*v)
	}
	return _c
}

// SetDefaultModel sets the "default_model" field.
func (_c *ProviderHallConfigCreate) SetDefaultModel(v string) *ProviderHallConfigCreate {
	_c.mutation.SetDefaultModel(v)
	return _c
}

// SetNillableDefaultModel sets the "default_model" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableDefaultModel(v *string) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetDefaultModel(*v)
	}
	return _c
}

// SetDefaultProtocol sets the "default_protocol" field.
func (_c *ProviderHallConfigCreate) SetDefaultProtocol(v providerhallconfig.DefaultProtocol) *ProviderHallConfigCreate {
	_c.mutation.SetDefaultProtocol(v)
	return _c
}

// SetNillableDefaultProtocol sets the "default_protocol" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableDefaultProtocol(v *providerhallconfig.DefaultProtocol) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetDefaultProtocol(*v)
	}
	return _c
}

// SetDefaultRange sets the "default_range" field.
func (_c *ProviderHallConfigCreate) SetDefaultRange(v providerhallconfig.DefaultRange) *ProviderHallConfigCreate {
	_c.mutation.SetDefaultRange(v)
	return _c
}

// SetNillableDefaultRange sets the "default_range" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableDefaultRange(v *providerhallconfig.DefaultRange) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetDefaultRange(*v)
	}
	return _c
}

// SetGatewayOrigin sets the "gateway_origin" field.
func (_c *ProviderHallConfigCreate) SetGatewayOrigin(v string) *ProviderHallConfigCreate {
	_c.mutation.SetGatewayOrigin(v)
	return _c
}

// SetNillableGatewayOrigin sets the "gateway_origin" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableGatewayOrigin(v *string) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetGatewayOrigin(*v)
	}
	return _c
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_c *ProviderHallConfigCreate) SetOperatorUserID(v int64) *ProviderHallConfigCreate {
	_c.mutation.SetOperatorUserID(v)
	return _c
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableOperatorUserID(v *int64) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetOperatorUserID(*v)
	}
	return _c
}

// SetDailyBudget sets the "daily_budget" field.
func (_c *ProviderHallConfigCreate) SetDailyBudget(v decimal.Decimal) *ProviderHallConfigCreate {
	_c.mutation.SetDailyBudget(v)
	return _c
}

// SetNillableDailyBudget sets the "daily_budget" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableDailyBudget(v *decimal.Decimal) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetDailyBudget(*v)
	}
	return _c
}

// SetExpectedNodes sets the "expected_nodes" field.
func (_c *ProviderHallConfigCreate) SetExpectedNodes(v []string) *ProviderHallConfigCreate {
	_c.mutation.SetExpectedNodes(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ProviderHallConfigCreate) SetVersion(v int64) *ProviderHallConfigCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableVersion(v *int64) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ProviderHallConfigCreate) SetUpdatedBy(v int64) *ProviderHallConfigCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableUpdatedBy(v *int64) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProviderHallConfigCreate) SetUpdatedAt(v time.Time) *ProviderHallConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableUpdatedAt(v *time.Time) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProviderHallConfigCreate) SetID(v int64) *ProviderHallConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProviderHallConfigCreate) SetNillableID(v *int64) *ProviderHallConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ProviderHallConfigMutation object of the builder.
func (_c *ProviderHallConfigCreate) Mutation() *ProviderHallConfigMutation {
	return _c.mutation
}

// Save creates the ProviderHallConfig in the database.
func (_c *ProviderHallConfigCreate) Save(ctx context.Context) (*ProviderHallConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderHallConfigCreate) SaveX(ctx context.Context) *ProviderHallConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderHallConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderHallConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProviderHallConfigCreate) defaults() {
	if _, ok := _c.mutation.CollectionEnabled(); !ok {
		v := providerhallconfig.DefaultCollectionEnabled
		_c.mutation.SetCollectionEnabled(v)
	}
	if _, ok := _c.mutation.DisplayEnabled(); !ok {
		v := providerhallconfig.DefaultDisplayEnabled
		_c.mutation.SetDisplayEnabled(v)
	}
	if _, ok := _c.mutation.TasksEnabled(); !ok {
		v := providerhallconfig.DefaultTasksEnabled
		_c.mutation.SetTasksEnabled(v)
	}
	if _, ok := _c.mutation.DefaultModel(); !ok {
		v := providerhallconfig.DefaultDefaultModel
		_c.mutation.SetDefaultModel(v)
	}
	if _, ok := _c.mutation.DefaultProtocol(); !ok {
		v := providerhallconfig.DefaultDefaultProtocol
		_c.mutation.SetDefaultProtocol(v)
	}
	if _, ok := _c.mutation.DefaultRange(); !ok {
		v := providerhallconfig.DefaultDefaultRange
		_c.mutation.SetDefaultRange(v)
	}
	if _, ok := _c.mutation.GatewayOrigin(); !ok {
		v := providerhallconfig.DefaultGatewayOrigin
		_c.mutation.SetGatewayOrigin(v)
	}
	if _, ok := _c.mutation.DailyBudget(); !ok {
		v := providerhallconfig.DefaultDailyBudget()
		_c.mutation.SetDailyBudget(v)
	}
	if _, ok := _c.mutation.ExpectedNodes(); !ok {
		v := providerhallconfig.DefaultExpectedNodes
		_c.mutation.SetExpectedNodes(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := providerhallconfig.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := providerhallconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := providerhallconfig.DefaultID
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderHallConfigCreate) check() error {
	if _, ok := _c.mutation.CollectionEnabled(); !ok {
		return &ValidationError{Name: "collection_enabled", err: errors.New(`ent: missing required field "ProviderHallConfig.collection_enabled"`)}
	}
	if _, ok := _c.mutation.DisplayEnabled(); !ok {
		return &ValidationError{Name: "display_enabled", err: errors.New(`ent: missing required field "ProviderHallConfig.display_enabled"`)}
	}
	if _, ok := _c.mutation.TasksEnabled(); !ok {
		return &ValidationError{Name: "tasks_enabled", err: errors.New(`ent: missing required field "ProviderHallConfig.tasks_enabled"`)}
	}
	if _, ok := _c.mutation.DefaultModel(); !ok {
		return &ValidationError{Name: "default_model", err: errors.New(`ent: missing required field "ProviderHallConfig.default_model"`)}
	}
	if v, ok := _c.mutation.DefaultModel(); ok {
		if err := providerhallconfig.DefaultModelValidator(v); err != nil {
			return &ValidationError{Name: "default_model", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.default_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultProtocol(); !ok {
		return &ValidationError{Name: "default_protocol", err: errors.New(`ent: missing required field "ProviderHallConfig.default_protocol"`)}
	}
	if v, ok := _c.mutation.DefaultProtocol(); ok {
		if err := providerhallconfig.DefaultProtocolValidator(v); err != nil {
			return &ValidationError{Name: "default_protocol", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.default_protocol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultRange(); !ok {
		return &ValidationError{Name: "default_range", err: errors.New(`ent: missing required field "ProviderHallConfig.default_range"`)}
	}
	if v, ok := _c.mutation.DefaultRange(); ok {
		if err := providerhallconfig.DefaultRangeValidator(v); err != nil {
			return &ValidationError{Name: "default_range", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.default_range": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GatewayOrigin(); !ok {
		return &ValidationError{Name: "gateway_origin", err: errors.New(`ent: missing required field "ProviderHallConfig.gateway_origin"`)}
	}
	if v, ok := _c.mutation.GatewayOrigin(); ok {
		if err := providerhallconfig.GatewayOriginValidator(v); err != nil {
			return &ValidationError{Name: "gateway_origin", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.gateway_origin": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OperatorUserID(); ok {
		if err := providerhallconfig.OperatorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "operator_user_id", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.operator_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DailyBudget(); !ok {
		return &ValidationError{Name: "daily_budget", err: errors.New(`ent: missing required field "ProviderHallConfig.daily_budget"`)}
	}
	if _, ok := _c.mutation.ExpectedNodes(); !ok {
		return &ValidationError{Name: "expected_nodes", err: errors.New(`ent: missing required field "ProviderHallConfig.expected_nodes"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ProviderHallConfig.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := providerhallconfig.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProviderHallConfig.updated_at"`)}
	}
	return nil
}

func (_c *ProviderHallConfigCreate) sqlSave(ctx context.Context) (*ProviderHallConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProviderHallConfigCreate) createSpec() (*ProviderHallConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderHallConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(providerhallconfig.Table, sqlgraph.NewFieldSpec(providerhallconfig.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CollectionEnabled(); ok {
		_spec.SetField(providerhallconfig.FieldCollectionEnabled, field.TypeBool, value)
		_node.CollectionEnabled = value
	}
	if value, ok := _c.mutation.DisplayEnabled(); ok {
		_spec.SetField(providerhallconfig.FieldDisplayEnabled, field.TypeBool, value)
		_node.DisplayEnabled = value
	}
	if value, ok := _c.mutation.TasksEnabled(); ok {
		_spec.SetField(providerhallconfig.FieldTasksEnabled, field.TypeBool, value)
		_node.TasksEnabled = value
	}
	if value, ok := _c.mutation.DefaultModel(); ok {
		_spec.SetField(providerhallconfig.FieldDefaultModel, field.TypeString, value)
		_node.DefaultModel = value
	}
	if value, ok := _c.mutation.DefaultProtocol(); ok {
		_spec.SetField(providerhallconfig.FieldDefaultProtocol, field.TypeEnum, value)
		_node.DefaultProtocol = value
	}
	if value, ok := _c.mutation.DefaultRange(); ok {
		_spec.SetField(providerhallconfig.FieldDefaultRange, field.TypeEnum, value)
		_node.DefaultRange = value
	}
	if value, ok := _c.mutation.GatewayOrigin(); ok {
		_spec.SetField(providerhallconfig.FieldGatewayOrigin, field.TypeString, value)
		_node.GatewayOrigin = value
	}
	if value, ok := _c.mutation.OperatorUserID(); ok {
		_spec.SetField(providerhallconfig.FieldOperatorUserID, field.TypeInt64, value)
		_node.OperatorUserID = &value
	}
	if value, ok := _c.mutation.DailyBudget(); ok {
		_spec.SetField(providerhallconfig.FieldDailyBudget, field.TypeString, value)
		_node.DailyBudget = value
	}
	if value, ok := _c.mutation.ExpectedNodes(); ok {
		_spec.SetField(providerhallconfig.FieldExpectedNodes, field.TypeJSON, value)
		_node.ExpectedNodes = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(providerhallconfig.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(providerhallconfig.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(providerhallconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderHallConfig.Create().
//		SetCollectionEnabled(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderHallConfigUpsert) {
//			SetCollectionEnabled(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderHallConfigCreate) OnConflict(opts ...sql.ConflictOption) *ProviderHallConfigUpsertOne {
	_c.conflict = opts
	return &ProviderHallConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderHallConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderHallConfigCreate) OnConflictColumns(columns ...string) *ProviderHallConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderHallConfigUpsertOne{
		create: _c,
	}
}

type (
	// ProviderHallConfigUpsertOne is the builder for "upsert"-ing
	//  one ProviderHallConfig node.
	ProviderHallConfigUpsertOne struct {
		create *ProviderHallConfigCreate
	}

	// ProviderHallConfigUpsert is the "OnConflict" setter.
	ProviderHallConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetCollectionEnabled sets the "collection_enabled" field.
func (u *ProviderHallConfigUpsert) SetCollectionEnabled(v bool) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldCollectionEnabled, v)
	return u
}

// UpdateCollectionEnabled sets the "collection_enabled" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateCollectionEnabled() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldCollectionEnabled)
	return u
}

// SetDisplayEnabled sets the "display_enabled" field.
func (u *ProviderHallConfigUpsert) SetDisplayEnabled(v bool) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldDisplayEnabled, v)
	return u
}

// UpdateDisplayEnabled sets the "display_enabled" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateDisplayEnabled() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldDisplayEnabled)
	return u
}

// SetTasksEnabled sets the "tasks_enabled" field.
func (u *ProviderHallConfigUpsert) SetTasksEnabled(v bool) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldTasksEnabled, v)
	return u
}

// UpdateTasksEnabled sets the "tasks_enabled" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateTasksEnabled() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldTasksEnabled)
	return u
}

// SetDefaultModel sets the "default_model" field.
func (u *ProviderHallConfigUpsert) SetDefaultModel(v string) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldDefaultModel, v)
	return u
}

// UpdateDefaultModel sets the "default_model" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateDefaultModel() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldDefaultModel)
	return u
}

// SetDefaultProtocol sets the "default_protocol" field.
func (u *ProviderHallConfigUpsert) SetDefaultProtocol(v providerhallconfig.DefaultProtocol) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldDefaultProtocol, v)
	return u
}

// UpdateDefaultProtocol sets the "default_protocol" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateDefaultProtocol() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldDefaultProtocol)
	return u
}

// SetDefaultRange sets the "default_range" field.
func (u *ProviderHallConfigUpsert) SetDefaultRange(v providerhallconfig.DefaultRange) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldDefaultRange, v)
	return u
}

// UpdateDefaultRange sets the "default_range" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateDefaultRange() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldDefaultRange)
	return u
}

// SetGatewayOrigin sets the "gateway_origin" field.
func (u *ProviderHallConfigUpsert) SetGatewayOrigin(v string) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldGatewayOrigin, v)
	return u
}

// UpdateGatewayOrigin sets the "gateway_origin" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateGatewayOrigin() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldGatewayOrigin)
	return u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *ProviderHallConfigUpsert) SetOperatorUserID(v int64) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldOperatorUserID, v)
	return u
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateOperatorUserID() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldOperatorUserID)
	return u
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *ProviderHallConfigUpsert) AddOperatorUserID(v int64) *ProviderHallConfigUpsert {
	u.Add(providerhallconfig.FieldOperatorUserID, v)
	return u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *ProviderHallConfigUpsert) ClearOperatorUserID() *ProviderHallConfigUpsert {
	u.SetNull(providerhallconfig.FieldOperatorUserID)
	return u
}

// SetDailyBudget sets the "daily_budget" field.
func (u *ProviderHallConfigUpsert) SetDailyBudget(v decimal.Decimal) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldDailyBudget, v)
	return u
}

// UpdateDailyBudget sets the "daily_budget" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateDailyBudget() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldDailyBudget)
	return u
}

// SetExpectedNodes sets the "expected_nodes" field.
func (u *ProviderHallConfigUpsert) SetExpectedNodes(v []string) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldExpectedNodes, v)
	return u
}

// UpdateExpectedNodes sets the "expected_nodes" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateExpectedNodes() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldExpectedNodes)
	return u
}

// SetVersion sets the "version" field.
func (u *ProviderHallConfigUpsert) SetVersion(v int64) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateVersion() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *ProviderHallConfigUpsert) AddVersion(v int64) *ProviderHallConfigUpsert {
	u.Add(providerhallconfig.FieldVersion, v)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProviderHallConfigUpsert) SetUpdatedBy(v int64) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateUpdatedBy() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ProviderHallConfigUpsert) AddUpdatedBy(v int64) *ProviderHallConfigUpsert {
	u.Add(providerhallconfig.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProviderHallConfigUpsert) ClearUpdatedBy() *ProviderHallConfigUpsert {
	u.SetNull(providerhallconfig.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderHallConfigUpsert) SetUpdatedAt(v time.Time) *ProviderHallConfigUpsert {
	u.Set(providerhallconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderHallConfigUpsert) UpdateUpdatedAt() *ProviderHallConfigUpsert {
	u.SetExcluded(providerhallconfig.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ProviderHallConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(providerhallconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProviderHallConfigUpsertOne) UpdateNewValues() *ProviderHallConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(providerhallconfig.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderHallConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProviderHallConfigUpsertOne) Ignore() *ProviderHallConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderHallConfigUpsertOne) DoNothing() *ProviderHallConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderHallConfigCreate.OnConflict
// documentation for more info.
func (u *ProviderHallConfigUpsertOne) Update(set func(*ProviderHallConfigUpsert)) *ProviderHallConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderHallConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetCollectionEnabled sets the "collection_enabled" field.
func (u *ProviderHallConfigUpsertOne) SetCollectionEnabled(v bool) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetCollectionEnabled(v)
	})
}

// UpdateCollectionEnabled sets the "collection_enabled" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateCollectionEnabled() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateCollectionEnabled()
	})
}

// SetDisplayEnabled sets the "display_enabled" field.
func (u *ProviderHallConfigUpsertOne) SetDisplayEnabled(v bool) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetDisplayEnabled(v)
	})
}

// UpdateDisplayEnabled sets the "display_enabled" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateDisplayEnabled() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateDisplayEnabled()
	})
}

// SetTasksEnabled sets the "tasks_enabled" field.
func (u *ProviderHallConfigUpsertOne) SetTasksEnabled(v bool) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetTasksEnabled(v)
	})
}

// UpdateTasksEnabled sets the "tasks_enabled" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateTasksEnabled() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateTasksEnabled()
	})
}

// SetDefaultModel sets the "default_model" field.
func (u *ProviderHallConfigUpsertOne) SetDefaultModel(v string) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetDefaultModel(v)
	})
}

// UpdateDefaultModel sets the "default_model" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateDefaultModel() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateDefaultModel()
	})
}

// SetDefaultProtocol sets the "default_protocol" field.
func (u *ProviderHallConfigUpsertOne) SetDefaultProtocol(v providerhallconfig.DefaultProtocol) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetDefaultProtocol(v)
	})
}

// UpdateDefaultProtocol sets the "default_protocol" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateDefaultProtocol() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateDefaultProtocol()
	})
}

// SetDefaultRange sets the "default_range" field.
func (u *ProviderHallConfigUpsertOne) SetDefaultRange(v providerhallconfig.DefaultRange) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetDefaultRange(v)
	})
}

// UpdateDefaultRange sets the "default_range" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateDefaultRange() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateDefaultRange()
	})
}

// SetGatewayOrigin sets the "gateway_origin" field.
func (u *ProviderHallConfigUpsertOne) SetGatewayOrigin(v string) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetGatewayOrigin(v)
	})
}

// UpdateGatewayOrigin sets the "gateway_origin" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateGatewayOrigin() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateGatewayOrigin()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *ProviderHallConfigUpsertOne) SetOperatorUserID(v int64) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *ProviderHallConfigUpsertOne) AddOperatorUserID(v int64) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateOperatorUserID() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateOperatorUserID()
	})
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *ProviderHallConfigUpsertOne) ClearOperatorUserID() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.ClearOperatorUserID()
	})
}

// SetDailyBudget sets the "daily_budget" field.
func (u *ProviderHallConfigUpsertOne) SetDailyBudget(v decimal.Decimal) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetDailyBudget(v)
	})
}

// UpdateDailyBudget sets the "daily_budget" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateDailyBudget() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateDailyBudget()
	})
}

// SetExpectedNodes sets the "expected_nodes" field.
func (u *ProviderHallConfigUpsertOne) SetExpectedNodes(v []string) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetExpectedNodes(v)
	})
}

// UpdateExpectedNodes sets the "expected_nodes" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateExpectedNodes() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateExpectedNodes()
	})
}

// SetVersion sets the "version" field.
func (u *ProviderHallConfigUpsertOne) SetVersion(v int64) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ProviderHallConfigUpsertOne) AddVersion(v int64) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateVersion() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProviderHallConfigUpsertOne) SetUpdatedBy(v int64) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ProviderHallConfigUpsertOne) AddUpdatedBy(v int64) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateUpdatedBy() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProviderHallConfigUpsertOne) ClearUpdatedBy() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderHallConfigUpsertOne) SetUpdatedAt(v time.Time) *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertOne) UpdateUpdatedAt() *ProviderHallConfigUpsertOne {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProviderHallConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderHallConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderHallConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProviderHallConfigUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProviderHallConfigUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProviderHallConfigCreateBulk is the builder for creating many ProviderHallConfig entities in bulk.
type ProviderHallConfigCreateBulk struct {
	config
	err      error
	builders []*ProviderHallConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the ProviderHallConfig entities in the database.
func (_c *ProviderHallConfigCreateBulk) Save(ctx context.Context) ([]*ProviderHallConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProviderHallConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderHallConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderHallConfigCreateBulk) SaveX(ctx context.Context) []*ProviderHallConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderHallConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderHallConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderHallConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderHallConfigUpsert) {
//			SetCollectionEnabled(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderHallConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProviderHallConfigUpsertBulk {
	_c.conflict = opts
	return &ProviderHallConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderHallConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderHallConfigCreateBulk) OnConflictColumns(columns ...string) *ProviderHallConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderHallConfigUpsertBulk{
		create: _c,
	}
}

// ProviderHallConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of ProviderHallConfig nodes.
type ProviderHallConfigUpsertBulk struct {
	create *ProviderHallConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProviderHallConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(providerhallconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProviderHallConfigUpsertBulk) UpdateNewValues() *ProviderHallConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(providerhallconfig.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderHallConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProviderHallConfigUpsertBulk) Ignore() *ProviderHallConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderHallConfigUpsertBulk) DoNothing() *ProviderHallConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderHallConfigCreateBulk.OnConflict
// documentation for more info.
func (u *ProviderHallConfigUpsertBulk) Update(set func(*ProviderHallConfigUpsert)) *ProviderHallConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderHallConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetCollectionEnabled sets the "collection_enabled" field.
func (u *ProviderHallConfigUpsertBulk) SetCollectionEnabled(v bool) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetCollectionEnabled(v)
	})
}

// UpdateCollectionEnabled sets the "collection_enabled" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateCollectionEnabled() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateCollectionEnabled()
	})
}

// SetDisplayEnabled sets the "display_enabled" field.
func (u *ProviderHallConfigUpsertBulk) SetDisplayEnabled(v bool) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetDisplayEnabled(v)
	})
}

// UpdateDisplayEnabled sets the "display_enabled" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateDisplayEnabled() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateDisplayEnabled()
	})
}

// SetTasksEnabled sets the "tasks_enabled" field.
func (u *ProviderHallConfigUpsertBulk) SetTasksEnabled(v bool) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetTasksEnabled(v)
	})
}

// UpdateTasksEnabled sets the "tasks_enabled" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateTasksEnabled() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateTasksEnabled()
	})
}

// SetDefaultModel sets the "default_model" field.
func (u *ProviderHallConfigUpsertBulk) SetDefaultModel(v string) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetDefaultModel(v)
	})
}

// UpdateDefaultModel sets the "default_model" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateDefaultModel() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateDefaultModel()
	})
}

// SetDefaultProtocol sets the "default_protocol" field.
func (u *ProviderHallConfigUpsertBulk) SetDefaultProtocol(v providerhallconfig.DefaultProtocol) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetDefaultProtocol(v)
	})
}

// UpdateDefaultProtocol sets the "default_protocol" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateDefaultProtocol() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateDefaultProtocol()
	})
}

// SetDefaultRange sets the "default_range" field.
func (u *ProviderHallConfigUpsertBulk) SetDefaultRange(v providerhallconfig.DefaultRange) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetDefaultRange(v)
	})
}

// UpdateDefaultRange sets the "default_range" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateDefaultRange() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateDefaultRange()
	})
}

// SetGatewayOrigin sets the "gateway_origin" field.
func (u *ProviderHallConfigUpsertBulk) SetGatewayOrigin(v string) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetGatewayOrigin(v)
	})
}

// UpdateGatewayOrigin sets the "gateway_origin" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateGatewayOrigin() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateGatewayOrigin()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *ProviderHallConfigUpsertBulk) SetOperatorUserID(v int64) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *ProviderHallConfigUpsertBulk) AddOperatorUserID(v int64) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateOperatorUserID() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateOperatorUserID()
	})
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *ProviderHallConfigUpsertBulk) ClearOperatorUserID() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.ClearOperatorUserID()
	})
}

// SetDailyBudget sets the "daily_budget" field.
func (u *ProviderHallConfigUpsertBulk) SetDailyBudget(v decimal.Decimal) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetDailyBudget(v)
	})
}

// UpdateDailyBudget sets the "daily_budget" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateDailyBudget() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateDailyBudget()
	})
}

// SetExpectedNodes sets the "expected_nodes" field.
func (u *ProviderHallConfigUpsertBulk) SetExpectedNodes(v []string) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetExpectedNodes(v)
	})
}

// UpdateExpectedNodes sets the "expected_nodes" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateExpectedNodes() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateExpectedNodes()
	})
}

// SetVersion sets the "version" field.
func (u *ProviderHallConfigUpsertBulk) SetVersion(v int64) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ProviderHallConfigUpsertBulk) AddVersion(v int64) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateVersion() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ProviderHallConfigUpsertBulk) SetUpdatedBy(v int64) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ProviderHallConfigUpsertBulk) AddUpdatedBy(v int64) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateUpdatedBy() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ProviderHallConfigUpsertBulk) ClearUpdatedBy() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProviderHallConfigUpsertBulk) SetUpdatedAt(v time.Time) *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProviderHallConfigUpsertBulk) UpdateUpdatedAt() *ProviderHallConfigUpsertBulk {
	return u.Update(func(s *ProviderHallConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProviderHallConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProviderHallConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderHallConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderHallConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
