// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/providerhallprofile"
	"github.com/shopspring/decimal"
)

// ProviderHallProfileUpdate is the builder for updating ProviderHallProfile entities.
type ProviderHallProfileUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderHallProfileMutation
}

// Where appends a list predicates to the ProviderHallProfileUpdate builder.
func (_u *ProviderHallProfileUpdate) Where(ps ...predicate.ProviderHallProfile) *ProviderHallProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModel sets the "model" field.
func (_u *ProviderHallProfileUpdate) SetModel(v string) *ProviderHallProfileUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ProviderHallProfileUpdate) SetNillableModel(v *string) *ProviderHallProfileUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ProviderHallProfileUpdate) SetProtocol(v providerhallprofile.Protocol) *ProviderHallProfileUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProviderHallProfileUpdate) SetNillableProtocol(v *providerhallprofile.Protocol) *ProviderHallProfileUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetSupportsTools sets the "supports_tools" field.
func (_u *ProviderHallProfileUpdate) SetSupportsTools(v bool) *ProviderHallProfileUpdate {
	_u.mutation.SetSupportsTools(v)
	return _u
}

// SetNillableSupportsTools sets the "supports_tools" field if the given value is not nil.
func (_u *ProviderHallProfileUpdate) SetNillableSupportsTools(v *bool) *ProviderHallProfileUpdate {
	if v != nil {
		_u.SetSupportsTools(*v)
	}
	return _u
}

// SetOutputLimit sets the "output_limit" field.
func (_u *ProviderHallProfileUpdate) SetOutputLimit(v int) *ProviderHallProfileUpdate {
	_u.mutation.ResetOutputLimit()
	_u.mutation.SetOutputLimit(v)
	return _u
}

// SetNillableOutputLimit sets the "output_limit" field if the given value is not nil.
func (_u *ProviderHallProfileUpdate) SetNillableOutputLimit(v *int) *ProviderHallProfileUpdate {
	if v != nil {
		_u.SetOutputLimit(*v)
	}
	return _u
}

// AddOutputLimit adds value to the "output_limit" field.
func (_u *ProviderHallProfileUpdate) AddOutputLimit(v int) *ProviderHallProfileUpdate {
	_u.mutation.AddOutputLimit(v)
	return _u
}

// SetModelAliases sets the "model_aliases" field.
func (_u *ProviderHallProfileUpdate) SetModelAliases(v []string) *ProviderHallProfileUpdate {
	_u.mutation.SetModelAliases(v)
	return _u
}

// AppendModelAliases appends value to the "model_aliases" field.
func (_u *ProviderHallProfileUpdate) AppendModelAliases(v []string) *ProviderHallProfileUpdate {
	_u.mutation.AppendModelAliases(v)
	return _u
}

// SetReferenceInputPrice sets the "reference_input_price" field.
func (_u *ProviderHallProfileUpdate) SetReferenceInputPrice(v decimal.Decimal) *ProviderHallProfileUpdate {
	_u.mutation.SetReferenceInputPrice(v)
	return _u
}

// SetNillableReferenceInputPrice sets the "reference_input_price" field if the given value is not nil.
func (_u *ProviderHallProfileUpdate) SetNillableReferenceInputPrice(v *decimal.Decimal) *ProviderHallProfileUpdate {
	if v != nil {
		_u.SetReferenceInputPrice(*v)
	}
	return _u
}

// ClearReferenceInputPrice clears the value of the "reference_input_price" field.
func (_u *ProviderHallProfileUpdate) ClearReferenceInputPrice() *ProviderHallProfileUpdate {
	_u.mutation.ClearReferenceInputPrice()
	return _u
}

// SetReferenceCachePrice sets the "reference_cache_price" field.
func (_u *ProviderHallProfileUpdate) SetReferenceCachePrice(v decimal.Decimal) *ProviderHallProfileUpdate {
	_u.mutation.SetReferenceCachePrice(v)
	return _u
}

// SetNillableReferenceCachePrice sets the "reference_cache_price" field if the given value is not nil.
func (_u *ProviderHallProfileUpdate) SetNillableReferenceCachePrice(v *decimal.Decimal) *ProviderHallProfileUpdate {
	if v != nil {
		_u.SetReferenceCachePrice(*v)
	}
	return _u
}

// ClearReferenceCachePrice clears the value of the "reference_cache_price" field.
func (_u *ProviderHallProfileUpdate) ClearReferenceCachePrice() *ProviderHallProfileUpdate {
	_u.mutation.ClearReferenceCachePrice()
	return _u
}

// SetReferenceCacheRate sets the "reference_cache_rate" field.
func (_u *ProviderHallProfileUpdate) SetReferenceCacheRate(v decimal.Decimal) *ProviderHallProfileUpdate {
	_u.mutation.SetReferenceCacheRate(v)
	return _u
}

// SetNillableReferenceCacheRate sets the "reference_cache_rate" field if the given value is not nil.
func (_u *ProviderHallProfileUpdate) SetNillableReferenceCacheRate(v *decimal.Decimal) *ProviderHallProfileUpdate {
	if v != nil {
		_u.SetReferenceCacheRate(*v)
	}
	return _u
}

// ClearReferenceCacheRate clears the value of the "reference_cache_rate" field.
func (_u *ProviderHallProfileUpdate) ClearReferenceCacheRate() *ProviderHallProfileUpdate {
	_u.mutation.ClearReferenceCacheRate()
	return _u
}

// SetReferenceConfirmedAt sets the "reference_confirmed_at" field.
func (_u *ProviderHallProfileUpdate) SetReferenceConfirmedAt(v time.Time) *ProviderHallProfileUpdate {
	_u.mutation.SetReferenceConfirmedAt(v)
	return _u
}

// SetNillableReferenceConfirmedAt sets the "reference_confirmed_at" field if the given value is not nil.
func (_u *ProviderHallProfileUpdate) SetNillableReferenceConfirmedAt(v *time.Time) *ProviderHallProfileUpdate {
	if v != nil {
		_u.SetReferenceConfirmedAt(*v)
	}
	return _u
}

// ClearReferenceConfirmedAt clears the value of the "reference_confirmed_at" field.
func (_u *ProviderHallProfileUpdate) ClearReferenceConfirmedAt() *ProviderHallProfileUpdate {
	_u.mutation.ClearReferenceConfirmedAt()
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProviderHallProfileUpdate) SetVersion(v int64) *ProviderHallProfileUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProviderHallProfileUpdate) SetNillableVersion(v *int64) *ProviderHallProfileUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ProviderHallProfileUpdate) AddVersion(v int64) *ProviderHallProfileUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProviderHallProfileUpdate) SetUpdatedBy(v int64) *ProviderHallProfileUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProviderHallProfileUpdate) SetNillableUpdatedBy(v *int64) *ProviderHallProfileUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ProviderHallProfileUpdate) AddUpdatedBy(v int64) *ProviderHallProfileUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProviderHallProfileUpdate) ClearUpdatedBy() *ProviderHallProfileUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderHallProfileUpdate) SetUpdatedAt(v time.Time) *ProviderHallProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProviderHallProfileMutation object of the builder.
func (_u *ProviderHallProfileUpdate) Mutation() *ProviderHallProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderHallProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderHallProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderHallProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderHallProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderHallProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providerhallprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderHallProfileUpdate) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := providerhallprofile.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProfile.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := providerhallprofile.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProfile.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputLimit(); ok {
		if err := providerhallprofile.OutputLimitValidator(v); err != nil {
			return &ValidationError{Name: "output_limit", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProfile.output_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := providerhallprofile.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProfile.version": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderHallProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerhallprofile.Table, providerhallprofile.Columns, sqlgraph.NewFieldSpec(providerhallprofile.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(providerhallprofile.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(providerhallprofile.FieldProtocol, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SupportsTools(); ok {
		_spec.SetField(providerhallprofile.FieldSupportsTools, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OutputLimit(); ok {
		_spec.SetField(providerhallprofile.FieldOutputLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputLimit(); ok {
		_spec.AddField(providerhallprofile.FieldOutputLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ModelAliases(); ok {
		_spec.SetField(providerhallprofile.FieldModelAliases, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelAliases(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, providerhallprofile.FieldModelAliases, value)
		})
	}
	if value, ok := _u.mutation.ReferenceInputPrice(); ok {
		_spec.SetField(providerhallprofile.FieldReferenceInputPrice, field.TypeString, value)
	}
	if _u.mutation.ReferenceInputPriceCleared() {
		_spec.ClearField(providerhallprofile.FieldReferenceInputPrice, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceCachePrice(); ok {
		_spec.SetField(providerhallprofile.FieldReferenceCachePrice, field.TypeString, value)
	}
	if _u.mutation.ReferenceCachePriceCleared() {
		_spec.ClearField(providerhallprofile.FieldReferenceCachePrice, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceCacheRate(); ok {
		_spec.SetField(providerhallprofile.FieldReferenceCacheRate, field.TypeString, value)
	}
	if _u.mutation.ReferenceCacheRateCleared() {
		_spec.ClearField(providerhallprofile.FieldReferenceCacheRate, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceConfirmedAt(); ok {
		_spec.SetField(providerhallprofile.FieldReferenceConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ReferenceConfirmedAtCleared() {
		_spec.ClearField(providerhallprofile.FieldReferenceConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(providerhallprofile.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(providerhallprofile.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(providerhallprofile.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(providerhallprofile.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(providerhallprofile.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerhallprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerhallprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderHallProfileUpdateOne is the builder for updating a single ProviderHallProfile entity.
type ProviderHallProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderHallProfileMutation
}

// SetModel sets the "model" field.
func (_u *ProviderHallProfileUpdateOne) SetModel(v string) *ProviderHallProfileUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ProviderHallProfileUpdateOne) SetNillableModel(v *string) *ProviderHallProfileUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ProviderHallProfileUpdateOne) SetProtocol(v providerhallprofile.Protocol) *ProviderHallProfileUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProviderHallProfileUpdateOne) SetNillableProtocol(v *providerhallprofile.Protocol) *ProviderHallProfileUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetSupportsTools sets the "supports_tools" field.
func (_u *ProviderHallProfileUpdateOne) SetSupportsTools(v bool) *ProviderHallProfileUpdateOne {
	_u.mutation.SetSupportsTools(v)
	return _u
}

// SetNillableSupportsTools sets the "supports_tools" field if the given value is not nil.
func (_u *ProviderHallProfileUpdateOne) SetNillableSupportsTools(v *bool) *ProviderHallProfileUpdateOne {
	if v != nil {
		_u.SetSupportsTools(*v)
	}
	return _u
}

// SetOutputLimit sets the "output_limit" field.
func (_u *ProviderHallProfileUpdateOne) SetOutputLimit(v int) *ProviderHallProfileUpdateOne {
	_u.mutation.ResetOutputLimit()
	_u.mutation.SetOutputLimit(v)
	return _u
}

// SetNillableOutputLimit sets the "output_limit" field if the given value is not nil.
func (_u *ProviderHallProfileUpdateOne) SetNillableOutputLimit(v *int) *ProviderHallProfileUpdateOne {
	if v != nil {
		_u.SetOutputLimit(*v)
	}
	return _u
}

// AddOutputLimit adds value to the "output_limit" field.
func (_u *ProviderHallProfileUpdateOne) AddOutputLimit(v int) *ProviderHallProfileUpdateOne {
	_u.mutation.AddOutputLimit(v)
	return _u
}

// SetModelAliases sets the "model_aliases" field.
func (_u *ProviderHallProfileUpdateOne) SetModelAliases(v []string) *ProviderHallProfileUpdateOne {
	_u.mutation.SetModelAliases(v)
	return _u
}

// AppendModelAliases appends value to the "model_aliases" field.
func (_u *ProviderHallProfileUpdateOne) AppendModelAliases(v []string) *ProviderHallProfileUpdateOne {
	_u.mutation.AppendModelAliases(v)
	return _u
}

// SetReferenceInputPrice sets the "reference_input_price" field.
func (_u *ProviderHallProfileUpdateOne) SetReferenceInputPrice(v decimal.Decimal) *ProviderHallProfileUpdateOne {
	_u.mutation.SetReferenceInputPrice(v)
	return _u
}

// SetNillableReferenceInputPrice sets the "reference_input_price" field if the given value is not nil.
func (_u *ProviderHallProfileUpdateOne) SetNillableReferenceInputPrice(v *decimal.Decimal) *ProviderHallProfileUpdateOne {
	if v != nil {
		_u.SetReferenceInputPrice(*v)
	}
	return _u
}

// ClearReferenceInputPrice clears the value of the "reference_input_price" field.
func (_u *ProviderHallProfileUpdateOne) ClearReferenceInputPrice() *ProviderHallProfileUpdateOne {
	_u.mutation.ClearReferenceInputPrice()
	return _u
}

// SetReferenceCachePrice sets the "reference_cache_price" field.
func (_u *ProviderHallProfileUpdateOne) SetReferenceCachePrice(v decimal.Decimal) *ProviderHallProfileUpdateOne {
	_u.mutation.SetReferenceCachePrice(v)
	return _u
}

// SetNillableReferenceCachePrice sets the "reference_cache_price" field if the given value is not nil.
func (_u *ProviderHallProfileUpdateOne) SetNillableReferenceCachePrice(v *decimal.Decimal) *ProviderHallProfileUpdateOne {
	if v != nil {
		_u.SetReferenceCachePrice(*v)
	}
	return _u
}

// ClearReferenceCachePrice clears the value of the "reference_cache_price" field.
func (_u *ProviderHallProfileUpdateOne) ClearReferenceCachePrice() *ProviderHallProfileUpdateOne {
	_u.mutation.ClearReferenceCachePrice()
	return _u
}

// SetReferenceCacheRate sets the "reference_cache_rate" field.
func (_u *ProviderHallProfileUpdateOne) SetReferenceCacheRate(v decimal.Decimal) *ProviderHallProfileUpdateOne {
	_u.mutation.SetReferenceCacheRate(v)
	return _u
}

// SetNillableReferenceCacheRate sets the "reference_cache_rate" field if the given value is not nil.
func (_u *ProviderHallProfileUpdateOne) SetNillableReferenceCacheRate(v *decimal.Decimal) *ProviderHallProfileUpdateOne {
	if v != nil {
		_u.SetReferenceCacheRate(*v)
	}
	return _u
}

// ClearReferenceCacheRate clears the value of the "reference_cache_rate" field.
func (_u *ProviderHallProfileUpdateOne) ClearReferenceCacheRate() *ProviderHallProfileUpdateOne {
	_u.mutation.ClearReferenceCacheRate()
	return _u
}

// SetReferenceConfirmedAt sets the "reference_confirmed_at" field.
func (_u *ProviderHallProfileUpdateOne) SetReferenceConfirmedAt(v time.Time) *ProviderHallProfileUpdateOne {
	_u.mutation.SetReferenceConfirmedAt(v)
	return _u
}

// SetNillableReferenceConfirmedAt sets the "reference_confirmed_at" field if the given value is not nil.
func (_u *ProviderHallProfileUpdateOne) SetNillableReferenceConfirmedAt(v *time.Time) *ProviderHallProfileUpdateOne {
	if v != nil {
		_u.SetReferenceConfirmedAt(*v)
	}
	return _u
}

// ClearReferenceConfirmedAt clears the value of the "reference_confirmed_at" field.
func (_u *ProviderHallProfileUpdateOne) ClearReferenceConfirmedAt() *ProviderHallProfileUpdateOne {
	_u.mutation.ClearReferenceConfirmedAt()
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProviderHallProfileUpdateOne) SetVersion(v int64) *ProviderHallProfileUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProviderHallProfileUpdateOne) SetNillableVersion(v *int64) *ProviderHallProfileUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ProviderHallProfileUpdateOne) AddVersion(v int64) *ProviderHallProfileUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProviderHallProfileUpdateOne) SetUpdatedBy(v int64) *ProviderHallProfileUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProviderHallProfileUpdateOne) SetNillableUpdatedBy(v *int64) *ProviderHallProfileUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ProviderHallProfileUpdateOne) AddUpdatedBy(v int64) *ProviderHallProfileUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProviderHallProfileUpdateOne) ClearUpdatedBy() *ProviderHallProfileUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderHallProfileUpdateOne) SetUpdatedAt(v time.Time) *ProviderHallProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProviderHallProfileMutation object of the builder.
func (_u *ProviderHallProfileUpdateOne) Mutation() *ProviderHallProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProviderHallProfileUpdate builder.
func (_u *ProviderHallProfileUpdateOne) Where(ps ...predicate.ProviderHallProfile) *ProviderHallProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderHallProfileUpdateOne) Select(field string, fields ...string) *ProviderHallProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderHallProfile entity.
func (_u *ProviderHallProfileUpdateOne) Save(ctx context.Context) (*ProviderHallProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderHallProfileUpdateOne) SaveX(ctx context.Context) *ProviderHallProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderHallProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderHallProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderHallProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providerhallprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderHallProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := providerhallprofile.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProfile.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := providerhallprofile.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProfile.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputLimit(); ok {
		if err := providerhallprofile.OutputLimitValidator(v); err != nil {
			return &ValidationError{Name: "output_limit", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProfile.output_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := providerhallprofile.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderHallProfile.version": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderHallProfileUpdateOne) sqlSave(ctx context.Context) (_node *ProviderHallProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerhallprofile.Table, providerhallprofile.Columns, sqlgraph.NewFieldSpec(providerhallprofile.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderHallProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providerhallprofile.FieldID)
		for _, f := range fields {
			if !providerhallprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providerhallprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(providerhallprofile.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(providerhallprofile.FieldProtocol, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SupportsTools(); ok {
		_spec.SetField(providerhallprofile.FieldSupportsTools, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OutputLimit(); ok {
		_spec.SetField(providerhallprofile.FieldOutputLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputLimit(); ok {
		_spec.AddField(providerhallprofile.FieldOutputLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ModelAliases(); ok {
		_spec.SetField(providerhallprofile.FieldModelAliases, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelAliases(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, providerhallprofile.FieldModelAliases, value)
		})
	}
	if value, ok := _u.mutation.ReferenceInputPrice(); ok {
		_spec.SetField(providerhallprofile.FieldReferenceInputPrice, field.TypeString, value)
	}
	if _u.mutation.ReferenceInputPriceCleared() {
		_spec.ClearField(providerhallprofile.FieldReferenceInputPrice, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceCachePrice(); ok {
		_spec.SetField(providerhallprofile.FieldReferenceCachePrice, field.TypeString, value)
	}
	if _u.mutation.ReferenceCachePriceCleared() {
		_spec.ClearField(providerhallprofile.FieldReferenceCachePrice, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceCacheRate(); ok {
		_spec.SetField(providerhallprofile.FieldReferenceCacheRate, field.TypeString, value)
	}
	if _u.mutation.ReferenceCacheRateCleared() {
		_spec.ClearField(providerhallprofile.FieldReferenceCacheRate, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceConfirmedAt(); ok {
		_spec.SetField(providerhallprofile.FieldReferenceConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ReferenceConfirmedAtCleared() {
		_spec.ClearField(providerhallprofile.FieldReferenceConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(providerhallprofile.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(providerhallprofile.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(providerhallprofile.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(providerhallprofile.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(providerhallprofile.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerhallprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ProviderHallProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerhallprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
