// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/providerhallprobekey"
)

// ProviderHallProbeKeyUpdate is the builder for updating ProviderHallProbeKey entities.
type ProviderHallProbeKeyUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderHallProbeKeyMutation
}

// Where appends a list predicates to the ProviderHallProbeKeyUpdate builder.
func (_u *ProviderHallProbeKeyUpdate) Where(ps ...predicate.ProviderHallProbeKey) *ProviderHallProbeKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the ProviderHallProbeKeyMutation object of the builder.
func (_u *ProviderHallProbeKeyUpdate) Mutation() *ProviderHallProbeKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderHallProbeKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderHallProbeKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderHallProbeKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderHallProbeKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProviderHallProbeKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(providerhallprobekey.Table, providerhallprobekey.Columns, sqlgraph.NewFieldSpec(providerhallprobekey.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerhallprobekey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderHallProbeKeyUpdateOne is the builder for updating a single ProviderHallProbeKey entity.
type ProviderHallProbeKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderHallProbeKeyMutation
}

// Mutation returns the ProviderHallProbeKeyMutation object of the builder.
func (_u *ProviderHallProbeKeyUpdateOne) Mutation() *ProviderHallProbeKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProviderHallProbeKeyUpdate builder.
func (_u *ProviderHallProbeKeyUpdateOne) Where(ps ...predicate.ProviderHallProbeKey) *ProviderHallProbeKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderHallProbeKeyUpdateOne) Select(field string, fields ...string) *ProviderHallProbeKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderHallProbeKey entity.
func (_u *ProviderHallProbeKeyUpdateOne) Save(ctx context.Context) (*ProviderHallProbeKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderHallProbeKeyUpdateOne) SaveX(ctx context.Context) *ProviderHallProbeKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderHallProbeKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderHallProbeKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProviderHallProbeKeyUpdateOne) sqlSave(ctx context.Context) (_node *ProviderHallProbeKey, err error) {
	_spec := sqlgraph.NewUpdateSpec(providerhallprobekey.Table, providerhallprobekey.Columns, sqlgraph.NewFieldSpec(providerhallprobekey.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderHallProbeKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providerhallprobekey.FieldID)
		for _, f := range fields {
			if !providerhallprobekey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providerhallprobekey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ProviderHallProbeKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerhallprobekey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
