// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/providerhallprobekey"
)

// ProviderHallProbeKey is the model entity for the ProviderHallProbeKey schema.
type ProviderHallProbeKey struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OperatorUserID holds the value of the "operator_user_id" field.
	OperatorUserID int64 `json:"operator_user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// RegisteredBy holds the value of the "registered_by" field.
	RegisteredBy int64 `json:"registered_by,omitempty"`
	// RegisteredAt holds the value of the "registered_at" field.
	RegisteredAt time.Time `json:"registered_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderHallProbeKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providerhallprobekey.FieldID, providerhallprobekey.FieldOperatorUserID, providerhallprobekey.FieldGroupID, providerhallprobekey.FieldRegisteredBy:
			values[i] = new(sql.NullInt64)
		case providerhallprobekey.FieldRegisteredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderHallProbeKey fields.
func (_m *ProviderHallProbeKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providerhallprobekey.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case providerhallprobekey.FieldOperatorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_user_id", values[i])
			} else if value.Valid {
				_m.OperatorUserID = value.Int64
			}
		case providerhallprobekey.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case providerhallprobekey.FieldRegisteredBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field registered_by", values[i])
			} else if value.Valid {
				_m.RegisteredBy = value.Int64
			}
		case providerhallprobekey.FieldRegisteredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field registered_at", values[i])
			} else if value.Valid {
				_m.RegisteredAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderHallProbeKey.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderHallProbeKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProviderHallProbeKey.
// Note that you need to call ProviderHallProbeKey.Unwrap() before calling this method if this ProviderHallProbeKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderHallProbeKey) Update() *ProviderHallProbeKeyUpdateOne {
	return NewProviderHallProbeKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderHallProbeKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderHallProbeKey) Unwrap() *ProviderHallProbeKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderHallProbeKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderHallProbeKey) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderHallProbeKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("operator_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OperatorUserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("registered_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.RegisteredBy))
	builder.WriteString(", ")
	builder.WriteString("registered_at=")
	builder.WriteString(_m.RegisteredAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderHallProbeKeys is a parsable slice of ProviderHallProbeKey.
type ProviderHallProbeKeys []*ProviderHallProbeKey
