// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/providerhalltarget"
)

// ProviderHallTargetDelete is the builder for deleting a ProviderHallTarget entity.
type ProviderHallTargetDelete struct {
	config
	hooks    []Hook
	mutation *ProviderHallTargetMutation
}

// Where appends a list predicates to the ProviderHallTargetDelete builder.
func (_d *ProviderHallTargetDelete) Where(ps ...predicate.ProviderHallTarget) *ProviderHallTargetDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProviderHallTargetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProviderHallTargetDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProviderHallTargetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(providerhalltarget.Table, sqlgraph.NewFieldSpec(providerhalltarget.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProviderHallTargetDeleteOne is the builder for deleting a single ProviderHallTarget entity.
type ProviderHallTargetDeleteOne struct {
	_d *ProviderHallTargetDelete
}

// Where appends a list predicates to the ProviderHallTargetDelete builder.
func (_d *ProviderHallTargetDeleteOne) Where(ps ...predicate.ProviderHallTarget) *ProviderHallTargetDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProviderHallTargetDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{providerhalltarget.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProviderHallTargetDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
