// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/providerhallconfig"
	"github.com/shopspring/decimal"
)

// ProviderHallConfigUpdate is the builder for updating ProviderHallConfig entities.
type ProviderHallConfigUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderHallConfigMutation
}

// Where appends a list predicates to the ProviderHallConfigUpdate builder.
func (_u *ProviderHallConfigUpdate) Where(ps ...predicate.ProviderHallConfig) *ProviderHallConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCollectionEnabled sets the "collection_enabled" field.
func (_u *ProviderHallConfigUpdate) SetCollectionEnabled(v bool) *ProviderHallConfigUpdate {
	_u.mutation.SetCollectionEnabled(v)
	return _u
}

// SetNillableCollectionEnabled sets the "collection_enabled" field if the given value is not nil.
func (_u *ProviderHallConfigUpdate) SetNillableCollectionEnabled(v *bool) *ProviderHallConfigUpdate {
	if v != nil {
		_u.SetCollectionEnabled(*v)
	}
	return _u
}

// SetDisplayEnabled sets the "display_enabled" field.
func (_u *ProviderHallConfigUpdate) SetDisplayEnabled(v bool) *ProviderHallConfigUpdate {
	_u.mutation.SetDisplayEnabled(v)
	return _u
}

// SetNillableDisplayEnabled sets the "display_enabled" field if the given value is not nil.
func (_u *ProviderHallConfigUpdate) SetNillableDisplayEnabled(v *bool) *ProviderHallConfigUpdate {
	if v != nil {
		_u.SetDisplayEnabled(*v)
	}
	return _u
}

// SetTasksEnabled sets the "tasks_enabled" field.
func (_u *ProviderHallConfigUpdate) SetTasksEnabled(v bool) *ProviderHallConfigUpdate {
	_u.mutation.SetTasksEnabled(v)
	return _u
}

// SetNillableTasksEnabled sets the "tasks_enabled" field if the given value is not nil.
func (_u *ProviderHallConfigUpdate) SetNillableTasksEnabled(v *bool) *ProviderHallConfigUpdate {
	if v != nil {
		_u.SetTasksEnabled(*v)
	}
	return _u
}

// SetAutoScheduleEnabled sets the "auto_schedule_enabled" field.
func (_u *ProviderHallConfigUpdate) SetAutoScheduleEnabled(v bool) *ProviderHallConfigUpdate {
	_u.mutation.SetAutoScheduleEnabled(v)
	return _u
}

// SetNillableAutoScheduleEnabled sets the "auto_schedule_enabled" field if the given value is not nil.
func (_u *ProviderHallConfigUpdate) SetNillableAutoScheduleEnabled(v *bool) *ProviderHallConfigUpdate {
	if v != nil {
		_u.SetAutoScheduleEnabled(*v)
	}
	return _u
}

// SetDefaultModel sets the "default_model" field.
func (_u *ProviderHallConfigUpdate) SetDefaultModel(v string) *ProviderHallConfigUpdate {
	_u.mutation.SetDefaultModel(v)
	return _u
}

// SetNillableDefaultModel sets the "default_model" field if the given value is not nil.
func (_u *ProviderHallConfigUpdate) SetNillableDefaultModel(v *string) *ProviderHallConfigUpdate {
	if v != nil {
		_u.SetDefaultModel(*v)
	}
	return _u
}

// SetDefaultProtocol sets the "default_protocol" field.
func (_u *ProviderHallConfigUpdate) SetDefaultProtocol(v providerhallconfig.DefaultProtocol) *ProviderHallConfigUpdate {
	_u.mutation.SetDefaultProtocol(v)
	return _u
}

// SetNillableDefaultProtocol sets the "default_protocol" field if the given value is not nil.
func (_u *ProviderHallConfigUpdate) SetNillableDefaultProtocol(v *providerhallconfig.DefaultProtocol) *ProviderHallConfigUpdate {
	if v != nil {
		_u.SetDefaultProtocol(*v)
	}
	return _u
}

// SetDefaultRange sets the "default_range" field.
func (_u *ProviderHallConfigUpdate) SetDefaultRange(v providerhallconfig.DefaultRange) *ProviderHallConfigUpdate {
	_u.mutation.SetDefaultRange(v)
	return _u
}

// SetNillableDefaultRange sets the "default_range" field if the given value is not nil.
func (_u *ProviderHallConfigUpdate) SetNillableDefaultRange(v *providerhallconfig.DefaultRange) *ProviderHallConfigUpdate {
	if v != nil {
		_u.SetDefaultRange(*v)
	}
	return _u
}

// SetGatewayOrigin sets the "gateway_origin" field.
func (_u *ProviderHallConfigUpdate) SetGatewayOrigin(v string) *ProviderHallConfigUpdate {
	_u.mutation.SetGatewayOrigin(v)
	return _u
}

// SetNillableGatewayOrigin sets the "gateway_origin" field if the given value is not nil.
func (_u *ProviderHallConfigUpdate) SetNillableGatewayOrigin(v *string) *ProviderHallConfigUpdate {
	if v != nil {
		_u.SetGatewayOrigin(*v)
	}
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *ProviderHallConfigUpdate) SetOperatorUserID(v int64) *ProviderHallConfigUpdate {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *ProviderHallConfigUpdate) SetNillableOperatorUserID(v *int64) *ProviderHallConfigUpdate {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *ProviderHallConfigUpdate) AddOperatorUserID(v int64) *ProviderHallConfigUpdate {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *ProviderHallConfigUpdate) ClearOperatorUserID() *ProviderHallConfigUpdate {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetDailyBudget sets the "daily_budget" field.
func (_u *ProviderHallConfigUpdate) SetDailyBudget(v decimal.Decimal) *ProviderHallConfigUpdate {
	_u.mutation.SetDailyBudget(v)
	return _u
}

// SetNillableDailyBudget sets the "daily_budget" field if the given value is not nil.
func (_u *ProviderHallConfigUpdate) SetNillableDailyBudget(v *decimal.Decimal) *ProviderHallConfigUpdate {
	if v != nil {
		_u.SetDailyBudget(*v)
	}
	return _u
}

// SetExpectedNodes sets the "expected_nodes" field.
func (_u *ProviderHallConfigUpdate) SetExpectedNodes(v []string) *ProviderHallConfigUpdate {
	_u.mutation.SetExpectedNodes(v)
	return _u
}

// AppendExpectedNodes appends value to the "expected_nodes" field.
func (_u *ProviderHallConfigUpdate) AppendExpectedNodes(v []string) *ProviderHallConfigUpdate {
	_u.mutation.AppendExpectedNodes(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProviderHallConfigUpdate) SetVersion(v int64) *ProviderHallConfigUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProviderHallConfigUpdate) SetNillableVersion(v *int64) *ProviderHallConfigUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ProviderHallConfigUpdate) AddVersion(v int64) *ProviderHallConfigUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProviderHallConfigUpdate) SetUpdatedBy(v int64) *ProviderHallConfigUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProviderHallConfigUpdate) SetNillableUpdatedBy(v *int64) *ProviderHallConfigUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ProviderHallConfigUpdate) AddUpdatedBy(v int64) *ProviderHallConfigUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProviderHallConfigUpdate) ClearUpdatedBy() *ProviderHallConfigUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderHallConfigUpdate) SetUpdatedAt(v time.Time) *ProviderHallConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProviderHallConfigMutation object of the builder.
func (_u *ProviderHallConfigUpdate) Mutation() *ProviderHallConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderHallConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderHallConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderHallConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderHallConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderHallConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providerhallconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderHallConfigUpdate) check() error {
	if v, ok := _u.mutation.DefaultModel(); ok {
		if err := providerhallconfig.DefaultModelValidator(v); err != nil {
			return &ValidationError{Name: "default_model", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.default_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultProtocol(); ok {
		if err := providerhallconfig.DefaultProtocolValidator(v); err != nil {
			return &ValidationError{Name: "default_protocol", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.default_protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultRange(); ok {
		if err := providerhallconfig.DefaultRangeValidator(v); err != nil {
			return &ValidationError{Name: "default_range", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.default_range": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GatewayOrigin(); ok {
		if err := providerhallconfig.GatewayOriginValidator(v); err != nil {
			return &ValidationError{Name: "gateway_origin", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.gateway_origin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperatorUserID(); ok {
		if err := providerhallconfig.OperatorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "operator_user_id", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.operator_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := providerhallconfig.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.version": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderHallConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerhallconfig.Table, providerhallconfig.Columns, sqlgraph.NewFieldSpec(providerhallconfig.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CollectionEnabled(); ok {
		_spec.SetField(providerhallconfig.FieldCollectionEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DisplayEnabled(); ok {
		_spec.SetField(providerhallconfig.FieldDisplayEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TasksEnabled(); ok {
		_spec.SetField(providerhallconfig.FieldTasksEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AutoScheduleEnabled(); ok {
		_spec.SetField(providerhallconfig.FieldAutoScheduleEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultModel(); ok {
		_spec.SetField(providerhallconfig.FieldDefaultModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultProtocol(); ok {
		_spec.SetField(providerhallconfig.FieldDefaultProtocol, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DefaultRange(); ok {
		_spec.SetField(providerhallconfig.FieldDefaultRange, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GatewayOrigin(); ok {
		_spec.SetField(providerhallconfig.FieldGatewayOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(providerhallconfig.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(providerhallconfig.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(providerhallconfig.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DailyBudget(); ok {
		_spec.SetField(providerhallconfig.FieldDailyBudget, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpectedNodes(); ok {
		_spec.SetField(providerhallconfig.FieldExpectedNodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExpectedNodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, providerhallconfig.FieldExpectedNodes, value)
		})
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(providerhallconfig.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(providerhallconfig.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(providerhallconfig.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(providerhallconfig.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(providerhallconfig.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerhallconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerhallconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderHallConfigUpdateOne is the builder for updating a single ProviderHallConfig entity.
type ProviderHallConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderHallConfigMutation
}

// SetCollectionEnabled sets the "collection_enabled" field.
func (_u *ProviderHallConfigUpdateOne) SetCollectionEnabled(v bool) *ProviderHallConfigUpdateOne {
	_u.mutation.SetCollectionEnabled(v)
	return _u
}

// SetNillableCollectionEnabled sets the "collection_enabled" field if the given value is not nil.
func (_u *ProviderHallConfigUpdateOne) SetNillableCollectionEnabled(v *bool) *ProviderHallConfigUpdateOne {
	if v != nil {
		_u.SetCollectionEnabled(*v)
	}
	return _u
}

// SetDisplayEnabled sets the "display_enabled" field.
func (_u *ProviderHallConfigUpdateOne) SetDisplayEnabled(v bool) *ProviderHallConfigUpdateOne {
	_u.mutation.SetDisplayEnabled(v)
	return _u
}

// SetNillableDisplayEnabled sets the "display_enabled" field if the given value is not nil.
func (_u *ProviderHallConfigUpdateOne) SetNillableDisplayEnabled(v *bool) *ProviderHallConfigUpdateOne {
	if v != nil {
		_u.SetDisplayEnabled(*v)
	}
	return _u
}

// SetTasksEnabled sets the "tasks_enabled" field.
func (_u *ProviderHallConfigUpdateOne) SetTasksEnabled(v bool) *ProviderHallConfigUpdateOne {
	_u.mutation.SetTasksEnabled(v)
	return _u
}

// SetNillableTasksEnabled sets the "tasks_enabled" field if the given value is not nil.
func (_u *ProviderHallConfigUpdateOne) SetNillableTasksEnabled(v *bool) *ProviderHallConfigUpdateOne {
	if v != nil {
		_u.SetTasksEnabled(*v)
	}
	return _u
}

// SetAutoScheduleEnabled sets the "auto_schedule_enabled" field.
func (_u *ProviderHallConfigUpdateOne) SetAutoScheduleEnabled(v bool) *ProviderHallConfigUpdateOne {
	_u.mutation.SetAutoScheduleEnabled(v)
	return _u
}

// SetNillableAutoScheduleEnabled sets the "auto_schedule_enabled" field if the given value is not nil.
func (_u *ProviderHallConfigUpdateOne) SetNillableAutoScheduleEnabled(v *bool) *ProviderHallConfigUpdateOne {
	if v != nil {
		_u.SetAutoScheduleEnabled(*v)
	}
	return _u
}

// SetDefaultModel sets the "default_model" field.
func (_u *ProviderHallConfigUpdateOne) SetDefaultModel(v string) *ProviderHallConfigUpdateOne {
	_u.mutation.SetDefaultModel(v)
	return _u
}

// SetNillableDefaultModel sets the "default_model" field if the given value is not nil.
func (_u *ProviderHallConfigUpdateOne) SetNillableDefaultModel(v *string) *ProviderHallConfigUpdateOne {
	if v != nil {
		_u.SetDefaultModel(*v)
	}
	return _u
}

// SetDefaultProtocol sets the "default_protocol" field.
func (_u *ProviderHallConfigUpdateOne) SetDefaultProtocol(v providerhallconfig.DefaultProtocol) *ProviderHallConfigUpdateOne {
	_u.mutation.SetDefaultProtocol(v)
	return _u
}

// SetNillableDefaultProtocol sets the "default_protocol" field if the given value is not nil.
func (_u *ProviderHallConfigUpdateOne) SetNillableDefaultProtocol(v *providerhallconfig.DefaultProtocol) *ProviderHallConfigUpdateOne {
	if v != nil {
		_u.SetDefaultProtocol(*v)
	}
	return _u
}

// SetDefaultRange sets the "default_range" field.
func (_u *ProviderHallConfigUpdateOne) SetDefaultRange(v providerhallconfig.DefaultRange) *ProviderHallConfigUpdateOne {
	_u.mutation.SetDefaultRange(v)
	return _u
}

// SetNillableDefaultRange sets the "default_range" field if the given value is not nil.
func (_u *ProviderHallConfigUpdateOne) SetNillableDefaultRange(v *providerhallconfig.DefaultRange) *ProviderHallConfigUpdateOne {
	if v != nil {
		_u.SetDefaultRange(*v)
	}
	return _u
}

// SetGatewayOrigin sets the "gateway_origin" field.
func (_u *ProviderHallConfigUpdateOne) SetGatewayOrigin(v string) *ProviderHallConfigUpdateOne {
	_u.mutation.SetGatewayOrigin(v)
	return _u
}

// SetNillableGatewayOrigin sets the "gateway_origin" field if the given value is not nil.
func (_u *ProviderHallConfigUpdateOne) SetNillableGatewayOrigin(v *string) *ProviderHallConfigUpdateOne {
	if v != nil {
		_u.SetGatewayOrigin(*v)
	}
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *ProviderHallConfigUpdateOne) SetOperatorUserID(v int64) *ProviderHallConfigUpdateOne {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *ProviderHallConfigUpdateOne) SetNillableOperatorUserID(v *int64) *ProviderHallConfigUpdateOne {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *ProviderHallConfigUpdateOne) AddOperatorUserID(v int64) *ProviderHallConfigUpdateOne {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *ProviderHallConfigUpdateOne) ClearOperatorUserID() *ProviderHallConfigUpdateOne {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetDailyBudget sets the "daily_budget" field.
func (_u *ProviderHallConfigUpdateOne) SetDailyBudget(v decimal.Decimal) *ProviderHallConfigUpdateOne {
	_u.mutation.SetDailyBudget(v)
	return _u
}

// SetNillableDailyBudget sets the "daily_budget" field if the given value is not nil.
func (_u *ProviderHallConfigUpdateOne) SetNillableDailyBudget(v *decimal.Decimal) *ProviderHallConfigUpdateOne {
	if v != nil {
		_u.SetDailyBudget(*v)
	}
	return _u
}

// SetExpectedNodes sets the "expected_nodes" field.
func (_u *ProviderHallConfigUpdateOne) SetExpectedNodes(v []string) *ProviderHallConfigUpdateOne {
	_u.mutation.SetExpectedNodes(v)
	return _u
}

// AppendExpectedNodes appends value to the "expected_nodes" field.
func (_u *ProviderHallConfigUpdateOne) AppendExpectedNodes(v []string) *ProviderHallConfigUpdateOne {
	_u.mutation.AppendExpectedNodes(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProviderHallConfigUpdateOne) SetVersion(v int64) *ProviderHallConfigUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProviderHallConfigUpdateOne) SetNillableVersion(v *int64) *ProviderHallConfigUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ProviderHallConfigUpdateOne) AddVersion(v int64) *ProviderHallConfigUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProviderHallConfigUpdateOne) SetUpdatedBy(v int64) *ProviderHallConfigUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProviderHallConfigUpdateOne) SetNillableUpdatedBy(v *int64) *ProviderHallConfigUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ProviderHallConfigUpdateOne) AddUpdatedBy(v int64) *ProviderHallConfigUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProviderHallConfigUpdateOne) ClearUpdatedBy() *ProviderHallConfigUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderHallConfigUpdateOne) SetUpdatedAt(v time.Time) *ProviderHallConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProviderHallConfigMutation object of the builder.
func (_u *ProviderHallConfigUpdateOne) Mutation() *ProviderHallConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProviderHallConfigUpdate builder.
func (_u *ProviderHallConfigUpdateOne) Where(ps ...predicate.ProviderHallConfig) *ProviderHallConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderHallConfigUpdateOne) Select(field string, fields ...string) *ProviderHallConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderHallConfig entity.
func (_u *ProviderHallConfigUpdateOne) Save(ctx context.Context) (*ProviderHallConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderHallConfigUpdateOne) SaveX(ctx context.Context) *ProviderHallConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderHallConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderHallConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderHallConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providerhallconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderHallConfigUpdateOne) check() error {
	if v, ok := _u.mutation.DefaultModel(); ok {
		if err := providerhallconfig.DefaultModelValidator(v); err != nil {
			return &ValidationError{Name: "default_model", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.default_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultProtocol(); ok {
		if err := providerhallconfig.DefaultProtocolValidator(v); err != nil {
			return &ValidationError{Name: "default_protocol", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.default_protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultRange(); ok {
		if err := providerhallconfig.DefaultRangeValidator(v); err != nil {
			return &ValidationError{Name: "default_range", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.default_range": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GatewayOrigin(); ok {
		if err := providerhallconfig.GatewayOriginValidator(v); err != nil {
			return &ValidationError{Name: "gateway_origin", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.gateway_origin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperatorUserID(); ok {
		if err := providerhallconfig.OperatorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "operator_user_id", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.operator_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := providerhallconfig.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProviderHallConfig.version": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderHallConfigUpdateOne) sqlSave(ctx context.Context) (_node *ProviderHallConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerhallconfig.Table, providerhallconfig.Columns, sqlgraph.NewFieldSpec(providerhallconfig.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderHallConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providerhallconfig.FieldID)
		for _, f := range fields {
			if !providerhallconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providerhallconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CollectionEnabled(); ok {
		_spec.SetField(providerhallconfig.FieldCollectionEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DisplayEnabled(); ok {
		_spec.SetField(providerhallconfig.FieldDisplayEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TasksEnabled(); ok {
		_spec.SetField(providerhallconfig.FieldTasksEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AutoScheduleEnabled(); ok {
		_spec.SetField(providerhallconfig.FieldAutoScheduleEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultModel(); ok {
		_spec.SetField(providerhallconfig.FieldDefaultModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultProtocol(); ok {
		_spec.SetField(providerhallconfig.FieldDefaultProtocol, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DefaultRange(); ok {
		_spec.SetField(providerhallconfig.FieldDefaultRange, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GatewayOrigin(); ok {
		_spec.SetField(providerhallconfig.FieldGatewayOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(providerhallconfig.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(providerhallconfig.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(providerhallconfig.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DailyBudget(); ok {
		_spec.SetField(providerhallconfig.FieldDailyBudget, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpectedNodes(); ok {
		_spec.SetField(providerhallconfig.FieldExpectedNodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedExpectedNodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, providerhallconfig.FieldExpectedNodes, value)
		})
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(providerhallconfig.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(providerhallconfig.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(providerhallconfig.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(providerhallconfig.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(providerhallconfig.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerhallconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ProviderHallConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerhallconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
