// Code generated by ent, DO NOT EDIT.

package providerhallprofile

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the providerhallprofile type in the database.
	Label = "provider_hall_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldSupportsTools holds the string denoting the supports_tools field in the database.
	FieldSupportsTools = "supports_tools"
	// FieldOutputLimit holds the string denoting the output_limit field in the database.
	FieldOutputLimit = "output_limit"
	// FieldModelAliases holds the string denoting the model_aliases field in the database.
	FieldModelAliases = "model_aliases"
	// FieldReferenceInputPrice holds the string denoting the reference_input_price field in the database.
	FieldReferenceInputPrice = "reference_input_price"
	// FieldReferenceCachePrice holds the string denoting the reference_cache_price field in the database.
	FieldReferenceCachePrice = "reference_cache_price"
	// FieldReferenceCacheRate holds the string denoting the reference_cache_rate field in the database.
	FieldReferenceCacheRate = "reference_cache_rate"
	// FieldReferenceConfirmedAt holds the string denoting the reference_confirmed_at field in the database.
	FieldReferenceConfirmedAt = "reference_confirmed_at"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the providerhallprofile in the database.
	Table = "provider_hall_profiles"
)

// Columns holds all SQL columns for providerhallprofile fields.
var Columns = []string{
	FieldID,
	FieldModel,
	FieldProtocol,
	FieldSupportsTools,
	FieldOutputLimit,
	FieldModelAliases,
	FieldReferenceInputPrice,
	FieldReferenceCachePrice,
	FieldReferenceCacheRate,
	FieldReferenceConfirmedAt,
	FieldVersion,
	FieldUpdatedBy,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultSupportsTools holds the default value on creation for the "supports_tools" field.
	DefaultSupportsTools bool
	// DefaultOutputLimit holds the default value on creation for the "output_limit" field.
	DefaultOutputLimit int
	// OutputLimitValidator is a validator for the "output_limit" field. It is called by the builders before save.
	OutputLimitValidator func(int) error
	// DefaultModelAliases holds the default value on creation for the "model_aliases" field.
	DefaultModelAliases []string
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int64) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Protocol defines the type for the "protocol" enum field.
type Protocol string

// Protocol values.
const (
	ProtocolResponses       Protocol = "responses"
	ProtocolChatCompletions Protocol = "chat_completions"
	ProtocolMessages        Protocol = "messages"
)

func (pr Protocol) String() string {
	return string(pr)
}

// ProtocolValidator is a validator for the "protocol" field enum values. It is called by the builders before save.
func ProtocolValidator(pr Protocol) error {
	switch pr {
	case ProtocolResponses, ProtocolChatCompletions, ProtocolMessages:
		return nil
	default:
		return fmt.Errorf("providerhallprofile: invalid enum value for protocol field: %q", pr)
	}
}

// OrderOption defines the ordering options for the ProviderHallProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// BySupportsTools orders the results by the supports_tools field.
func BySupportsTools(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportsTools, opts...).ToFunc()
}

// ByOutputLimit orders the results by the output_limit field.
func ByOutputLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputLimit, opts...).ToFunc()
}

// ByReferenceInputPrice orders the results by the reference_input_price field.
func ByReferenceInputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceInputPrice, opts...).ToFunc()
}

// ByReferenceCachePrice orders the results by the reference_cache_price field.
func ByReferenceCachePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceCachePrice, opts...).ToFunc()
}

// ByReferenceCacheRate orders the results by the reference_cache_rate field.
func ByReferenceCacheRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceCacheRate, opts...).ToFunc()
}

// ByReferenceConfirmedAt orders the results by the reference_confirmed_at field.
func ByReferenceConfirmedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceConfirmedAt, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
