// Code generated by ent, DO NOT EDIT.

package providerhallprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLTE(FieldID, id))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldModel, v))
}

// SupportsTools applies equality check predicate on the "supports_tools" field. It's identical to SupportsToolsEQ.
func SupportsTools(v bool) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldSupportsTools, v))
}

// OutputLimit applies equality check predicate on the "output_limit" field. It's identical to OutputLimitEQ.
func OutputLimit(v int) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldOutputLimit, v))
}

// ReferenceInputPrice applies equality check predicate on the "reference_input_price" field. It's identical to ReferenceInputPriceEQ.
func ReferenceInputPrice(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldReferenceInputPrice, v))
}

// ReferenceCachePrice applies equality check predicate on the "reference_cache_price" field. It's identical to ReferenceCachePriceEQ.
func ReferenceCachePrice(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldReferenceCachePrice, v))
}

// ReferenceCacheRate applies equality check predicate on the "reference_cache_rate" field. It's identical to ReferenceCacheRateEQ.
func ReferenceCacheRate(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldReferenceCacheRate, v))
}

// ReferenceConfirmedAt applies equality check predicate on the "reference_confirmed_at" field. It's identical to ReferenceConfirmedAtEQ.
func ReferenceConfirmedAt(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldReferenceConfirmedAt, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldVersion, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldContainsFold(FieldModel, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v Protocol) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v Protocol) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...Protocol) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...Protocol) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotIn(FieldProtocol, vs...))
}

// SupportsToolsEQ applies the EQ predicate on the "supports_tools" field.
func SupportsToolsEQ(v bool) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldSupportsTools, v))
}

// SupportsToolsNEQ applies the NEQ predicate on the "supports_tools" field.
func SupportsToolsNEQ(v bool) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNEQ(FieldSupportsTools, v))
}

// OutputLimitEQ applies the EQ predicate on the "output_limit" field.
func OutputLimitEQ(v int) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldOutputLimit, v))
}

// OutputLimitNEQ applies the NEQ predicate on the "output_limit" field.
func OutputLimitNEQ(v int) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNEQ(FieldOutputLimit, v))
}

// OutputLimitIn applies the In predicate on the "output_limit" field.
func OutputLimitIn(vs ...int) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIn(FieldOutputLimit, vs...))
}

// OutputLimitNotIn applies the NotIn predicate on the "output_limit" field.
func OutputLimitNotIn(vs ...int) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotIn(FieldOutputLimit, vs...))
}

// OutputLimitGT applies the GT predicate on the "output_limit" field.
func OutputLimitGT(v int) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGT(FieldOutputLimit, v))
}

// OutputLimitGTE applies the GTE predicate on the "output_limit" field.
func OutputLimitGTE(v int) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGTE(FieldOutputLimit, v))
}

// OutputLimitLT applies the LT predicate on the "output_limit" field.
func OutputLimitLT(v int) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLT(FieldOutputLimit, v))
}

// OutputLimitLTE applies the LTE predicate on the "output_limit" field.
func OutputLimitLTE(v int) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLTE(FieldOutputLimit, v))
}

// ReferenceInputPriceEQ applies the EQ predicate on the "reference_input_price" field.
func ReferenceInputPriceEQ(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldReferenceInputPrice, v))
}

// ReferenceInputPriceNEQ applies the NEQ predicate on the "reference_input_price" field.
func ReferenceInputPriceNEQ(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNEQ(FieldReferenceInputPrice, v))
}

// ReferenceInputPriceIn applies the In predicate on the "reference_input_price" field.
func ReferenceInputPriceIn(vs ...decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIn(FieldReferenceInputPrice, vs...))
}

// ReferenceInputPriceNotIn applies the NotIn predicate on the "reference_input_price" field.
func ReferenceInputPriceNotIn(vs ...decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotIn(FieldReferenceInputPrice, vs...))
}

// ReferenceInputPriceGT applies the GT predicate on the "reference_input_price" field.
func ReferenceInputPriceGT(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGT(FieldReferenceInputPrice, v))
}

// ReferenceInputPriceGTE applies the GTE predicate on the "reference_input_price" field.
func ReferenceInputPriceGTE(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGTE(FieldReferenceInputPrice, v))
}

// ReferenceInputPriceLT applies the LT predicate on the "reference_input_price" field.
func ReferenceInputPriceLT(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLT(FieldReferenceInputPrice, v))
}

// ReferenceInputPriceLTE applies the LTE predicate on the "reference_input_price" field.
func ReferenceInputPriceLTE(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLTE(FieldReferenceInputPrice, v))
}

// ReferenceInputPriceContains applies the Contains predicate on the "reference_input_price" field.
func ReferenceInputPriceContains(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldContains(FieldReferenceInputPrice, vc))
}

// ReferenceInputPriceHasPrefix applies the HasPrefix predicate on the "reference_input_price" field.
func ReferenceInputPriceHasPrefix(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldHasPrefix(FieldReferenceInputPrice, vc))
}

// ReferenceInputPriceHasSuffix applies the HasSuffix predicate on the "reference_input_price" field.
func ReferenceInputPriceHasSuffix(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldHasSuffix(FieldReferenceInputPrice, vc))
}

// ReferenceInputPriceIsNil applies the IsNil predicate on the "reference_input_price" field.
func ReferenceInputPriceIsNil() predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIsNull(FieldReferenceInputPrice))
}

// ReferenceInputPriceNotNil applies the NotNil predicate on the "reference_input_price" field.
func ReferenceInputPriceNotNil() predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotNull(FieldReferenceInputPrice))
}

// ReferenceInputPriceEqualFold applies the EqualFold predicate on the "reference_input_price" field.
func ReferenceInputPriceEqualFold(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldEqualFold(FieldReferenceInputPrice, vc))
}

// ReferenceInputPriceContainsFold applies the ContainsFold predicate on the "reference_input_price" field.
func ReferenceInputPriceContainsFold(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldContainsFold(FieldReferenceInputPrice, vc))
}

// ReferenceCachePriceEQ applies the EQ predicate on the "reference_cache_price" field.
func ReferenceCachePriceEQ(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldReferenceCachePrice, v))
}

// ReferenceCachePriceNEQ applies the NEQ predicate on the "reference_cache_price" field.
func ReferenceCachePriceNEQ(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNEQ(FieldReferenceCachePrice, v))
}

// ReferenceCachePriceIn applies the In predicate on the "reference_cache_price" field.
func ReferenceCachePriceIn(vs ...decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIn(FieldReferenceCachePrice, vs...))
}

// ReferenceCachePriceNotIn applies the NotIn predicate on the "reference_cache_price" field.
func ReferenceCachePriceNotIn(vs ...decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotIn(FieldReferenceCachePrice, vs...))
}

// ReferenceCachePriceGT applies the GT predicate on the "reference_cache_price" field.
func ReferenceCachePriceGT(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGT(FieldReferenceCachePrice, v))
}

// ReferenceCachePriceGTE applies the GTE predicate on the "reference_cache_price" field.
func ReferenceCachePriceGTE(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGTE(FieldReferenceCachePrice, v))
}

// ReferenceCachePriceLT applies the LT predicate on the "reference_cache_price" field.
func ReferenceCachePriceLT(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLT(FieldReferenceCachePrice, v))
}

// ReferenceCachePriceLTE applies the LTE predicate on the "reference_cache_price" field.
func ReferenceCachePriceLTE(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLTE(FieldReferenceCachePrice, v))
}

// ReferenceCachePriceContains applies the Contains predicate on the "reference_cache_price" field.
func ReferenceCachePriceContains(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldContains(FieldReferenceCachePrice, vc))
}

// ReferenceCachePriceHasPrefix applies the HasPrefix predicate on the "reference_cache_price" field.
func ReferenceCachePriceHasPrefix(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldHasPrefix(FieldReferenceCachePrice, vc))
}

// ReferenceCachePriceHasSuffix applies the HasSuffix predicate on the "reference_cache_price" field.
func ReferenceCachePriceHasSuffix(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldHasSuffix(FieldReferenceCachePrice, vc))
}

// ReferenceCachePriceIsNil applies the IsNil predicate on the "reference_cache_price" field.
func ReferenceCachePriceIsNil() predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIsNull(FieldReferenceCachePrice))
}

// ReferenceCachePriceNotNil applies the NotNil predicate on the "reference_cache_price" field.
func ReferenceCachePriceNotNil() predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotNull(FieldReferenceCachePrice))
}

// ReferenceCachePriceEqualFold applies the EqualFold predicate on the "reference_cache_price" field.
func ReferenceCachePriceEqualFold(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldEqualFold(FieldReferenceCachePrice, vc))
}

// ReferenceCachePriceContainsFold applies the ContainsFold predicate on the "reference_cache_price" field.
func ReferenceCachePriceContainsFold(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldContainsFold(FieldReferenceCachePrice, vc))
}

// ReferenceCacheRateEQ applies the EQ predicate on the "reference_cache_rate" field.
func ReferenceCacheRateEQ(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldReferenceCacheRate, v))
}

// ReferenceCacheRateNEQ applies the NEQ predicate on the "reference_cache_rate" field.
func ReferenceCacheRateNEQ(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNEQ(FieldReferenceCacheRate, v))
}

// ReferenceCacheRateIn applies the In predicate on the "reference_cache_rate" field.
func ReferenceCacheRateIn(vs ...decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIn(FieldReferenceCacheRate, vs...))
}

// ReferenceCacheRateNotIn applies the NotIn predicate on the "reference_cache_rate" field.
func ReferenceCacheRateNotIn(vs ...decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotIn(FieldReferenceCacheRate, vs...))
}

// ReferenceCacheRateGT applies the GT predicate on the "reference_cache_rate" field.
func ReferenceCacheRateGT(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGT(FieldReferenceCacheRate, v))
}

// ReferenceCacheRateGTE applies the GTE predicate on the "reference_cache_rate" field.
func ReferenceCacheRateGTE(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGTE(FieldReferenceCacheRate, v))
}

// ReferenceCacheRateLT applies the LT predicate on the "reference_cache_rate" field.
func ReferenceCacheRateLT(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLT(FieldReferenceCacheRate, v))
}

// ReferenceCacheRateLTE applies the LTE predicate on the "reference_cache_rate" field.
func ReferenceCacheRateLTE(v decimal.Decimal) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLTE(FieldReferenceCacheRate, v))
}

// ReferenceCacheRateContains applies the Contains predicate on the "reference_cache_rate" field.
func ReferenceCacheRateContains(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldContains(FieldReferenceCacheRate, vc))
}

// ReferenceCacheRateHasPrefix applies the HasPrefix predicate on the "reference_cache_rate" field.
func ReferenceCacheRateHasPrefix(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldHasPrefix(FieldReferenceCacheRate, vc))
}

// ReferenceCacheRateHasSuffix applies the HasSuffix predicate on the "reference_cache_rate" field.
func ReferenceCacheRateHasSuffix(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldHasSuffix(FieldReferenceCacheRate, vc))
}

// ReferenceCacheRateIsNil applies the IsNil predicate on the "reference_cache_rate" field.
func ReferenceCacheRateIsNil() predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIsNull(FieldReferenceCacheRate))
}

// ReferenceCacheRateNotNil applies the NotNil predicate on the "reference_cache_rate" field.
func ReferenceCacheRateNotNil() predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotNull(FieldReferenceCacheRate))
}

// ReferenceCacheRateEqualFold applies the EqualFold predicate on the "reference_cache_rate" field.
func ReferenceCacheRateEqualFold(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldEqualFold(FieldReferenceCacheRate, vc))
}

// ReferenceCacheRateContainsFold applies the ContainsFold predicate on the "reference_cache_rate" field.
func ReferenceCacheRateContainsFold(v decimal.Decimal) predicate.ProviderHallProfile {
	vc := v.String()
	return predicate.ProviderHallProfile(sql.FieldContainsFold(FieldReferenceCacheRate, vc))
}

// ReferenceConfirmedAtEQ applies the EQ predicate on the "reference_confirmed_at" field.
func ReferenceConfirmedAtEQ(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldReferenceConfirmedAt, v))
}

// ReferenceConfirmedAtNEQ applies the NEQ predicate on the "reference_confirmed_at" field.
func ReferenceConfirmedAtNEQ(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNEQ(FieldReferenceConfirmedAt, v))
}

// ReferenceConfirmedAtIn applies the In predicate on the "reference_confirmed_at" field.
func ReferenceConfirmedAtIn(vs ...time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIn(FieldReferenceConfirmedAt, vs...))
}

// ReferenceConfirmedAtNotIn applies the NotIn predicate on the "reference_confirmed_at" field.
func ReferenceConfirmedAtNotIn(vs ...time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotIn(FieldReferenceConfirmedAt, vs...))
}

// ReferenceConfirmedAtGT applies the GT predicate on the "reference_confirmed_at" field.
func ReferenceConfirmedAtGT(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGT(FieldReferenceConfirmedAt, v))
}

// ReferenceConfirmedAtGTE applies the GTE predicate on the "reference_confirmed_at" field.
func ReferenceConfirmedAtGTE(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGTE(FieldReferenceConfirmedAt, v))
}

// ReferenceConfirmedAtLT applies the LT predicate on the "reference_confirmed_at" field.
func ReferenceConfirmedAtLT(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLT(FieldReferenceConfirmedAt, v))
}

// ReferenceConfirmedAtLTE applies the LTE predicate on the "reference_confirmed_at" field.
func ReferenceConfirmedAtLTE(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLTE(FieldReferenceConfirmedAt, v))
}

// ReferenceConfirmedAtIsNil applies the IsNil predicate on the "reference_confirmed_at" field.
func ReferenceConfirmedAtIsNil() predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIsNull(FieldReferenceConfirmedAt))
}

// ReferenceConfirmedAtNotNil applies the NotNil predicate on the "reference_confirmed_at" field.
func ReferenceConfirmedAtNotNil() predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotNull(FieldReferenceConfirmedAt))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLTE(FieldVersion, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderHallProfile) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderHallProfile) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderHallProfile) predicate.ProviderHallProfile {
	return predicate.ProviderHallProfile(sql.NotPredicates(p))
}
