// Code generated by ent, DO NOT EDIT.

package providerhalltarget

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the providerhalltarget type in the database.
	Label = "provider_hall_target"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldProfileID holds the string denoting the profile_id field in the database.
	FieldProfileID = "profile_id"
	// FieldProbeKeyID holds the string denoting the probe_key_id field in the database.
	FieldProbeKeyID = "probe_key_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldProbeIntervalSeconds holds the string denoting the probe_interval_seconds field in the database.
	FieldProbeIntervalSeconds = "probe_interval_seconds"
	// FieldVerificationIntervalSeconds holds the string denoting the verification_interval_seconds field in the database.
	FieldVerificationIntervalSeconds = "verification_interval_seconds"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the providerhalltarget in the database.
	Table = "provider_hall_targets"
)

// Columns holds all SQL columns for providerhalltarget fields.
var Columns = []string{
	FieldID,
	FieldGroupID,
	FieldProfileID,
	FieldProbeKeyID,
	FieldEnabled,
	FieldProbeIntervalSeconds,
	FieldVerificationIntervalSeconds,
	FieldVersion,
	FieldUpdatedBy,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// GroupIDValidator is a validator for the "group_id" field. It is called by the builders before save.
	GroupIDValidator func(int64) error
	// ProfileIDValidator is a validator for the "profile_id" field. It is called by the builders before save.
	ProfileIDValidator func(int64) error
	// ProbeKeyIDValidator is a validator for the "probe_key_id" field. It is called by the builders before save.
	ProbeKeyIDValidator func(int64) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultProbeIntervalSeconds holds the default value on creation for the "probe_interval_seconds" field.
	DefaultProbeIntervalSeconds int
	// ProbeIntervalSecondsValidator is a validator for the "probe_interval_seconds" field. It is called by the builders before save.
	ProbeIntervalSecondsValidator func(int) error
	// DefaultVerificationIntervalSeconds holds the default value on creation for the "verification_interval_seconds" field.
	DefaultVerificationIntervalSeconds int
	// VerificationIntervalSecondsValidator is a validator for the "verification_interval_seconds" field. It is called by the builders before save.
	VerificationIntervalSecondsValidator func(int) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int64) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ProviderHallTarget queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByProfileID orders the results by the profile_id field.
func ByProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfileID, opts...).ToFunc()
}

// ByProbeKeyID orders the results by the probe_key_id field.
func ByProbeKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeKeyID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByProbeIntervalSeconds orders the results by the probe_interval_seconds field.
func ByProbeIntervalSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeIntervalSeconds, opts...).ToFunc()
}

// ByVerificationIntervalSeconds orders the results by the verification_interval_seconds field.
func ByVerificationIntervalSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerificationIntervalSeconds, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
