// Code generated by ent, DO NOT EDIT.

package providerhalltarget

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldGroupID, v))
}

// ProfileID applies equality check predicate on the "profile_id" field. It's identical to ProfileIDEQ.
func ProfileID(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldProfileID, v))
}

// ProbeKeyID applies equality check predicate on the "probe_key_id" field. It's identical to ProbeKeyIDEQ.
func ProbeKeyID(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldProbeKeyID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldEnabled, v))
}

// ProbeIntervalSeconds applies equality check predicate on the "probe_interval_seconds" field. It's identical to ProbeIntervalSecondsEQ.
func ProbeIntervalSeconds(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldProbeIntervalSeconds, v))
}

// VerificationIntervalSeconds applies equality check predicate on the "verification_interval_seconds" field. It's identical to VerificationIntervalSecondsEQ.
func VerificationIntervalSeconds(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldVerificationIntervalSeconds, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldVersion, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLTE(FieldGroupID, v))
}

// ProfileIDEQ applies the EQ predicate on the "profile_id" field.
func ProfileIDEQ(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldProfileID, v))
}

// ProfileIDNEQ applies the NEQ predicate on the "profile_id" field.
func ProfileIDNEQ(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNEQ(FieldProfileID, v))
}

// ProfileIDIn applies the In predicate on the "profile_id" field.
func ProfileIDIn(vs ...int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldIn(FieldProfileID, vs...))
}

// ProfileIDNotIn applies the NotIn predicate on the "profile_id" field.
func ProfileIDNotIn(vs ...int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNotIn(FieldProfileID, vs...))
}

// ProfileIDGT applies the GT predicate on the "profile_id" field.
func ProfileIDGT(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGT(FieldProfileID, v))
}

// ProfileIDGTE applies the GTE predicate on the "profile_id" field.
func ProfileIDGTE(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGTE(FieldProfileID, v))
}

// ProfileIDLT applies the LT predicate on the "profile_id" field.
func ProfileIDLT(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLT(FieldProfileID, v))
}

// ProfileIDLTE applies the LTE predicate on the "profile_id" field.
func ProfileIDLTE(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLTE(FieldProfileID, v))
}

// ProbeKeyIDEQ applies the EQ predicate on the "probe_key_id" field.
func ProbeKeyIDEQ(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldProbeKeyID, v))
}

// ProbeKeyIDNEQ applies the NEQ predicate on the "probe_key_id" field.
func ProbeKeyIDNEQ(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNEQ(FieldProbeKeyID, v))
}

// ProbeKeyIDIn applies the In predicate on the "probe_key_id" field.
func ProbeKeyIDIn(vs ...int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldIn(FieldProbeKeyID, vs...))
}

// ProbeKeyIDNotIn applies the NotIn predicate on the "probe_key_id" field.
func ProbeKeyIDNotIn(vs ...int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNotIn(FieldProbeKeyID, vs...))
}

// ProbeKeyIDGT applies the GT predicate on the "probe_key_id" field.
func ProbeKeyIDGT(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGT(FieldProbeKeyID, v))
}

// ProbeKeyIDGTE applies the GTE predicate on the "probe_key_id" field.
func ProbeKeyIDGTE(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGTE(FieldProbeKeyID, v))
}

// ProbeKeyIDLT applies the LT predicate on the "probe_key_id" field.
func ProbeKeyIDLT(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLT(FieldProbeKeyID, v))
}

// ProbeKeyIDLTE applies the LTE predicate on the "probe_key_id" field.
func ProbeKeyIDLTE(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLTE(FieldProbeKeyID, v))
}

// ProbeKeyIDIsNil applies the IsNil predicate on the "probe_key_id" field.
func ProbeKeyIDIsNil() predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldIsNull(FieldProbeKeyID))
}

// ProbeKeyIDNotNil applies the NotNil predicate on the "probe_key_id" field.
func ProbeKeyIDNotNil() predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNotNull(FieldProbeKeyID))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNEQ(FieldEnabled, v))
}

// ProbeIntervalSecondsEQ applies the EQ predicate on the "probe_interval_seconds" field.
func ProbeIntervalSecondsEQ(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldProbeIntervalSeconds, v))
}

// ProbeIntervalSecondsNEQ applies the NEQ predicate on the "probe_interval_seconds" field.
func ProbeIntervalSecondsNEQ(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNEQ(FieldProbeIntervalSeconds, v))
}

// ProbeIntervalSecondsIn applies the In predicate on the "probe_interval_seconds" field.
func ProbeIntervalSecondsIn(vs ...int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldIn(FieldProbeIntervalSeconds, vs...))
}

// ProbeIntervalSecondsNotIn applies the NotIn predicate on the "probe_interval_seconds" field.
func ProbeIntervalSecondsNotIn(vs ...int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNotIn(FieldProbeIntervalSeconds, vs...))
}

// ProbeIntervalSecondsGT applies the GT predicate on the "probe_interval_seconds" field.
func ProbeIntervalSecondsGT(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGT(FieldProbeIntervalSeconds, v))
}

// ProbeIntervalSecondsGTE applies the GTE predicate on the "probe_interval_seconds" field.
func ProbeIntervalSecondsGTE(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGTE(FieldProbeIntervalSeconds, v))
}

// ProbeIntervalSecondsLT applies the LT predicate on the "probe_interval_seconds" field.
func ProbeIntervalSecondsLT(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLT(FieldProbeIntervalSeconds, v))
}

// ProbeIntervalSecondsLTE applies the LTE predicate on the "probe_interval_seconds" field.
func ProbeIntervalSecondsLTE(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLTE(FieldProbeIntervalSeconds, v))
}

// VerificationIntervalSecondsEQ applies the EQ predicate on the "verification_interval_seconds" field.
func VerificationIntervalSecondsEQ(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldVerificationIntervalSeconds, v))
}

// VerificationIntervalSecondsNEQ applies the NEQ predicate on the "verification_interval_seconds" field.
func VerificationIntervalSecondsNEQ(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNEQ(FieldVerificationIntervalSeconds, v))
}

// VerificationIntervalSecondsIn applies the In predicate on the "verification_interval_seconds" field.
func VerificationIntervalSecondsIn(vs ...int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldIn(FieldVerificationIntervalSeconds, vs...))
}

// VerificationIntervalSecondsNotIn applies the NotIn predicate on the "verification_interval_seconds" field.
func VerificationIntervalSecondsNotIn(vs ...int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNotIn(FieldVerificationIntervalSeconds, vs...))
}

// VerificationIntervalSecondsGT applies the GT predicate on the "verification_interval_seconds" field.
func VerificationIntervalSecondsGT(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGT(FieldVerificationIntervalSeconds, v))
}

// VerificationIntervalSecondsGTE applies the GTE predicate on the "verification_interval_seconds" field.
func VerificationIntervalSecondsGTE(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGTE(FieldVerificationIntervalSeconds, v))
}

// VerificationIntervalSecondsLT applies the LT predicate on the "verification_interval_seconds" field.
func VerificationIntervalSecondsLT(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLT(FieldVerificationIntervalSeconds, v))
}

// VerificationIntervalSecondsLTE applies the LTE predicate on the "verification_interval_seconds" field.
func VerificationIntervalSecondsLTE(v int) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLTE(FieldVerificationIntervalSeconds, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLTE(FieldVersion, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderHallTarget) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderHallTarget) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderHallTarget) predicate.ProviderHallTarget {
	return predicate.ProviderHallTarget(sql.NotPredicates(p))
}
